app/containers/message/index.js
@ggazzo 
This adds more information messages such as `user joined` and `user muted`
=> Add more info messages

app/utils/openLink.android.js, app/utils/openLink.ios.js, ios/RocketChatRN.xcodeproj/project.pbxproj, package-lock.json, package.json
=> URL opens in SafariView on iOS

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, ios/RocketChatRN/Info.plist
=> Fabric fix and location removed

app/ReactotronConfig.js, app/lib/methods/helpers/protectedFunction.js, app/presentation/RoomItem.js, app/utils/log.js, app/views/RoomsListView/index.js
=> RoomsListView re-render

app/views/OAuthView.js, package-lock.json
OAuth was missing in Rocket.Chat.js.SDK.
=> [FIX] OAuth

app/containers/MessageBox/index.js, e2e/09-roominfo.spec.js
Closes #525 
Before:
Every key entered would re-render entire Messagebox (with `setState`).
After:
Message is not persisted on `state` anymore.
I'm using `this` and native TextInput for display and `setState` only for showing/hiding buttons.
=> [FIX] Composer composer's send icon slowness

app/sagas/deepLinking.js, app/sagas/rooms.js, app/sagas/selectServer.js
=> [FIX] Load messages on notification tap

app/lib/rocketchat.js
Closes #581 
Closes #571 
Parameters were wrongly passed to the server, resulting in credentials always being rejected. To fix this, I passed the actual correct keys to the server for LDAP authentication.
=> [FIX] LDAP login

app/lib/methods/subscriptions/rooms.js
=> [FIX] Start loop searching for rooms updates only when connection goes down and SDK has userId

app/containers/ConnectionBadge.js, app/lib/methods/subscriptions/room.js, app/lib/rocketchat.js, app/reducers/connect.js, app/reducers/rooms.js, package.json, yarn.lock
=> [FIX] SDK issues

app/lib/methods/subscriptions/room.js, app/lib/methods/subscriptions/rooms.js, app/lib/rocketchat.js, app/views/SettingsView/index.js
Remove rooms listener and fix lint (from french pr)
=> [FIX] Remove rooms listener

app/lib/methods/getRooms.js, app/lib/realm.js, app/sagas/rooms.js
Now we save `servers.roomsUpdatedAt` instead of querying subscriptions and pick max `updatedAt` date.
=> [FIX] Fetch rooms date

android/app/build.gradle
Debug suffix is useful during development, because with it we can keep debug and release versions of the app on the phone.
The downside is that it doesn't open debug version after running `react-native run-android` causing beginner developers to think something is not right.
I'm removing it for now and keeping the `[DEVELOP]` name and logo.
In future, we can think on having the default as `.debug` suffix, but it would need to be both on Android and iOS and update CircleCI jobs.
=> [CHORE] Remove .debug suffix on Android

.expo/packager-info.json, .expo/settings.json, README.md, package.json
I have added documentation for storybook and also removed the storybook script from package.json
=> [CHORE] Added Storybook documentation

app/containers/EmojiPicker/index.js, app/lib/realm.js, app/lib/rocketchat.js, app/views/NewMessageView.js, app/views/RoomActionsView/index.js, app/views/RoomInfoEditView/index.js, app/views/RoomInfoView/index.js, app/views/RoomMembersView/index.js, app/views/RoomView/List.js, app/views/RoomView/UploadProgress.js, app/views/RoomView/index.js, app/views/RoomsListView/ServerDropdown.js, app/views/RoomsListView/index.js, app/views/SelectedUsersView.js
This PR aims to fix "Cannot create asynchronous query while in a write transaction" error from Realm.
Realm raises this error when the app tries to open an `Results.addListener()` while in a `Realm.write()` operation.
This error is very rare, but it is raised usually when RoomView is opened.
We have too many `listeners` and `writes` in the app and I couldn't find another option.
I got this workaround from a [similar Realm issue on their repo](https://github.com/realm/realm-js/issues/1188#issuecomment-359223918).
Let's see how it goes.
=> [FIX] Add Realm.safeAddListener

app/containers/message/Message.js, app/containers/message/Url.js
FastImage raises error if the image doesn't start with `http` or `https`.
There's some cases returned urls are server's local assets, e.g. `assets/icon.png`.
This PR identifies them and append the server credentials.
=> [FIX] Load local URL image

app/lib/methods/subscriptions/room.js
If someone was typing when the user popped out RoomView, typing state would never be cleared.
=> [FIX] Typing not getting cleared after popping a room

.circleci/config.yml
E2E is always failing on CircleCI because of misconfiguration.
We're running all tests locally for a few months already.
Let's comment out and keep running tests locally for now.
This is planned to be fixed soon.
=> [CHORE] Remove e2e tests from CI

app/views/RoomView/Header/Header.js, app/views/RoomView/Header/index.js, app/views/RoomView/index.js
=> Remove "updating" indicator inside the room

app/sagas/selectServer.js
Check if user is logged to hide splash screen first and fetch server info later.
Also, stop alerting "Wrong url" in case of server is down.
The user is logged in, so the url is correct.
=> [IMPROVEMENT] Lazy fetch server info

app/views/RoomsListView/index.js
We used to do that, but I commented sometime ago.
It started to delay update rooms too much.
Tests:
Closes #931
=> [REGRESSION] Get rooms on app restore

app/lib/rocketchat.js, app/views/ProfileView/index.js
Closes #953 
This PR aims to fix profile update custom fields (phone, mobile, language, etc.). 
The bug was introduced when all the fields on user profile were sent in one object `{ data }.`
But back-end accepts an object in format: `{ data, customFields }`.
=> [FIX]  Profile update

app/views/RoomView/index.js
**Acceptance Criteria**
In one room, after typing "test", and go back, then enter the room, remove "test" message and go back. Then enter the room, it will be empty inputfiled
Closes #923
=> [FIX] Draft message do not go away when whole message is removed

app/views/RoomView/index.js
Closes #988 
Fixes bug. Now users with access to broadcast room can post messages and user without access don't have messagebox and have text 'This room is read only' displayed.
https://drive.google.com/file/d/1S9XjrIy5PuBZO9gb9t095PwkqUn5ThOG/view?usp=sharing
=> [FIX] Broadcast channel is not readonly

app/containers/message/Markdown.js
Improve code to regex empty spaces on quote and works with message with only a md link like a:
```[name](link)```
=> [IMPROVEMENT] Code of regex empty space on quote

app/views/RegisterView.js
=> [NEW] Custom fields on signup

ios/RocketChatRN.xcodeproj/project.pbxproj
=> [CHORE] Renew provisioning profiles

.circleci/config.yml, package.json
This PR updates Detox to 12.11.3 from 12.8.0 in order to make CI pass.
=> [Chore] [CI] [TESTS] update detox to make ci pass

app/containers/Avatar.js
If avatar is a local image (like `/avatar/room.png`), browser is going to convert to `${ serverUrl }/avatar/room.png` automatically.
It doesn't happen by default on RN.
It crashes on Android and returns an empty space on iOS.
This PR fixes this issue by checking if `http` is present and append server URL if it's not.
=> [FIX] Append server URL on avatar if necessary

ios/RocketChatRN.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
=> [FIX] Share extension CI build

app/constants/settings.js, app/views/LoginView.js
Closes #1036
Currently the "Accounts_PasswordReset" property is not used.
The "Forgot password" button may now be hidden when the "Accounts_PasswordReset" property coming from the server is false.
=> [IMPROVEMENT] Hide "Forgot password" by server "Accounts_PasswordReset" property

app/notifications/push/push.ios.js
Turns out react-native-notifications v2 fires `notificationOpened` event even on cold start.
It was dispatching `deepLinkingOpen` twice causing `selectServerRequest` to never finish.
=> [FIX] Endless "connecting" on notification tap on iOS

app/lib/methods/subscriptions/room.js, app/lib/methods/subscriptions/rooms.js, package.json, patches/react-native+0.60.4.patch, yarn.lock
There are some issues on our socket connection handle that this PR fixes.
- When user changes servers, we don't close sockets correctly leaving some sessions hanging until the app is closed.
- There was an issue on our JS SDK fixed here: https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/91
- There was an issue on React Native for iOS fixed here: https://github.com/facebook/react-native/pull/26052
- When user goes offline, reopen socket does a loop requesting data from Rest API
- JS SDK already sends messages to the app, so we are reusing them to fetch data from Rest API instead of maintaining another loop.
I created a local patch for RN (it can take longer to get released), but we can wait for JS SDK to be bumped.
=> [FIX] Handle disconnect and reconnect properly

app/containers/message/Content.js
We need to disable markdown when it is a Thread Reply Preview because it causes weird behaviors.
=> [FIX] Block code on thread preview

app/utils/log.js
`Bugsnag.notify` only accept `Errors`, we need to create a condition because sometimes `RocketChatJS SDK` return an `Object` instead of `Error` on `reject`.
More info:
[Bugsnag notify docs](https://docs.bugsnag.com/platforms/javascript/reporting-handled-errors/#sending-custom-errors)
=> [FIX] Bugsnag notify only accept Error

app/views/RoomsListView/index.js
We can use `willFocus` instead `didFocus` to check if `RoomsListView` needs a re-render.
To check it we can use a instance variable and set it when chats are not equal, when `RoomsListView` receive focus we forceUpdate if it is `true`, when it re-render we can set to `false`.
=> [FIX] Unnecessary rooms list render on focus

app/lib/methods/sendFileMessage.js, app/views/RoomView/UploadProgress.js
Wrong Watermelon instance usage
=> [FIX] Cancel upload and check failed upload

app/views/RoomsListView/index.js
We weren't dispatching `roomsRequest` action if not connected.
`roomsRequest` saga already waits for `isAuthenticated` state: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/rooms.js#L81
This PR may fix some foreground events not fetching rooms updates.
=> [FIX] Dispatch roomsRequest on app foreground event even if not connected

app/containers/markdown/index.js
iOS 13 is causing weird behaviour on markdown and images loaded from URL.
Let's fix markdown for now.
=> [REGRESSION] Markdown text

app/views/RoomsListView/index.js, ios/Podfile.lock, ios/Pods/Headers/Private/RNReanimated/REACallFuncNode.h, ios/Pods/Headers/Private/RNReanimated/REAFunctionNode.h, ios/Pods/Headers/Private/RNReanimated/REAParamNode.h, ios/Pods/Headers/Public/RNReanimated/REACallFuncNode.h, ios/Pods/Headers/Public/RNReanimated/REAFunctionNode.h, ios/Pods/Headers/Public/RNReanimated/REAParamNode.h, ios/Pods/Local Podspecs/RNReanimated.podspec.json, ios/Pods/Manifest.lock, ios/Pods/Pods.xcodeproj/project.pbxproj, package.json, yarn.lock
=> [CHORE] Update react-native-reanimated to 1.3.0

app/sagas/init.js
We need to run migration only one time.
=> [FIX] Run credentials migration only once

app/containers/markdown/AtMention.js, app/containers/markdown/Hashtag.js, app/containers/markdown/Link.js, app/containers/markdown/index.js
* Fix preview with quote
* Fix preview with mention
* Fix preview with hashtag
* Fix last message with link
=> [FIX] Some issues on preview message

app/views/JitsiMeetView.js
It usually happens when the user taps Android back button.
=> [FIX] End Jitsi call on unmount

android/app/src/debug/AndroidManifest.xml, android/app/src/debug/res/xml/react_native_config.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml
We need to allow app to use self-signed certificates (ssl) from "user" and "system" on Android devices.
Closes #1307 .
=> [FIX] Allow self-signed certificates

app/lib/database/index.js
When we have a server with `https://open.rocket.chat/rocketchat` [subpath] it raises an error because we try to create and read a database file with name `open.rocket.chat/rocketchat`.
To fix it after remove `http://` or `https://` I replace all `/` with `.`, it will create `open.rocket.chat.rocketchat` and you can use multiples servers with differents `subpaths.
=> [FIX] Server with subpath

app/views/NewServerView.js
If users put `https:\\open.rocket.chat` it raises an error, but it work's how expected on google chrome and can cause a bit confusing on users..
We can replace all `\` with `/`.
=> [FIX] Server with backslash

app/lib/methods/getSettings.js, app/lib/rocketchat.js, app/sagas/selectServer.js
@RocketChat/reactnative 
After we start `serverSelectRequest` the `RocketChat.connect` is started and call `login`, when login success we call `fetchCustomEmojis`, `fetchPermissions` and this access `redux.getState().server.version`, but if we get this before `serverSelectSuccess` we have a null version.. it can occur when `/api/info` is slower than `/login`..
Other possible approach is create a action `setVersion` and call it when `getServerInfo` 🤔 ...
What do you think?
=> [FIX] Invalid version

app/presentation/RoomItem/Touchable.js, app/presentation/RoomItem/index.js
Closes #1311 #1289
Sorry, by mistake I messed up #1311 code, so I am raising this new PR with all the conflicts resolved
=> [CHORE] Refactor RoomItem touchable

app/lib/methods/subscriptions/rooms.js, app/sagas/rooms.js
Save subscription.lastMessage on messages collection without entering the room.
**Important:** use a database browser (like DB Browser for SQLite) to make sure all DMLs happened outside RoomView.
- Logout (just to clear the database)
- Login
- All last messages should have been inserted on messages collection 
- With app closed, receive a new message
- Restore the app
- Check if the message was inserted on db
- With app closed, receive an update to an existing last message
- Restore the app
- Check if the message was updated on db
- With app opened, receive a new message
- Check if the message was inserted on db
- With app opened, receive an update to an existing last message
- Check if the message was updated on db
=> [IMPROVEMENT] Save last message as message when subscription changes

package.json, yarn.lock
[Our PR was merged](https://github.com/ptomasroos/react-native-scrollable-tab-view/pull/1039), so we can use the official version of `react-native-scrollable-tab-view` again.
=> [CHORE] Remove react-native-scrollable-tab-view fork

app/lib/methods/helpers/parseUrls.js
Implement a case of `image` from `url` that not have host, following web client:
https://github.com/RocketChat/Rocket.Chat/blob/d53e264b83ccc971236123853e4b68c9eb6beeb4/app/oembed/client/oembedUrlWidget.js
=> [FIX] Parse Urls

app/lib/methods/subscriptions/room.js, app/lib/methods/subscriptions/rooms.js, app/sagas/rooms.js, app/views/RoomView/List.js, app/views/RoomView/index.js
- Debounce RoomView's list updates
- Fix a few concurrency error updates
- Removed LastMessage being inserted as Message for now
=> [FIX] Load messages issues

app/notifications/inApp/index.js
Closes #1396 
In-app notification were working nicely for directs or groups, but not channels.
=> [FIX] In-app notification showing wrong content on channels

app/views/NewServerView.js
This PR fixes a crash happening on Android only in case of the user entered a whitespace on server URL, like `https:// open. rocket. chat`.
It wouldn't just raise an error on iOS.
Now we're removing whitespaces and it would submit the correct URL even with the typo.
=> [FIX] Prevent server with whitespace

app/views/RoomView/List.js, app/views/RoomView/index.js
Closes #1408 
Sometimes when the app goes foreground, the room loses track of its observables on Android (tried to reproduce it on iOS, but I couldn't).
Easiest way to reproduce it is following the steps written on #1408
=> [FIX] Messages stop loading

app/actions/login.js, app/lib/rocketchat.js, app/sagas/deepLinking.js, app/sagas/login.js, app/sagas/selectServer.js
This PR adds the capability of logging in via deep linking.
Docs: https://rocket.chat/docs/developer-guides/deeplink/#deeplink
The logic is really simple: it's just call `RocketChat.connect` with resume token, but I had to change the code a little, because the server response when login fails is hard to track down on the app and we have so many ways to login that makes even worse.
We can login via:
- Password
- Register
- OAuth/SSO
- Resume the app
- Deep linking
In all of them, we have to tell the user if the login was succeeded or not, but when resuming the app we have to make sure the user is logged out automatically.
Because of this I've created `logoutOnError` prop, that is default `false` and it's `true` only when the app is resumed.
=> [IMPROVEMENT] Authentication via deep linking

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/markdown/index.js
=> [IMPROVEMENT] Markdown performance when identifying emoji only content

app/views/RoomsListView/index.js
=> [FIX] Rooms grouping not working properly

app/lib/methods/sendMessage.js, app/views/RoomView/index.js
Attempt to fix same issue as #1455
=> [FIX] Messages being sent but showing as temp status

app/views/LoginSignupView.js
Fix background color on login.
=> [FIX] Incorrect background color login on iPad

app/views/ShareView/index.js
While content is posted to server you could tap "send", this causes multiple repeated messages.
This PR prevent clicks while send is loading.
=> [FIX] Prevent multiple tap on send (Share Extension)

app/containers/MessageBox/index.js, app/views/RoomView/index.js
Closes #1524 
`withTheme` don't forward refs.
Instead of modifying it to do so, I just forwarded `theme` to `Messagebox`.
I think it was wrong anyway.
Passing `theme` as prop to `Messagebox` helps writing tests :)
=> [FIX] Draft messages not working with themed Messagebox

app/views/RoomMembersView/index.js
Closes #1517
This Pr fixes the issue. Actually the issue was around the code `if(query)` . When no previous conversation data was present, `query` would be an empty array and not `undefined`. Hence the `if` block was always getting executed even if there was no data. SO i changed it to `query.length` which gives 0 when there is nothing inside `query` so that the `else` block gets executed.
=> [FIX] Go to direct message from members list

app/views/AuthenticationWebView.js, app/views/LoginSignupView.js
Instead of creating a token, sending it to idp and waiting for a validation, we're just opening idp and waiting for a token.
=> [FIX] Make SAML wait for idp token instead of creating it on client

app/sagas/selectServer.js
We'll remove the patch version from `/api/info`, so it will return only `2.4` for example, instead of `2.4.0`.
Semver needs a valid version, with `coerce` the version will be fixed.
=> [CHORE] Update to new server response

app/lib/methods/helpers/normalizeMessage.js
Closes #1521 
An earlier workaround was preventing Realm from inserting users without a username.
That was ages ago and now we're using WatermelonDB.
If we prevent blank users from appearing, it'll cause messages to stop loading because of the error.
Let the blank users show on the app and the behaviour stays the same as web (the real issue is the blank users).
We're already working on a fix for that.
In the meantime, let's fix the app.
=> [FIX] Insert messages with blank users

app/presentation/RoomItem/LastMessage.js
Attempt to fix an annoying error caused by empty `u` object on `lastMessage`.
Closes #1582
=> [FIX] Add username block condition to prevent error

app/sagas/login.js
=> [FIX] Change force logout rule

app/lib/methods/subscriptions/room.js, app/lib/rocketchat.js, app/views/RoomView/index.js
In bad internet connections, some unsubscribe calls used to fail.
This PR refactors `subscribeRoom` to use a class, so it's easier to manage across rooms.
Example:
If the phone loses the internet connection, SDK takes some time before acting as disconnected state.
In the meantime, the user can make DDP calls and the SDK will queue them and execute when internet is up again.
- Focus on RoomsListView
- Disconnect from internet
- Go to DM A
- Go back to rooms list
- Go to DM B
- Connect to internet
- Wait for SDK to get connection again
- Only streams from DM B should be open
=> [FIX] Unsubscribe from room

app/containers/MessageActions.js, app/views/InviteUsersView/index.js, app/views/RoomActionsView/index.js
App crashes with `At least one of URL and message is required` in case of empty url.
=> [FIX] Disallow empty sharing

app/containers/MessageActions.js, app/i18n/locales/en.js, app/i18n/locales/pt-BR.js, app/utils/info.js, app/views/SettingsView/index.js
In this PR was done:
* Exported delete message Alert into `showConfirmationAlert(message, title, CTA, onPress)`method in `/utils/info.js`
* Used this in "Logout" and "Clear local server cache".
* Added ptBR Intl for the new messages.
=> [NEW] Confirm logout/clear cache

app/containers/UIKit/utils.js, app/lib/methods/actions.js
=> [FIX] Unhandled action on UIKit

app/actions/notification.js, app/containers/UIKit/MultiSelect/Items.js, app/containers/UIKit/MultiSelect/styles.js, app/containers/UIKit/Overflow.js, app/containers/markdown/Table.js, app/lib/methods/actions.js, app/lib/methods/subscriptions/rooms.js, app/lib/rocketchat.js, app/notifications/inApp/index.js, app/views/ModalBlockView.js, app/views/RoomsListView/index.js
=> [FIX] Small Fixes on UiKit

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/markdown/AtMention.js, app/containers/markdown/Hashtag.js
=> [REGRESSION] Remove @ and # from mention

app/lib/methods/getSlashCommands.js
If a slash command was deleted from the server, we were keeping it on local database, causing the above issue.
=> [FIX] Delete slash commands

app/containers/MessageBox/index.js
react-native-image-crop-picker throws an error when user cancelled the event, like `User cancelled image selection`.
=> [FIX] Stop logging react-native-image-crop-picker

app/containers/Toast.js
=> [FIX] Prevent toast ref error

app/containers/message/Reactions.js
There's a weird case when `reactions` is not an array.
=> [FIX] Prevent reaction map error

app/containers/message/MessageAvatar.js, app/containers/message/index.js, app/views/MessagesView/index.js, app/views/SearchMessagesView/index.js
After clicking on MessageAvatar from MessagesView or SearchMessagesView, the app would crash.
I added the missing calls and missing default props for every Message function.
=> [FIX] Add missing calls to user info

app/utils/media.js
We have a description on server configuration about `Accepted Media Types`, to keep it blank to accept all media types, but sometimes administrators are confused because put a `*` and it not works, so, now we'll accept `*` as `all media types`.
=> [FIX] Accept all media types using *

yarn.lock
Commonmark use a regex like `/ \n/` to split lines before parse it, but when it does this, all blank lines disappear, to fix this I create our own split function, that not will ignore blank lines.
Before:
`'a\n\n\na' => ['a', '', '', 'a'];` 
After:
`'a\n\n\na' => ['a\n\n', 'a'];`
Closes #1513.
=> [FIX] Markdown Line Break

app/views/AuthLoadingView.js, app/views/SettingsView/index.js
Calling `loginRequest` was making SDK to stop working properly.
Instead, this PR calls `selectServerRequest`, which disconnects SDK and connects again.
=> [FIX] Consecutive clear cache calls freezing app

app/index.js, app/share.js, ios/Podfile.lock, ios/Pods/Local Podspecs/RNUserDefaults.podspec.json, ios/Pods/Manifest.lock, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist, package.json, patches/react-native+0.61.5.patch, patches/react-native-notifications+2.0.6.patch, yarn.lock
=> [IMPROVEMENT] Create App Group property on Info.plist

app/views/NewServerView.js
@djorkaeffalexandre 
Closes #1928 
Passing `host` rather than `origin` doesn't give the `url` any idea about the protocol being `http` or `https`
`origin` gives us a url with a protocol.
=> [FIX] Respect protocol in HTTP Auth IPs

app/views/LoginSignupView.js
LinkedIn updated his OAuth2 link, how we can see [here](https://developer.linkedin.com/blog/posts/2018/redirecting-oauth-uas), we need to use the new link.
=> [FIX] Use new LinkedIn OAuth url

app/lib/rocketchat.js, app/selectors/login.js, app/views/RegisterView.js, app/views/RoomsListView/ServerDropdown.js, app/views/WorkspaceView/index.js
- Log in any server
- Add a server but don't log in
- Open ServerDropdown and tap the unlogged server
- The app should navigate to that server's Workspace
- The app should enable to go back to previous server (via close button on NewServerView)
- The app should show login button on WorkspaceView and RegisterView only if `Accounts_ShowFormLogin` is enabled or it there's any login service (OAuth or SSO) available.
=> [FIX] Add server and hide login

app/views/RoomView/index.js
This PR fixes the app inserting thread message without rid, which was causing `UNIQUE constraint failed`.
How to reproduce:
- Make sure you didn't join `#dev`
- Go to `#dev`
- Scroll until February
Without this PR, the app would fail loading all messages.
=> [FIX] Single message thread inserting thread without rid

app/views/ThreadMessagesView/index.js
=> [FIX] ThreadMessagesView crashing on load

app/containers/TwoFactor/index.js, app/containers/TwoFactor/styles.js, app/lib/rocketchat.js
We need to support older totp method on login.
It's not using totp headers on older servers.
=> [FIX] Login TOTP Compatibility to older servers

app/views/RoomView/List.js
I faced a problem while ago, some messages aren't threads and was considered as thread, then, when I tried to click on one of this messages, the app crashed.
On this PR I fixed this error, preventing this crash, it's hard to reproduce, so, I followed these steps:
* Open your database
* Add `tmid` to some message
* Try to click on this message
If you have some reproducible test for this, please comment here.
Thanks.
=> [FIX] Prevent crash when thread is not found

app/views/RoomsListView/index.js
Pay attention at the header of RoomView.
Before this PR, we're able to click on another roomItem while navigating, so, the header receives new navigation params and be incorrect.
=> [FIX] Prevent double click

app/constants/settings.js, app/lib/rocketchat.js, app/views/RoomActionsView/index.js, app/views/RoomInfoEditView/index.js, app/views/RoomInfoView/index.js, app/views/RoomView/index.js
=> [FIX] Respect UI_Allow_room_names_with_special_chars setting

app/views/RoomsListView/index.js
It's not the best solution, but react-navigation v4 had a problem with navigation lifecycle, some events aren't fired sometimes, refer to [this issue](https://github.com/react-navigation/react-navigation/issues/4867), while we wait to upgrade to react-navigation-v5, this will fix the problem.
Steps to reproduce:
* RoomsList
* Open directory
* Select Users
* Select some user
* Send a message
* Go back to RoomsList
-> WillFocus is not fired
=> [FIX] RoomsList update sometimes isn't fired

app/actions/actionsTypes.js, app/actions/room.js, app/lib/methods/subscriptions/room.js, app/lib/methods/subscriptions/rooms.js, app/reducers/room.js
`rooms` stream returns `subscription.lastMessage` info.
`room` stream returns all messages.
Both streams inserts it as a Message record on database.
Let's stop inserting it on `rooms` stream if the room is focused, so we have less tasks to do.
=> [IMPROVEMENT] Stop inserting last message as message object from rooms stream if room is focused

app/lib/rocketchat.js
=> [FIX] Prevent crash when room.uids was not inserted yet

app/sagas/deepLinking.js
Enables room params on auth deep linking.
```
https://go.rocket.chat/auth?host=${ HOST }&token=${ TOKEN }&userId=${ USERID }&path=${ PATH }
rocketchat://auth?host=${ HOST }&token=${ TOKEN }&userId=${ USERID }&path=${ PATH }
```
=> [IMPROVEMENT] Enable navigating to a room from auth deep linking

app/utils/goRoom.js, app/views/NewMessageView.js, app/views/RoomsListView/index.js
=> [FIX] NewMessageView Press Item should open DM

app/utils/theme.js
Sometimes `changeNavigationBarColor` throws an error saying that hasn't have an activity attached, so, we'll do the same thing of #1649, and wait to the activity be attached.
=> [FIX] Wait attach activity before changeNavigationBarColor

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/UIKit/Section.js, app/containers/UIKit/index.js, storybook/stories/Message.js, storybook/stories/UiKitMessage.js, storybook/stories/index.js
Closes #672.
[Here](https://drive.google.com/file/d/1g-LuC9fdny_TOms2z3A7V1_Ixm3yRJrJ/view?usp=sharing) I have just changed our classic poll app to send a specific message containing the content that crashes the app, so, just install this app on your server and try to submit some poll. :)
=> [FIX] UIKit crash when some app send a list

app/constants/localAuthentication.js, app/lib/methods/getSettings.js, app/views/ScreenLockConfigView.js
I've changed the logic about enable/disable by admin on server settings, now, when the admin disable the `Force_Screen_Lock`, we'll check if the current value of autoLockTime is one of our default values, if yes, we'll show this option as selected, but, if not, we'll show the current option of time, until the user change to some default option, then the older admin option will just be hide.
=> [FIX] Screen Lock options i18n

app/containers/MessageBox/index.js
Reverts RocketChat/Rocket.Chat.ReactNative#2106
Unfortunately it's generating some errors on our Bugsnag like:
```
java.lang.IndexOutOfBoundsExceptionMainActivity
setSpan (-11 ... -11) starts before 0
```
So, we'll revert it.
=> Revert "[FIX] Autocomplete position on Android"

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/markdown/AtMention.js
Stop looking for `user.name` when mention is `all` or `here`.
Now it always shows `all/here`.
=> [FIX] Here and all mentions shouldn't refer to users

app/utils/log.js
When you change between servers while it's connecting, all pending API requests will be rejected with ABORTED status, so, it sometimes take the error to bugsnag, we don't want this logs, so I'm just ignoring these logs.
=> [FIX] No send data to bugsnag if it's an aborted request

app/lib/methods/getSettings.js, app/views/ScreenLockConfigView.js
We'll set the `autoLockTime` with the value that came from server, just if the setting is enabled.
* If the autoLockTime is disabled at server, and you enabled screenLock at your device, it'll be enabled with the default value of `autoLockTime`, and if you change this, the device should respect the value that you've set.
* if the server enable the autoLock, and you have it enabled before locally at your phone, it should must keep enabled and the autoLockTime should change to the value of the server, and respect this always while it's enabled.
* if the server disable the autoLock, your device should keep this enabled with the autoLockTime as the latest value set by an admin, while you not change this.
* if it's disabled at your phone, and was enabled at the server …
=> [FIX] Screen Lock Time respect local value

e2e/README.md
Simple markdown tweaks driven by linting to improve rendering (and quieten the IDE)
=> Markdown linting for e2e README

app/views/RoomView/List.js
`result` sometimes return an empty array, so the latest item is `undefined`.
=> [FIX] Load messages

app/views/SettingsView/index.js
This PR fixes an error introduced by #2217, when you try to logout the app is crashing.
Test plan:
1. logout
=> [REGRESSION] Logout failing after #2217

app/AppContainer.js, app/containers/InAppNotification/index.js, app/containers/MessageBox/index.js, app/share.js
Check for null before using `navigationRef` and `draftMessage`.
=> [FIX] Handle TypeErrors on navigationRef and draftMessage due to null properties 

android/app/src/main/java/chat/rocket/reactnative/MainActivity.java, app/views/RoomsListView/index.js
Fixes this issue:
> Unable to start activity ComponentInfo{chat.rocket.android/chat.rocket.reactnative.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
It was fixed by https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067
It also fixes a collateral bug where RoomsListView would remain in loading state.
- Enable "Don't keep activities" on Android Developer Options
- Open the app on a server
- Minimize the app (test both normal and back button)
- Restore
- App crashes (or keep in loading state without the RoomsListView changes)
- Enable "Don't keep activities" on Android Developer Options
- …
=> [FIX] Android crashing when restoring from background

app/containers/MessageBox/index.js, app/views/ShareView/Header.js, app/views/ShareView/index.js
1. Send an attachment inner a thread
2. Start a thread with an attachment
=> [FIX] Send thread attachment

app/containers/MessageBox/Recording.js
Audio recording never send the file at Android Devices.
=> [REGRESSION] Audio Recording

app/containers/MessageBox/EmojiKeyboard.js, app/lib/database/index.js, app/lib/rocketchat.js
* Show frequently used emojis at emoji keyboard on Share Extension
* Show custom emojis at emoji keyboard on Share Extension
=> [FIX] Emoji keyboard not showing custom and frequently used emojis on Share Extension

app/views/RoomView/index.js, app/views/RoomsListView/index.js
Prevent access to property of `undefined`.
=> [FIX] Scroll to top crashing when ref is undefined

app/views/AttachmentView.js
`decodeURI` can throw an error while try to decode filename, so, we'll use the original title at these cases.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI
=> [FIX] AttachmentView crashing during title decode

app/containers/MessageBox/index.js
Refer to some error events where we're trying to access `items` of `undefined`.
I can't reproduce the error here, but I guess with this it not will happen again.
=> [FIX] Command previews crashing when API returns an error

app/views/ThreadMessagesView/index.js
* Go to directory
* Open a room that you don't have joined yet
* Open thread messages view
=> [FIX] ThreadMessagesView throwing error when subscription wasn't found

app/presentation/ImageViewer/ImageViewer.android.js
Closes #2227
Create an animated component inner a render generates an infinite loop at render function, and never make the component animatable.
=> [FIX] ImageViewer not recognising gestures after zoomed

app/utils/navigation/animations.js
This is an attempt to fix the following error:
> com.facebook.react.bridge.JSApplicationCausedNativeException: Illegal node ID set as an input for Animated.multiply node
I kept the animation, but I removed a React Navigation's `conditional` call, which makes some other `multiply` calls.
Play with the navigation app on Android.
=> [FIX] Android stack animation throwing illegal node ID

app/views/SidebarView/index.js
It was trying to close a nonexistent drawer on `isMasterDetail` layout.
I removed the functionality, because there's a close modal button for that.
- Open drawer
- Tap user header
- It should close the drawer
- Open drawer (which is a modal on this case)
- Tap user header
- It shouldn't do anything
=> [FIX] Navigation object undefined when tapping sidebar's user header on tablet

android/app/src/debug/AndroidManifest.xml, android/app/src/debug/java/chat/rocket/reactnative/MainDebugApplication.java, android/app/src/debug/java/chat/rocket/reactnative/ReactNativeFlipper.java, android/app/src/main/java/chat/rocket/reactnative/MainApplication.java, android/gradle/wrapper/gradle-wrapper.properties
These changes remove the need for reflection to load Flipper. They also fix the need to hard code the package name, which is not helpful when white labelling the RC App. 
No UI/UX changes and no dev flow changes. Flipper should work how it did previously.
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] Improvement (non-breaking change which improves a current function)
- [ x] I have read the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/CONTRIBUTING.md#contributing-to-rocketchat) doc
- [ x] I have signed the [CLA](https://cla-assistant.io/RocketChat/Rocket.Chat.ReactNative)
- [ x] Lint and unit tests pass locally with my changes
- [x ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x ] I have …
=> [CHORE] Only run Flipper in debug via MainApplication is debug

app/sagas/deepLinking.js
As our app answers to `https://go.rocket.chat` and `rocketchat://`, we have to follow some rules in order to deep link users to the wanted room or server.
There're some cases that this deep link is wrong, incomplete, with an invalid server, etc.
Previous to this PR, we were just stopping the execution of the process, but that would leave the user stuck on the splash screen, if the app was closed.
This PR checks if the app is opened and, if not, calls `appInit()`, making the app to start over.
Closes #1626 
* Call `xcrun simctl openurl booted rocketchat://room\?WHATEVER\=open.rocket.chat`
* The app should `appInit()` again
* Call `xcrun simctl openurl booted rocketchat://room\?WHATEVER\=open.rocket.chat`
* The app just `return`
* Call `xcrun simctl openurl booted …
=> [FIX] App hanging on splash screen when deep link params are wrong

android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java, android/app/src/main/java/chat/rocket/reactnative/LoadNotification.java
Instead of create a new sharedPreferences instance to read user credentials we can use the EJSON class that have the logic to get these values from a notification.
=> [IMPROVEMENT] Use parsed EJSON info on load notification

android/app/src/main/java/chat/rocket/reactnative/MainActivity.java
I've tested and the crashes that are being reported on the latest Android Experimental app are related to a null pointer exception caused when we try to insert `null` into a boolean on a `WritableMap`, it doesn't raise any error when we try to set null for some string, so, we can check null only boolean values.
It should be better if we rewrite these things using kotlin, but for now it's a movement that our planning don't allow to do.
Thanks.
Try to get an older version of this app without MMKV. `(4.10-)`
Add a sort preference but keep `showUnread` `null`.
Update to the latest experimental app using MMKV.
=> [FIX] SharedPreferences data migration

app/i18n/locales/en.js, app/i18n/locales/pt-BR.js, app/views/RoomsListView/index.js
Always group Omnichannel chats on top
=> [IMPROVEMENT] Show "Chats in Progress" group

app/views/RoomView/Header/Header.js, e2e/tests/room/01-createroom.spec.js, e2e/tests/room/02-room.spec.js, e2e/tests/room/03-roomactions.spec.js
Fixed a couple of wrong or flaky tests
=> [FIX] Detox tests

app/stacks/OutsideStack.js
/workspace/Rocket.Chat.ReactNative/app/stacks/OutsideStack.js
24:26  error  'root' is defined but never used  no-unused-vars
=> fix: error  'root' is defined but never used  no-unused-vars

app/containers/MessageBox/index.js, app/lib/database/utils.js, app/lib/database/utils.test.js, app/lib/rocketchat.js, app/views/NewServerView/index.js, app/views/SearchMessagesView/index.js, app/views/ShareListView/index.js, package.json, yarn.lock
Queries using LIKE clause with user input aren't safe by default, so we need to sanitize them first.
WatermelonDB default sanitizer works for latin alphabet only.
This PR adds support for other alphabets.
Closes #2158 
Related to https://github.com/Nozbe/WatermelonDB/issues/734
=> [FIX] Local database searches using non-latin characters

app/views/ReadReceiptView/index.js, app/views/ReadReceiptView/styles.js
In some cases, `message.user.username` is null.
This PR won't print that item.
=> [FIX] Read receipt crashing in some cases

app/constants/settings.js, app/views/AttachmentView.js
Some server's content have confidential data that shouldn't be saved on device's gallery/storage.
This PR adds a way to disable it (the top right download button on AttachmentView)
Server PR: https://github.com/RocketChat/Rocket.Chat/pull/18875
=> [IMPROVEMENT] Add "Allow_Save_Media_to_Gallery" setting

app/lib/database/utils.js, app/lib/database/utils.test.js
- Login and logout from any server just to populate servers history
- Focus on NewServerView's input
- Nothing happens, because it trigger an error
=> [FIX] SanitizeLikeString util crashes for empty strings

patches/@nozbe+watermelondb+0.19.0.patch
Fix a bug of watermelon where dates are read as String instead of a Date instance.
- Open any room
- Reload messages
- All messages have a header
https://github.com/Nozbe/WatermelonDB/pull/828
=> [FIX] WatermelonDB caching Date as String

CONTRIBUTING.md
Information about the Reactotron tool was missing in the contribution file.
=> [DOCS] Add Reactotron

app/containers/Header/index.js, app/views/RoomView/index.js, app/views/RoomsListView/index.js, app/views/ThreadMessagesView/index.js
Adds `numIconsRight` to `getHeaderTitlePosition` and multiply it by 45 (approximated space of a header icon).
- Change RoomsListView server to make it break the layout and it should be ok
- Change RoomView title to make it break the layout and it should be ok
- Change ThreadMessagesView background color for searching to make it show the spacing and it should be ok (I left 1 icon as space just to feel better)
=> [FIX] Header title positioning not changing according to the number of icons

app/lib/methods/subscriptions/rooms.js
Sometimes notification event doesn't have a message with a type on it payload, so we need to check before compare, using an optional chaining.
=> [FIX] Notification stream throwing an error when there isn't a message on payload

app/containers/message/Thread.js, app/containers/message/index.js, app/views/RoomView/Header/Header.js, app/views/RoomView/List.js, app/views/RoomView/index.js, app/views/RoomsListView/index.js, storybook/stories/index.js
- Fixed parent title on thread header breaking lines
- When unread on top is set, channels wouldn't leave unread group in some cases
- Fixed thread badge color not being updated on the message's thread button
Closes #2519 
- Create a thread on a room with a long name (or a discussion from a long message)
- Subtitle shouldn't break lines
- Enable `Unread on top`
- Mark a channel as unread
- Mark it as read
- Channel should leave `Unread` group
- Focus a room with a thread you're following
- Send a message from a different user on a thread you're following
- Thread badge color should update
- Enter in the thread
- When you leave it, the badge color should update
=> [FIX] Threads not being updated and other related issues

app/views/RoomView/Header/Header.js, app/views/RoomView/index.js
- Adds hit slop on the header
- Uses 1 icon padding on threads header
Long thread names should use a larger space on the header title
=> [FIX] Minor room header issues

android/app/build.gradle, app/views/UserPreferencesView/index.js
The string "Notifications" is double translated, giving the strange output seen in issue #2625 when the language is set to non-English
The second file is the fix for #2614 
#2625 and #2614 which Github added to my existing PR instead of creating a second one ... see annotations beyond. Sorry, I'm a Github noob ;-)
See #2625 
This is my first PR on Github ... I also saw that #2614 was still unfixed in 4.12.0, so I've added that as well in a second step. I thought it would open a second PR, instead it added this change to the existing one. Sorry, I have no idea how to tell Github to make 2 PR's out of it, but I wanted to be sure that the fix for #2614 finds its way into future versions.
=> [FIX] Whitelabel unable to find package name

app/lib/methods/helpers/mergeSubscriptionsRooms.js, app/presentation/RoomItem/RoomItem.js, app/presentation/RoomItem/UpdatedAt.js, app/presentation/RoomItem/index.js, storybook/stories/RoomItem.js
Currently, messages inside threads aren't being considered for chats order.
This PR makes this rule: `chatDate = max(room._updatedAt, subscription.lastMessage.ts)`
- Sort by activity
- Send a message on a thread to a older chat (without sending it to the main channel)
- App should send it to the top of RoomsListView
=> [FIX] Chats order

.circleci/config.yml, ios/fastlane/Fastfile
Renames "release" lane to "build_experimental"
=> [CHORE] Rename Experimental iOS lane

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/markdown/index.js, app/containers/message/RepliedThread.js, storybook/stories/Markdown.js
Removes sequential empty spaces from Markdown preview.
Closes #2434 
Send a message with lots of sequential empty spaces and make it render as Markdown preview.
=> [FIX] App freezing if Markdown preview contains sequential empty spaces

app/views/AttachmentView.js, ios/Podfile.lock, ios/Pods/Local Podspecs/react-native-cameraroll.podspec.json, ios/Pods/Manifest.lock, package.json, yarn.lock
Closes #2741 
- Go to AttachmentView on iOS
- Tap save button
- Error is raised
=> [FIX] Unable to save attachment on iOS

android/app/src/main/java/chat/rocket/reactnative/MainActivity.java, app/lib/encryption/constants.js, app/lib/userPreferences.js, app/sagas/login.js, ios/RocketChatRN/AppDelegate.m
=> [CHORE] Remove some migrations

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/chat/rocket/reactnative/MainActivity.java, app/AppContainer.js, app/actions/app.js, app/views/OnboardingView/index.js, app/views/RoomsListView/index.js
When app is on root stack screen, hardware back button kills current activity and minimizes the app, but it should behave just like hardware home button, which just moves it to background leaving the app state as it is.
https://user-images.githubusercontent.com/804994/104757999-8373f100-573c-11eb-8a35-a3d72d7cc8c7.mp4
https://user-images.githubusercontent.com/804994/104757992-81119700-573c-11eb-8585-446ed5bee587.mp4
=> [FIX] Back button closing activity when on root stack screen

app/containers/MessageBox/ReplyPreview.js
Added Use real name check for reply preview used for quotes and thread replies
fixes #2907
=> [FIX] Real name setting ignored on reply preview

app/constants/colors.js, app/containers/ActionSheet/ActionSheet.js, app/containers/ReactionsModal.js, app/containers/UIKit/MultiSelect/index.js, app/containers/UIKit/MultiSelect/styles.js, app/stacks/InsideStack.js, app/views/DirectoryView/Options.js, app/views/RoomView/ReactionPicker.js, app/views/RoomView/index.js, app/views/RoomsListView/ServerDropdown.js, app/views/RoomsListView/SortDropdown/index.js, app/views/ThreadMessagesView/Dropdown/index.js
In order to keep UI more consistent, we should make backdrop opacity based on themes. The idea here is to make elements to stand out based on the theme we're currently on.
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [CHORE] BackdropOpacity based on themes

package.json, patches/react-native-webview+10.3.2.patch, yarn.lock
If a certificate auth challenge is requested on Android the webview will hang if no certificate is loaded. To prevent this, fallback to default Android behavior and cancel the challenge with request.cancel().  This is the same behavior on iOS, https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebView.m#L818.
#2917 
Co-authored-by: Jan Garaj <jan.garaj@gmail.com>
=> [FIX] Webview not falling back to default auth challenge when no cert is provided

app/lib/methods/getCustomEmojis.js, app/lib/methods/getPermissions.js, app/lib/methods/getRoles.js, app/lib/methods/getSlashCommands.js, app/lib/methods/getUsersPresence.js, app/lib/methods/loadThreadMessages.js, app/views/ThreadMessagesView/index.js
We use InteractionManager.runAfterInteractions on some places to keep the bridge calls and JS thread free, but that also breaks try/catch behavior. When there's an issue inside the block, catch doesn't work.
=> [CHORE] Remove InteractionManager blocks

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/message/utils.js, app/i18n/locales/en.js, app/i18n/locales/pt-BR.js, storybook/stories/Message.js
Add more condition to render e2e text in message view if is toggle to on or off
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] System message of e2e encryption missing

.circleci/config.yml
We always start the os-build-experimental and android-build-experimental every time we push some code, it make spent more cost. So we need to add type:approval to make the task can be hold
=> [CHORE] Add hold step for ios and android build experimental

e2e/tests/room/02-room.spec.js
For now we don't have e2e testing for draft message, so we decide to adding it.
=> [TESTS] Add E2E tests to draft message

app/views/DirectoryView/index.js, e2e/tests/assorted/09-joinfromdirectory.spec.js
For now we don't have e2e testing for Directory, so we decide to adding it.
=> [TESTS] Add E2E tests to directory

app/views/TeamChannelsView.js
- Query for a non-existing channel
- Cancel query
- List is in infinite loop
=> [FIX] Team's channel search not working properly

.circleci/config.yml, android/fastlane/Fastfile
=> [CHORE] Add job to upload Experimental to Google Play production

app/i18n/index.js
Closes #3069
- Set up a non-supported language to your user from web client (like Esperanto)
- Try to login or resume the app
=> [REGRESSION] Fallback language stopped working

app/i18n/index.js, app/i18n/locales/nl.json, e2e/tests/assorted/04-setting.spec.js, e2e/tests/assorted/12-i18n.spec.js
Adds `en` language by default to `i18n` object.
Added e2e tests to make sure we don't have such regressions anymore.
Closes #3087
=> [REGRESSION] Fallback not working when device's language is available

android/app/src/main/AndroidManifest.xml
This should fix the Issue described in #3136
In order while researching the problem from #3136 I found out that the launch mode on master was set different. Setting the launch mode to `singleTask` as on master, everything works like expected
Tested on Android 11 Pixel 4 and Samsung Galaxy A52
1. create a Apk from this branch
2. Install it
3. login as a user A
4. check that notifications are working
5. move Rocket chat into background
6. send a message from an other user B
7. open rocket chat with clicking on the notification
8. send a message: Sending runs smooth withour error
9. Sending messages from other channels also works
=> Fix single-server sending messeages when calling app back via notifications

app/views/RoomActionsView/index.js
That don't show the `Block user` button inside the Group DM's actions
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3111
- Create a Group DM
- Go to Group DM's actions
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
Closes #3111
=> [FIX] Don't show Block Button inside Group DM Actions

.circleci/config.yml, android/fastlane/Fastfile, android/fastlane/README.md
- Removes additional approval job on iOS Experimental, making it to land to TestFlight automatically after `ios-hold-build-experimental` is approved
- Adds a new job to upload to Internal App Sharing
- From now on, when `ios-hold-build-experimental` and `android-hold-build-experimental` are approved, CI builds and uploads versions to TestFlight and Internal App Sharing
Before:
After:
=> Chore: Improve QA workflow

app/sagas/init.js
Fix a white screen when open the app.
Closes #3302 	
Using the single-server branch, just open the app
[BEFORE]
[AFTER]
N/A
=> [FIX] White screen on start on single-server

e2e/helpers/data_setup.js, e2e/tests/assorted/01-e2eencryption.spec.js
Just fixing two wrong merged file.
N/A
N/A
N/A
=> [FIX] Merge mistake on single-server

yarn.lock
We pointed `@rocketchat/sdk` to the latest commit on #3279, but it'd not fetch the correct version automatically.
As that's not enough, we bumped it to 1.1.0.
https://app.clickup.com/t/de44ww
- Checkout this branch
- `yarn`
- `yarn lint`
- No issues
Prior to this, `yarn lint` would result in Typescript errors on the SDK.
=> Fix: @rocketchat/sdk not fetching correct commit

app/containers/MessageBox/RecordAudio.tsx, app/containers/MessageBox/styles.ts
When an event interrupts an ongoing voice recording in IOS, the OS stops the recording. This was not handled properly before: The message was immediately completely lost and it was not possible to make a new voice message before force-quitting and restarting the app (because the Expo recorder was left in loaded state).
This PR stops the recording in this case, indicating it was stopped. The user can send or discard the voice message up to that point at any time afterwards.
I also changed the GUI to make it more clear. See below.
#3002 
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3388
- Start a voice message recording
- while the recording is running, call the device or activate Siri.
- App should stop the recording, but give you a way to send the message
- Same steps, but …
=> [FIX] Preserve voice message if recording is interrupted

app/containers/MessageBox/index.tsx, app/views/CannedResponsesListView/index.js
This PR fixes when using canned responses on tablets and remove the refresh control on the canned responses list
- The fix to tablets/ipads:
- You as agent, takes a chat from omnichannel's queue
- Goes to Canned Responses List and click on button `USE`
- You should be redirected to Room view and the message will be written on the message input
- The same needs to happening when you click the USE on Canned Response Detail view
- The other fix is to remove the refresh control (that action that the user can pull the scroll, and refresh the page) in the Canned Response List
=> [FIX] Canned Responses minor fixes

app/lib/rocketchat.js, app/views/RoomMembersView/index.js
This PR is to fix a TypeError when is fetching members on Room Members View. Because we need to evaluate which version of the server the user is, although if the server is greater or equal than 3.16.0 the result is by property members if is low the property is by records.
- You'll need to access 2 different server versions: 1 with version >=3.16.0, and one below.
- Go to a channel/team/group dm or discussion and check the members that are inside the room.
- Members should be listed correctly
=> [FIX] Fetch members on RoomMembersView

app/views/SelectListView.tsx
Migrate SelectListView to Typescript
- Create a team and a channel
- Open the team room, go to `Channels View`, the `#`icon near the title, then click on `edit` icon, next to search icon
- The view `AddChannelToTeam` will show and click on `Add Existing`
- Here is the view migrated. So you must see the channel that you created before. Test the search too.
=> Chore: Migrate SelectListView to Typescript

app/views/SelectServerView.tsx
Migrate SelectServerView to Typescript
- To test this, you must be logged into two servers
- Then, share a file or text, and the Share App will open and you should see a section written as `Select server`
- Click on the server, and you will be moved to the view migrated.
-
=> Chore: Migrate SelectServerView to Typescript

app/presentation/KeyboardView.tsx, app/views/SetUsernameView.tsx
Migrate SetUsernameView to Typescript
- Create a new account with the username as `test+username`, you need to write the username with `+`
- Then, after validating your email, do the login, you should be moved to another screen with the title `Username` and button `Register`. This is the view migrated
=> Chore: Migrate SetUsernameView to Typescript

app/views/ThemeView.tsx
Migrate ThemeView to Typescript
- Go to Settings, then click on Theme
- This is the view migrated
=> Chore: Migrate ThemeView to Typescript

app/containers/Status/Status.tsx, app/views/StatusView.tsx
Migrate StatusView to Typescript
- When logged in, click on the `hamburger menu`
- Then on the sidebar click on `Edit Status`, you should be moved to Status View, the view migrated.
=> Chore: Migrate StatusView to Typescript

app/views/AttachmentView.tsx
Download properly any video that has a video type as `video/quicktime`, that could be `.mov` or `.qt`.
On iOS when we were testing the extension, the result was `.qt` for `.mov` and `.qt` video. However, when tried to save in the iOS gallery, the format `.qt` wasn't recognized by iOS and throw an exception. Because of this was showing an Error in Alert.
- On any Room, upload a `.MOV` file and try downloading it.
https://user-images.githubusercontent.com/47038980/147830377-0d00a8ce-ba6b-46b4-9177-fd87ddb0dc6a.mov
=> [FIX] Download video/quicktime in iOS

app/commands.ts
Migrate lib/commands to typescript
Test input via keyboard for app control
=> Chore: Migrate app/commands to typescript

app/commands.ts, app/containers/List/ListItem.tsx, app/definitions/ISubscription.ts, app/lib/methods/getUsersPresence.ts, app/stacks/types.ts, app/utils/debounce.ts, app/utils/events.ts, app/utils/goRoom.ts, app/views/RoomsListView/Header/Header.tsx, app/views/RoomsListView/Header/index.tsx, app/views/RoomsListView/ListHeader/index.tsx, app/views/RoomsListView/ServerDropdown.tsx, app/views/RoomsListView/index.tsx, app/views/RoomsListView/styles.ts
Migrate methods/RoomListView to typescript
N/A
On App: 
* Check the list of chats; 
* Check the search rooms;
* Enter some chat and check if:
* Check if the headers still works fine;
* Change the theme app, and verify if the chats list still works fine;
N/A
N/A
=> Chore: Migrate views/RoomListView to typescript

app/definitions/rest/v1/channels.ts, app/definitions/rest/v1/groups.ts, app/definitions/rest/v1/im.ts, app/lib/rocketchat/services/restApi.ts, app/views/RoomMembersView/index.tsx
=> Chore: Migrate REST API - removeUserFromRoom to Typescript

app/definitions/rest/v1/chat.ts, app/lib/rocketchat/services/restApi.ts
=> Chore: Migrate REST API - ignoreUser to Typescript

app/definitions/rest/v1/channels.ts, app/lib/rocketchat/services/restApi.ts
=> Chore: Migrate REST API - toggleRoomOwner to Typescript

app/containers/MessageBox/index.tsx, app/definitions/rest/v1/omnichannel.ts, app/lib/rocketchat/services/restApi.ts
Migrate REST API - getListCannedResponse to Typescript
- Take an omnichannel's room
- Go to Canned responses and should work properly
=> Chore: Migrate REST API - getListCannedResponse to Typescript

app/definitions/rest/v1/omnichannel.ts, app/views/LivechatEditView.tsx
Migrate REST API - getCustomFields to Typescript
- Login in `candidate.rocket.chat`
- Take an omnichannel's room
- Go to `RoomInforEditView` and should appear a `custom-field` title
=> Chore: Migrate REST API - getCustomFields to Typescript

app/definitions/IRoom.ts, app/definitions/IUser.ts, app/definitions/rest/v1/rooms.ts, app/lib/rocketchat/services/restApi.ts, app/views/NotificationPreferencesView/index.tsx
Migrate REST API - saveNotificationSettings to Typescript
On a chat, open the actions and go to notifications;
=> Chore: Migrate REST API - saveNotificationSettings to Typescript

app/definitions/IMessage.ts, app/definitions/rest/v1/chat.ts, app/lib/rocketchat/services/restApi.ts, app/views/SearchMessagesView/index.tsx
Migrate REST API - searchMessages to Typescript
Open an chat and search for a message.
=> Chore: Migrate REST API - searchMessages to Typescript

app/definitions/IAttachment.ts, app/definitions/rest/v1/channels.ts, app/definitions/rest/v1/groups.ts, app/definitions/rest/v1/im.ts, app/lib/rocketchat/services/restApi.ts, app/views/MessagesView/index.tsx
Migrate REST API - getFiles to Typescript
Test the files view on:
* directly message room;
* channels room;
* thread room;
=> Chore: Migrate REST API - getFiles to Typescript

app/sagas/rooms.js
When a subscription is removed from the server via another client, when the
mobile app is relaunched the subscriptions were not being removed properly.
Changed the logic to use the subscriptionResult.remove array from the server
and the _id property to fix.
TEMP only to test https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3757
- General room fetch/sync should work
- Create a room
- Open the app to make sure it's saved on app's local database
- Close the app
- Delete the room on web
- Open the app and it be removed from app
- Create a room
- Open the app to make sure it's saved on app's local database
- Close the app
- Leave room on web
- Open the app and it be removed from app
- I think there was a similar use case not working on Omnichannel and this PR might fix it
=> [TEMP] Leave room request not removing the subscription from the app

app/definitions/ILivechatEditView.ts, app/lib/rocketchat/services/restApi.ts, app/views/LivechatEditView.tsx
Migrate REST API - editLivechat to Typescript
- Take an omnichannel's room and edit his infos
=> Chore: Migrate REST API - editLivechat to Typescript

app/containers/MessageBox/index.tsx, app/definitions/rest/v1/commands.ts, app/definitions/rest/v1/index.ts, app/lib/rocketchat/services/restApi.ts
Migrate REST API - runSlashCommand to Typescript
=> Chore: Migrate REST API - runSlashCommand to Typescript

app/definitions/rest/v1/chat.ts, app/lib/rocketchat/services/restApi.ts
Migrate REST API - getSyncThreadsList to Typescript
=> Chore: Migrate REST API - getSyncThreadsList to Typescript

app/definitions/rest/v1/chat.ts, app/lib/rocketchat/services/restApi.ts, app/views/ThreadMessagesView/index.tsx
Migrate REST API - getThreadsList to Typescript
=> Chore: Migrate REST API - getThreadsList to Typescript

app/lib/methods/getUsersPresence.ts
`getUserPresence`  has a [timer](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/getUsersPresence.ts#L112) to [group](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/getUsersPresence.ts#L35) an amount of users and call `GET /users.presence` in [one request.](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/getUsersPresence.ts#L57)
This grouping logic is broken, because we're cleaning the list before [actually dispatching](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/getUsersPresence.ts#L78) the result to Redux.
The impact of this is fetching user statuses, but not dispatching them to Redux.
- Make sure you have a few _not offline_ DMs at the top of …
=> [FIX] Not properly fetching users presence on some startup situations

app/views/MessagesView/index.tsx
In this PR #4113, I introduced a bug that made it impossible to load starred, mentions, pinned and files messages. 
The proposal of this PR is fix this bug.
In a room, go to actions and load the files, mentions, starred and pinned messages. Please verify if we can do and undo the actions. 
E.g: 
* star a message, go to actions -> starred messages -> unstar that message. 
* pinned a message, go to actions -> pinned messages -> unpin that message.
=> Regression: Fix problem to load starred, mentions, pinned and files messages

app/views/RoomInfoEditView/index.tsx
Reverts RocketChat/Rocket.Chat.ReactNative#4220
Reverting since it's causing a few visual glitches, which is worse than fixing only very edge case.
=> Revert "[FIX] Form re-rendering on RoomInfoEditView when app receives newer data from stream"

app/containers/ActionSheet/ActionSheetContentWithInputAndSubmit/index.tsx, app/views/ProfileView/components/DeleteAccountActionSheetContent/index.tsx
Add showInput prop to add the option to show actionSheetContent without input
- Try to delete an account with created rooms
=> Regression: Add showInput prop to add the option to show actionSheetContent without input

app/sagas/login.js, app/sagas/selectServer.js
Changes the logic to only set the chosen server if the login is successful.
Since it is not necessary to set the server and I have not even completed the login.
Note: If it is necessary to keep the server even not logging into it, the right thing would be to create a key, something like a temp key, different from the main key that indicates the logged server.
Closes #4291
I left the old PR just for history and in case you want to compare.
1 - Start the process of logging in to a server by choosing one, but do not log in to any user account.
a - If this step is not done correctly, at step 4, the user will probably see the screen stating there is no server logged in.
2 - Minimize app
3 - Open Share Extension (by sharing something from the device's gallery)
4 - Try choosing a server to share …
=> [FIX] Share Extension shows a server that has no user logged in

e2e/tests/assorted/11-deeplinking.spec.js, ios/RocketChatRN/AppDelegate.mm
Introduced on #4316 
- Tapping on a notification with the app open in background should redirect to the room
- On iOS `e2e/tests/assorted/11-deeplinking.spec.js` should be passing
- On Android I couldn't make Detox work on my machine, so I tested with 
```
adb shell am start -W -a android.intent.action.VIEW -d "https://go.rocket.chat/room\?host\=open.rocket.chat\&path\=channel/general"
```
=> Regression: Resume the app with a deep link not navigating

app/lib/services/connect.ts, app/sagas/selectServer.js, e2e/helpers/app.js, e2e/tests/onboarding/05-login.spec.js
We were calling `abort` on `selectServer` saga without need.
The [app doesn't disconnect](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/services/connect.ts#L45) if it's reconnecting to the same server, but it would abort upcoming requests anyway.
Calling `abort` invalidates `this.controller` from `@rocket.chat/sdk` https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/mobile/lib/api/api.ts#L260
I wrote a regression test to make sure it doesn't happen again.
Depends on #4428 
- Tap join open
- Go back
- Tap join open again
- From now on, any request happening through `@rocket.chat/sdk` is going to be aborted
=> [FIX] Requests being skipped after reconnecting on onboarding

ios/Podfile.lock, package.json, yarn.lock
Updates Expo SDK to 46.
I didn't touch the Expo modules on this PR.
I've tested all expo modules on iOS and Android.
=> Chore: Upgrade Expo to SDK 46

app/views/RoomView/List/List.tsx, app/views/RoomView/List/RefreshControl.tsx, app/views/RoomView/List/index.tsx, app/views/RoomView/index.tsx
Related to https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3260
I was not able to use the exact same workaround after RN update, so I created a different one using RefreshControl.
- Both iOS and Android messages list should work properly (pay attention to messages order)
- Android should be a lot faster than on 4.30
- Use the support chanel on open to measure performance, in others channels the performance is "acceptable".
"Profile HWUI rendering" > "On screen as bars" on Samsung S10e
https://user-images.githubusercontent.com/804994/190730700-69cf8143-9e37-4ff8-ab2c-d2da3770e087.mp4
https://user-images.githubusercontent.com/804994/190730645-11d307d2-e2e1-4359-9171-63407c53fa6c.mp4
=> Regression: Poor performance in messages list on Android

android/app/src/play/java/chat/rocket/reactnative/CustomPushNotification.java
https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
- Push notifications should be received properly
- Reply and dismiss notifications should work
=> Regression: Push notifications not working after update to Android 12

app/containers/message/Attachments.tsx, app/containers/message/Audio.tsx, app/containers/message/Reply.tsx, app/containers/message/interfaces.ts, app/lib/methods/audioFile.ts
- Adds support to servers with (forbidden printable ASCII characters) - example `server.url:3000` (the colon)
- Adds support to files with (forbidden printable ASCII characters) - example `Audi:o.mp3` `😀audio.mp3` (the colon and emoji)
- Fix the download of files with same name.
Closes #4548, #4534
Try to download an audio file with a server terminating with colon - example `localhost:3000`
Send various audios with the same name - example record multilple audios on web
=> [FIX] Fix filenames and servers url when downloading audio files

e2e/tests/assorted/11-deeplinking.spec.ts, ios/RocketChatRN/AppDelegate.h, ios/RocketChatRN/AppDelegate.mm, package.json, patches/react-native-notifications+4.2.4.patch, yarn.lock
We migrate AppDelegate to Objective-C++ on #4316, which is documented here https://reactnative.dev/docs/next/new-architecture-app-intro#ios---use-objective-c-mm-extension
However, we used import the swift bridging header on AppDelegate and we removed it by mistake.
Since there is no compatibility between Swift and Objective-C++, we had to patch react-native-notifications and do a workaround on Expo to stop importing using the Swift way (`@import module`) and make it import using obj-c way (`<module/module.h>`).
References:
- https://github.com/facebook/react-native/issues/33692#issuecomment-1192597753
- https://github.com/expo/expo/issues/17705#issuecomment-1196251146
We worked on a fix on #4428, but that fixed only deep link with URL and not with a push notification tap.
In order to fix …
=> [FIX] Reply and deep link from push notifications not working on iOS

app/lib/methods/search.ts
This regression was introduced [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4546/files#diff-40cfd2a3b11d20726a6668af6ef2c8c9216ef533bfe5bd5ad80744e42dbd8d5eR39-R41). Unfortunately, during this PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4546 I added 3 params that weren't needed or was incorrect as the `search: true`.
- Try to mention a channel that you already joined before
- Create a dm with someone, then back to create a channel and select the previous person that you started to sent a dm
=> Regression: Local search is returning wrong object

app/dimensions.tsx
We’ve been using our own Dimensions context on the root of the app.
Instead, we need to migrate to RN’s useWindowDimensions moving the whole logic to a self contained hook and decreasing complexity on app/index and app/share.
It’s going to take some time until we can finish this, because some components aren’t using hooks yet and they rely on our current logic, so let’s start using useWindowDimensions in baby steps.
On this PR, we're deprecating everything related to the current implementation.
[NATIVE-117]
[NATIVE-117]: https://rocketchat.atlassian.net/browse/NATIVE-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: Deprecate Dimensions

ios/Podfile.lock, package.json, patches/react-native-notifications+4.3.2.patch, yarn.lock
Applied https://github.com/wix/react-native-notifications/pull/908 and tested isReactInitialized as well.
Is there any way to call `mAppLifecycleFacade` directly?
Closes #4606
- Receive a push notification (try it both with the app in background and killed)
- Tap on it and the app should redirect to it
- Go to another room and try to send a message
- (fail) On Android, the app is going to trigger the deep link again and behave like you tapped the push notification again
- Everything related to push notification (ping me if you need help thinking on possible test cases)
- Previously, receiving a push and trying to share an image would also trigger the deep link
[NATIVE-135]
[NATIVE-135]: https://rocketchat.atlassian.net/browse/NATIVE-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> [FIX] Push notification's deep linking not working when opened from a cold state on Android

ios/Podfile.lock, package.json, patches/react-native-mmkv-storage+0.8.0.patch, yarn.lock
Bumps react-native-mmkv-storage and possibly fixes #4431, because it lands this fix https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/263
- Update app should keep the user logged in
- Share media from other apps to Rocket.Chat
- Reply from push notification
- Secured Push Notification (fetch content push)
- Decrypt push notification
- Enable E2E encryption and receive push notifications
[NATIVE-164]
[NATIVE-164]: https://rocketchat.atlassian.net/browse/NATIVE-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: Update react-native-mmkv-storage to 0.8.0

app/views/RoomView/index.tsx
This issue was found the first time when the user opened the announcement and the announcement's text is a link. Then the user pressed the link and should open the web browser outside of the app. This behavior was forcing the app to go to the background, then when the user resume the app again and tried to close the modal, the app was freezing.
During some tests, I noticed that is only happening on iOS and we still need to keep the `list.query` to resolve this bug that still occurs on Android https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1410
You need to test properly for iOS and Android
1 - For both, open the announcement inside any Room
2 - Then, minimize the app or if the announcement is a link, click on it
3 - After the app goes to background, resume it again
4 - You …
=> [FIX] Modal freezing app after return from the background

app/actions/actionsTypes.ts, app/actions/room.ts, app/containers/message/index.tsx, app/definitions/index.ts, app/lib/methods/getMoreMessages.ts, app/lib/methods/index.ts, app/lib/methods/loadNextMessages.ts, app/lib/methods/loadSurroundingMessages.ts, app/reducers/room.test.ts, app/reducers/room.ts, app/sagas/room.js, app/sagas/rooms.js, app/views/RoomView/LoadMore/LoadMore.stories.tsx, app/views/RoomView/LoadMore/index.tsx, app/views/RoomView/index.tsx, app/views/RoomView/services/getMessages.ts, app/views/RoomView/services/index.ts
Fixes a use case where the app would fail to persist data on local db without adding a new loader item ("load more").
It could be reproduced by scrolling through messages history while receiving multiple messages on the same room.
That would make `LoadMore` component to mount -> unmount -> mount, which would call `useEffect` twice and create a race condition during load.
I fixed by adding the load logic inside a saga channel (queue), since we don't have a better option to deal with message loading atm.
`LoadMore` dispatches the redux action to the saga queue, which calls them in sequence.
If the same loader was called more than once, it's ignored.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4793
- Go to a room with enough messages to trigger pagination
- Receive …
=> [FIX] Messages not loading on some edge cases

app/views/RoomView/index.tsx
There is a bug in the component provided by the library where it fails to determine its height when there are multiple snap points. For instance, with the array ['50%, '80%'], the component interpreted that the height of the scroll was 80% of the device's height, causing a part of the scroll to be hidden during the first 50%. On iOS, this resulted in bouncing to the end of the scroll, revealing more users to list, while on Android, this bounce did not occur, making it appear as if the scroll was at the end.
- Go to a channel and search for a message with more than 8 user's reactions with the same reactions
- Do a long press on the reactions
- The reaction's list should appear and you should be able to see all the users that reacted with that emoji …
=> fix: change reactions list scroll to use a single snap point

app/lib/constants/defaultSettings.ts, app/lib/methods/getSettings.ts, app/views/CreateChannelView/RoomSettings/index.tsx, app/views/CreateChannelView/index.tsx, app/views/RoomsListView/Header/Header.tsx
Properly set new room to be encrypted according to server settings
Closes: #5175 
Resolve: #5189
1. Go to server workspace administration
2. Go to settings
3. Go to "E2E Encryption"
4. Enable "E2E Encryption" and "Enable encryption for Private Rooms by default"
5. Save changes
6. Open app in mobile
7. Create a new room
8. Skip adding participants
9. In the next screen you will see room creation parameters, with the encryption flag turned off
=> fix: properly set new room to be encrypted according to server settings

app/views/DirectoryView/index.tsx
After changing search type, we need to again click on search by or outside of DropDown to close the Dropdown. So instead we can automatically close dropdown after selecting search type
Fixes #5449 
1. Go to Directory
2. Open DropDown
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/65113071/fcd9743d-1261-42b7-9287-25ac65e9eb13
=> feat: close OptionsDropdown after changing search  type

android/app/build.gradle, ios/Podfile.lock, ios/RocketChatRN.xcodeproj/project.pbxproj, package.json, yarn.lock
related: https://github.com/software-mansion/react-native-screens/pull/1969
https://open.rocket.chat/group/native-clients-internal?msg=zK5yqWpnR2mttXxqD
https://app.bugsnag.com/rocket-dot-chat-1/experimental/errors/65a952292d11af000863f8a0?filters[error.status]=open&filters[event.since]=30d
Jira: [NATIVE-453]
[NATIVE-453]: https://rocketchat.atlassian.net/browse/NATIVE-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update react-native-screens from 3.13.1 to 3.29.0

app/lib/services/connect.ts
This pull request adds a check to ensure that the `_id` being processed in the `public-settings-changed` event is present in the `defaultSettings` object before updating the settings. This helps prevent errors when the `_id` is not part of the default settings.
Fix #4805 : Error when non-support setting change is received via stream
=> fix: Error when non-support setting change is received via stream

app/lib/methods/getCustomEmojis.ts, app/lib/methods/getSlashCommands.ts, app/sagas/login.js
Fixes:
- Two floating promises that would keep loginSuccess saga hanging
- Redux-Saga's fork used instead of put
As far as I could tell, there was no visible bug.
`takeLatest` would cancel the `loginSuccess` running anyway, while the fork was declared at the top of the saga, so there was enough time to dispatch their own saga.
- Open simulator with Reactotron connected
- Do a login
- See how `LOGIN_SUCCESS` saga would never finish (fixed on this PR)
[CORE-91]
[CORE-91]: https://rocketchat.atlassian.net/browse/CORE-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: floating promises and fork usage on login saga

app/views/CannedResponsesListView/Dropdown/index.tsx, app/views/DirectoryView/Options.tsx, app/views/DirectoryView/index.tsx, app/views/RoomsListView/ServerDropdown.tsx, app/views/RoomsListView/index.tsx, app/views/ThreadMessagesView/Dropdown/index.tsx, app/views/ThreadMessagesView/index.tsx
The React team recommends replacing class-based components with functional components. This PR migrates several of them.
=> chore: migrate several class-based components to functional components

app/views/SidebarView/index.tsx
`allowUserStatusMessageChange` can be `true`, `false` or `undefined`
We should only disable status change if it is explicitly `false`.
Enable or disable the setting and see if the status change menu is visible or not.
Also check on a server that has not changed this setting (which must have the value of `undefined`), to see if the option exists or not.
Jira: [SUP-536]
[SUP-536]: https://rocketchat.atlassian.net/browse/SUP-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: explicitly check the type of `Accounts_AllowUserStatusMessageChange`

package.json, yarn.lock
Fix error on installing node modules in windows systems based on https://github.com/bugsnag/bugsnag-cli/issues/93
There was an issue while installing node modules in windows systems that was related to Bugsnag Cli package. This issue was fixed already in bugsnag in version 2.2.0 in [this pr](https://github.com/bugsnag/bugsnag-cli/issues/93)
Use a Windows system with x64 architecture and run `yarn`
=> Platform with type "Windows_NT" and architecture "x64" is not supported by @bugsnag/cli.

app/lib/methods/helpers/formatAttachmentUrl.ts
In some cases, the URL returned by `formatAttachmentUrl` wouldn't consider local files and the code would get to this line https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/79134296bc3a3d44fbab42574794f99162e5a902/app/lib/methods/helpers/formatAttachmentUrl.ts#L32
The result would be an invalid URL like `${server}${localFile}` -> `https://open.rocket.chatfile://var/mobile...`
I was not able to reproduce the issue, but since the code on this function is fairly straightforward and the only condition that should consider local files was based on a specific local directory (`FileSystem.documentDirectory`), I've decided to relax this rule a little bit by just checking `file://`.
[NATIVE-655]
[NATIVE-655]: https://rocketchat.atlassian.net/browse/NATIVE-655?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> fix: Make file format attachment less rigid

app/views/Styles.ts
Android was not Mobile app not showing entire message in the Inter-Regular font.
https://rocketchat.atlassian.net/browse/NATIVE-657
- Select a room;
- Send the message : 'Perfect, I will let them know. Thank you. Also happy to look at the FlieVlaut stuff with you.'
- Send the message: 'テスト'
[untitled.webm](https://github.com/user-attachments/assets/dd0781d8-3878-46a1-a1c5-ce0c222ac7ec)
=> fix: added letter-spacing to fix Inter Regular line break issue

app/sagas/init.js
We added a migration from WatermelonDB to MMKV for servers.biometry field, so users don't lose their preferences for biometry on app update, so we can remove this block of code.
https://rocketchat.atlassian.net/browse/NATIVE-54
=> chore: removed biometry migration to MMKV

app/containers/MessageActions/index.tsx, e2e/tests/room/02-room.spec.ts
Move the Edit option to the top of message action sheet.
https://rocketchat.atlassian.net/browse/NATIVE-672
- Go to room;
- Send a message;
- long press this message;
- edit should be on top of action sheet;
| Before                       | After                       |
|-------------------------------------|-------------------------------------|
| ![Simulator Screenshot 1](https://github.com/user-attachments/assets/d4791de4-b213-4df2-ad54-8e30323bf755) | ![Simulator Screenshot 2](https://github.com/user-attachments/assets/6869d170-91a3-4d4f-b793-142759124866) |
=> feat: move edit action to top of message actions

app/containers/MessageComposer/components/ComposerInput.tsx, e2e/tests/room/02-room.spec.ts
On https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5827, we fixed an issue causing the draft to remain saved after the message is sent.
However, that bug can still be reproduced in some cases.
On that PR we added `forceUpdateDraftMessage` on `setInput`, to be used only on `getTextAndClear`, which is called on send message.
It bypasses the logic from `useAutoSaveDraft` to force clear it.
However, `useAutoSaveDraft(textRef.current)` uses `textRef` and `setInput` doesn't trigger a rerender.
In the end, `useAutoSaveDraft` would keep the value before `setInput` was called with `forceUpdateDraftMessage` and the draft would be saved with that value again.
Since `setInput` is going to call `setMicOrSend` (to mic icon) every time a new message is sent, I added a call to `const mic = …
=> fix: draft message not being updated

app/containers/markdown/Emoji.tsx, app/containers/markdown/index.tsx, app/containers/markdown/styles.ts
when you send a big emoji it renders cutted (as a video below) because the lineHeight was defined with 22.
I updated the emoji component looking for the newMarkdown emoji component.
Regression added on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5845.
https://rocketchat.atlassian.net/browse/NATIVE-669
- Go to room;
- Send one emoji;
https://github.com/user-attachments/assets/48567cee-659c-49dc-8efc-aecdc4ea57a1
https://github.com/user-attachments/assets/79c43159-60e7-4b7d-9333-c2a939375c9b
https://github.com/user-attachments/assets/ea1d036f-db99-40f9-b4d1-8c16a3d2886f
https://github.com/user-attachments/assets/c12e5ba8-ff62-4e99-81ca-a9c74b432cf6
=> regression: Big emoji cutted

app/containers/message/Components/Attachments/Reply.tsx
Reduce the thumb image size and adjust the reply component layout to improve its distribution and optimize the space occupied by the message.
https://rocketchat.atlassian.net/browse/NATIVE-622
If you have one room with a message that have a thumb URL you can open this room, or you can mock this messages on List component:
| ![Image 1](https://github.com/user-attachments/assets/70da4505-286d-4cea-ab23-a697d02bfebc) | ![Image 2](https://github.com/user-attachments/assets/807c666e-1482-46d0-8efe-f7cbb7181525) |
|:---:|:---:|
| ![Screenshot_1727813558](https://github.com/user-attachments/assets/a1d7be0d-4aa5-414c-8d9e-7b49ee91e89b) | ![after](https://github.com/user-attachments/assets/017254d0-026a-4d24-98d1-a749d0a8508e) |
|:---:|:---:|
=> fix: update thumb message layout

app/lib/services/restApi.ts, app/views/DirectoryView/index.tsx
Update the query parameters for `/directory`.
https://rocketchat.atlassian.net/browse/NATIVE-703
- Go to directoryView;
=> chore: updated params of getDirectory

app/views/RoomInfoView/index.tsx
Fixed a issue where direct message names could be edited in the mobile app, while this functionality is correctly restricted in the web client. Mobile app was not checking the channel type before allowing name edits.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5904
|Before|After|
| --- | --- |
| <img width="378" alt="Screenshot 2024-11-09 at 3 56 41 PM" src="https://github.com/user-attachments/assets/33608506-a4ac-4087-81c6-bfa4933e5c52"> | <img width="378" alt="Screenshot 2024-11-09 at 3 56 59 PM" src="https://github.com/user-attachments/assets/0375b027-d79b-4d50-b3de-fd2f01fa0c31"> |
=> Fix: Prevent DM name editing in mobile client

app/views/RoomMembersView/index.tsx
Currently, when a member's name is missing, the app renders nothing, while the web client displays the username in such cases. This PR aligns the app’s behavior with the web client by ensuring the username is shown when the member name is missing. Additionally, I noticed that the divider between two members is either too light or missing, so I’ve fixed this issue by adding a `marginBottom` of *0.5* to the member component.
none
|Before|After|
| --- | --- |
| <img width="378" alt="Screenshot 2024-11-13 at 12 08 54 AM" src="https://github.com/user-attachments/assets/83c7504d-113f-42b8-a23e-6319922a4f15"> | <img width="378" alt="Screenshot 2024-11-13 at 12 09 37 AM" src="https://github.com/user-attachments/assets/1caef458-015a-4e4b-b59d-c0a1eae510e3"> |
=> fix: Display username when member name is missing in members list

app/views/NewServerView/index.tsx
When attempting to add a new workspace, clicking the Connect button caused the keyboard to close without executing the intended functionality. This PR resolves the issue by ensuring that pressing the Connect button triggers the appropriate function instead of just dismissing the keyboard. The button now behaves as expected.
Closes #6025
https://github.com/user-attachments/assets/985d5781-69e7-4dec-8b99-77d0c6b39aaf
=> fix: Add workspace requiring extra tap to connect

app/containers/message/Urls.tsx, app/lib/constants/defaultSettings.ts
Admin > Message > Embed Link Previews
|  Turned on | Turned off  |
|---|---|
| <img width="524" alt="Screenshot 2024-12-17 at 15 19 57" src="https://github.com/user-attachments/assets/deec6a16-69a7-4049-ac65-1a31f5a4b77e" />  | <img width="413" alt="Screenshot 2024-12-17 at 15 20 27" src="https://github.com/user-attachments/assets/39f939d4-559c-4d25-ae48-34301d9f711f" />  |
[NATIVE-742]
[NATIVE-742]: https://rocketchat.atlassian.net/browse/NATIVE-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Support API_Embed setting

app/views/RoomView/Banner.tsx, app/views/RoomView/index.tsx
This PR resolves two issues with the announcement banner. 
- Announcement banner close button was difficult to interact, which has been fixed by adding a hitSlop to improve touch responsiveness. 
- The banner was visible in both normal chats and thread channels, this has been fixed to ensure the banner is hidden in thread channels.
N/A
1. Go to any channel which have announcement message
2. Go to any thread in the same channel
3. Observe the announcement message is visible at the top of the channel
| Scenario | Before| After |
| --- | --- | --- |
| Close button hitbox | <img width="380" alt="Screenshot 2024-11-30 at 3 12 17 PM" src="https://github.com/user-attachments/assets/7ddb93d8-5ee3-46e9-a42f-2c2d88f32bb7"> | <img width="376" alt="Screenshot 2024-11-30 at 3 08 33 PM" …
=> fix: announcement banner closing issue and visibility in hidden thread channels

app/containers/markdown/index.tsx, app/containers/message/Message.stories.tsx
Regression introduced on #6080
| Before    | After |
| -------- | ------- |
| <img width="515" alt="Screenshot 2025-02-14 at 16 37 08" src="https://github.com/user-attachments/assets/e5198ccb-5fa3-4446-b47d-5e563a9eef23" />|  <img width="515" alt="Screenshot 2025-02-14 at 16 37 20" src="https://github.com/user-attachments/assets/a19bc186-c8ae-4e50-849d-1f51d73bb0d7" />  |
[NATIVE-790]
[NATIVE-790]: https://rocketchat.atlassian.net/browse/NATIVE-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regression: auto translate not working

app/containers/message/RepliedThread.tsx, app/containers/message/Urls.tsx
Adjusted color token of url title and replied thread.
https://rocketchat.atlassian.net/browse/MA-165
=> feat(a11y): Links contrast

app/containers/List/ListItem.tsx, app/views/GetHelpView.tsx, app/views/LegalView.tsx, app/views/PushTroubleshootView/components/NotificationDelay.tsx, app/views/SettingsView/index.tsx
Currently, when using TalkBack or VoiceOver to navigate to the SettingsView, the screen reader identifies options that open an external link as buttons. This PR will fix this by updating the accessibilityRole to 'link.'
https://rocketchat.atlassian.net/browse/MA-111
=> feat(a11y): External link as link on screen reader

app/lib/services/restApi.ts, app/views/SetUsernameView.tsx
Asks the name from the user during signup using Social Auth so to not leave the name slot empty.
#6138 
1. Use a new email address not used in Rocket Chat.
2. Sign up using Social Auth.
3. There is no field to ask for the name of the user and as a result
I thoroughly debugged the SocialOAuth flow, checking all params in sdk.ts and all auth related functions such as  login() [connect.ts], loginTOTP() [connect.ts], also tracing requests and their responses from and to @rocket.chat/sdk, and verifying backend auth routes. I found that in the result.me section ([screenshot](https://github.com/user-attachments/assets/a826fa0d-fa4a-4013-8d9c-aafbef107b59)), key values like name and username are coming as undefined, seemingly from the `@rocket.chat/sdk`.
To cross-check, I tried calling …
=> fix: add Name field to SetUsernameView

package.json, yarn.lock
This dev dependency seems to be unused since mocha was removed in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4866
More details: `ts-node` pulls in tons of transitive dependencies which is causing duplication and affecting module-resolution.
=> chore(deps): remove unused ts-node dependency

app/lib/constants/defaultSettings.ts, app/lib/methods/helpers/formatAttachmentUrl.ts
Modified formatAttachmentUrl to append rc_token and rc_uid only when FileUpload_ProtectFiles is enabled. This prevents unnecessary URL parameters when the setting is disabled.
https://rocketchat.atlassian.net/browse/NATIVE-739
- Log in a workspace that you can change Protect Upload Files;
- Open an room with attachments;
(PS: to make it easier, use a console.log on formatAttachmentUrl results.)
=> fix: add userId and rcToken on attachmentURL only if protect files is enabled

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-suggestion.yml, .github/ISSUE_TEMPLATE/config.yml
This PR migrates our repository’s old issue template to a new, structured format. GitHub recent changes removed support for the old template, which resulted in a blank form being displayed to users while creating issue.
N/A
1. Create a issue in this Repo
2. It will display blank template
1. What users will see after clicking New Issue button
2. Bug report preview
3. Feature suggestion preview
=> chore: added new github issue templates

app/containers/EmojiPicker/EmojiCategory.tsx, package.json, patches/expo-image+1.10.6.patch, yarn.lock
Currently, GIF reactions are not animating on iOS after migrating from react-native-fast-image to expo-image. This PR applies a patch to fix GIF animation issues and restore proper GIF reaction support on iOS.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6222
React with animated emoji on message and observe
https://github.com/user-attachments/assets/e0bd8cab-77b9-43f9-8b5f-5361b6f1fe72
To resolve another iOS related issue, I replaced the FlatList import from `react-native-gesture-handler` with `react-native`. When using FlatList from gesture-handler, opening the emoji selection from the message input was triggering the error: "nativeViewGestureHandler must be used as a descendant of GestureHandlerRootView."
=> fix: gif reactions not animating on iOS

app/views/ThreadMessagesView/index.tsx
This PR fixes the issue with the indicator introduced in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6186. Previously, the indicator was rendered only after the filter was applied, but it failed to render when the screen was initially mounted. This PR ensures that the indicator is correctly rendered every time the screen is mounted.
Closes: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/6236
1. Apply a filter in thread in any channel and press back button
2. Go to same channel again and click on thread
3. Observe thread icon
Before: https://github.com/user-attachments/assets/8019784b-8852-4868-9f42-f02d8de87f49
After: https://github.com/user-attachments/assets/23a31788-4246-4b60-8b55-e3ec57566198
N/A
=> fix: filtered threads indicator not displaying on screen mount

app/containers/markdown/components/Plain.tsx, app/containers/markdown/styles.ts
This PR fixes an issue where message content with Markdown formatting, such as bold text and italic, was being rendered as plain text.
Regression introduced in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6326
Closes: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/6363
Closes #6361
N/A
| --- | --- |
|  <img width="375" alt="Screenshot 2025-05-16 at 12 59 29 AM" src="https://github.com/user-attachments/assets/150d9013-c6da-4f3e-8f31-f72031b2b5c4" /> | <img width="376" alt="Screenshot 2025-05-16 at 12 59 53 AM" src="https://github.com/user-attachments/assets/c6674d41-6da7-4ff8-a57c-547016136f22" /> | 
N/A
=> fix: markdown formatting in message

app/lib/services/connect.ios.test.ts, app/lib/services/connect.test.ts, app/lib/services/connect.ts
https://github.com/RocketChat/Rocket.Chat/pull/31497 started to return as null settings that used to return undefined.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/6412
https://rocketchat.atlassian.net/browse/NATIVE-928
=> fix: showButton null condition

app/containers/KeyboardView.tsx, app/containers/UIKit/MultiSelect/Input.tsx, app/views/CreateDiscussionView/index.tsx, app/views/CreateDiscussionView/styles.ts
- It fixes missing padding on createDiscussionView (regression introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6380);
- it fixes E2E `e2e/tests/room/04-discussion.spec.ts` tests failing (regression introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6446).
https://rocketchat.atlassian.net/browse/NATIVE-933
https://rocketchat.atlassian.net/browse/NATIVE-934
- Navigate to DiscussionView;
- Try to create a discussion;
| ![Simulator Screenshot - iPhone 16 - 2025-07-04 at 15 22 35](https://github.com/user-attachments/assets/ec91e216-10a3-49c3-bb8d-e755212fbf84) | ![Simulator Screenshot - iPhone 16 - 2025-07-04 at 18 02 03](https://github.com/user-attachments/assets/3f185a39-befe-4a51-a5bc-12 …
=> fix: CreateDiscussionView padding and discussion E2E tests

app/containers/MessageComposer/hooks/useEmojiKeyboard.tsx
This PR fixes an issue where, when we open a chat room and try to send an emoji using the OS provided keyboard, it overlaps the toolbar on iOS and hides the TextInput on Android. This makes it difficult to send the emoji directly; to send it, we first have to open the keyboard in text mode.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/6550
1. Go to any chat room
2. Click the text input
3. Click on keyboard emoji button
4. Observe the toolbar and send button is getting overlapped on iOS and TextInput is not visible on Android
| OS | Before | After |
| --- | --- | --- |
| Android | <img width="377" height="794" alt="Screenshot 2025-08-12 at 4 35 37 PM" src="https://github.com/user-attachments/assets/99ac1b98-877b-487d-9e48-7f89976a2c89" /> | <img width="376" …
=> fix: keyboard overlap send button and toolbar when switching to keyboard's emoji mode

ios/AppDelegate.swift
Cleanup leftovers on AppDelegate from #6478 
https://rocketchat.atlassian.net/browse/NATIVE-968
=> chore(iOS): Cleanup AppDelegate

.github/workflows/build-pr.yml, ios/fastlane/Fastfile
During the migration from CircleCI to GitHub Actions in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6447, I forgot to change [setup_circle_ci](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/ios/fastlane/Fastfile#L20) to [setup_ci](https://docs.fastlane.tools/actions/setup_ci/), which is more suitable and recommended by fastlane for GitHub Actions. The previous setup was causing the iOS build to hang on Signing NotificationService.appex, which resulted in the build failing. Hopefully, this change will fix the hanging issue.
[Run 1](https://github.com/RocketChat/Rocket.Chat.ReactNative/actions/runs/17067295823)
[Run 2](https://github.com/RocketChat/Rocket.Chat.ReactNative/actions/runs/17065016163/attempts/1)
[Run …
=> chore: using setup_ci for ios build
