- app/views/RoomActionsView/index.js
Reverts RocketChat/Rocket.Chat.ReactNative#3185
> Revert "[IMPROVEMENT] Load team's rooms from local database on team leave"

- app/lib/database/model/migrations.js
- app/lib/database/schema/app.js
- app/sagas/room.js
- app/views/RoomActionsView/index.js
- app/views/RoomInfoEditView/index.js
- e2e/tests/team/02-team.spec.js
> [FIX] Teams tests

- app/utils/messageTypes.js
Save room info when config which system message do you want to hide.
- When selecting: `Hide "Was Set Role" messages` or `Hide "Role No Longer Defined" messages`, shows an error when click to save
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3115
- go to `Room Info Edit`
- turn on `Hide System Messages`
- select `Hide "Was Set Role" messages` or `Hide "Role No Longer Defined" messages`
- then, press the `SAVE`
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
Closes #3115
> [FIX] Wrong system messages being passed as parameters to room save

- __tests__/__snapshots__/Storyshots.test.js.snap
- app/presentation/RoomItem/index.js
- storybook/stories/RoomItem.js
If `onLongPress` isn't sent to `RoomItem`, long press would crash the app.
> [FIX] RoomItem's long press crashing the app if prop is missing

- app/containers/markdown/Link.js
> [FIX] Crashing on link press

- app/lib/methods/getSettings.js
- app/lib/rocketchat.js
- app/sagas/login.js
On #3222 we made the app reactive to changes on settings stream.
That introduced an error on login, causing the app to try to subscribe to an event before the user was logged in.
This PR moves the subscribe part to login saga.
- Login should work properly
- Settings should still change over stream
> [FIX] Subscribe to settings making app to hang on login

- patches/react-native+0.63.4.patch
RoomView's list is slow on Android 11.
This PR uses [this workaround](https://github.com/facebook/react-native/issues/30034#issuecomment-806396274) + a workaround for RefreshControl.
Applying `scaleY` without `transform` is deprecated though https://github.com/facebook/react-native/blob/dc80b2dcb52fadec6a573a9dd1824393f8c29fdc/Libraries/DeprecatedPropTypes/DeprecatedTransformPropTypes.js#L53
https://github.com/facebook/react-native/issues/30034
Could see the difference between the animated emojis
https://user-images.githubusercontent.com/47038980/124982314-ee77f380-e00c-11eb-86af-cabe1357f459.mp4
https://user-images.githubusercontent.com/47038980/124982332-f33ca780-e00c-11eb-9a2f-d08140544b47.mp4
> [FIX] Poor performance in messages list on Android 11

- app/index.js
- app/share.js
- app/views/ThemeView.js
Sets black theme as default dark theme
1. Go to `Settings > Theme`
You should be able to see `Black` as default `Dark Level`
> [IMPROVE] Set black as default dark theme

- app/utils/openLink.js
- app/views/DefaultBrowserView.js
Use `system default` as the default option to open links
When `inApp` is selected as the default browser, the deep link for other apps don't work.
- Browser/Safari should be the default option
> [IMPROVE] Make `system default` the default browser

- app/i18n/locales/ar.json
- app/i18n/locales/de.json
- app/i18n/locales/en.json
- app/i18n/locales/es-ES.json
- app/i18n/locales/fr.json
- app/i18n/locales/it.json
- app/i18n/locales/ja.json
- app/i18n/locales/nl.json
- app/i18n/locales/pt-BR.json
- app/i18n/locales/pt-PT.json
- app/i18n/locales/ru.json
- app/i18n/locales/tr.json
- app/i18n/locales/zh-CN.json
- app/i18n/locales/zh-TW.json
- app/views/RoomsListView/index.js
Remove difference from private groups and channels by grouping them together
1. On the sorting dropdown, tap on `Group by type`
It should group public channels and private groups together
> [IMPROVE] Remove difference between public/private on "Group by type"

- app/lib/methods/getSettings.js
Recently, we added support to more settings from server, but that reached 52 settings being fetched and the server started paginating the results.
This PR adds `count` param to the request based on the number of settings we have.
- Start the app
- Make sure all settings are on redux
> [REGRESSION] Settings pagination not working

- app/containers/markdown/Link.js
> Regression: Markdown handlePress not working properly

- package.json
Run lint and tests on staged files only instead of all the files
> Chore: Run lint and tests on staged files only

- app/views/RoomsListView/Header/Header.js
Remove the list of servers from the Rooms list view.
N/A
Open the app, after login you be able to se an error on the emulator.
After the fix:
> [FIX] Conflicts not resolved properly on 4.18.0

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.19.0

- package.json
After #3279, lint-staged stopped working.
- Create a temp branch
- Try to commit a change that should fail on a JS file
- Try to commit a change that should fail on a TS file
Note: Don't run it with `--no-verify` as I did on #3279 😅
> Fix: lint-staged not working properly

- app/views/RoomActionsView/index.js
- app/views/RoomView/index.js
After an agent opens a chat from Omnichannel's queue, then `Take It` and goes to Actions view, the omnichannel's buttons didn't appear properly. So this PR pass the param `joined` from Room view to Actions view to test if all the omnichannel's buttons should appear. 
- You need to be an agent from omnichannel
- Go to the Omnichannel's queue, open one room
- Go to 
- Now, you are the agent that 
**BEFORE**
https://user-images.githubusercontent.com/47038980/134575934-e2db75ce-4a44-435b-b4b4-4c108153ae6a.mp4
**AFTER**
https://user-images.githubusercontent.com/47038980/134575658-75d2c5a8-d0cf-44d3-b345-965a83c3f227.mp4
> [FIX] Room Actions buttons not showing after taking a channel from Omnichannel Queue

- app/views/AuthLoadingView.tsx
> Chore: Migrate AuthLoadingView to Typescript

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.22.0

- app/stacks/OutsideStack.js
Fixes the additional general onboarding screen for the Rocket.Chat app being available for selection in the single-server build.
In the single server build there was the ability to move back from the single server onboarding screeen to the general Rocket Chat onboarding screen with a "back" button.
This is removed with this PR.
No Github issue opened, referring to chat with Diego Mello: https://open.rocket.chat/channel/react-native?msg=yvzfXMpsMZChrXXAG
See above
> Remove NewServerView from single-server

- app/views/DisplayPrefsView.js
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table >
> [FIX] Display prefs showing wrong header icon on tablet

- app/views/ScreenLockConfigView.tsx
Migrate ScreenLockConfigView to Typescript
- When logged, go to `Settings -> Security and privacy -> Screen lock`
- Then, this is the view to check the behavior.
> Chore: Migrate ScreenLockConfigView to Typescript

- app/views/SecurityPrivacyView.tsx
Migrate SecurityPrivacyView to Typescript
- When logged with an account, go to `Settings -> Security and privacy`
- Then, this is the view migrated, test the buttons and selects
> Chore: Migrate SecurityPrivacyView to Typescript

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.23.0

- app/lib/rocketchat.js
Starting 4.2, the server started excluding a few columns for some requests https://github.com/RocketChat/Rocket.Chat/pull/23701/files#diff-dc251dbffb8ab53b6f3a186f7c8237d5564c2e368b20711cfa15d0a337425694R109
Since we only pick the ones we're using to make the request faster, it started to raise an error, because Mongo can't do both at the same time.
This PR removes the usage of fields.
- Go to a room, click o header
- Then inside the `Actions` you click on `Files`
- You should be moved to `Files List` and shows the files.
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table >
> [FIX] Files screen stopped listing content on server 4.2

- app/views/ThreadMessagesView/Item.tsx
> [FIX] Lint not ignoring Markdown props

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.24.0

- ios/Podfile.lock
- patches/react-native-device-info+8.4.8.patch
Chore: Update react-native-device-info patch-package and pods
Test jitsi integration
> Chore: Update react-native-device-info patch-package and pods

- app/definitions/INotification.ts
- app/notifications/push/index.ts
- app/notifications/push/push.ios.ts
- app/notifications/push/push.ts
Fix app crash on opening a notification when app is closed
Open notification when app is closed
> [FIX] App crashes when opening a notification while app is closed

- app/utils/room.ts
When you reply to a message as a thread, then that message that created the thread is deleted, if the user goes to `ThreadMessagesView` will crash the app, because that thread didn't have a name or title. So, to fix this issue need to refactor and add an interrogation mark to check if the object is undefined
- Create a message
- Reply to this message as a thread
- Delete the message
- Click on the Thread button, besides the search button
> [FIX] makeThreadName asserting undefined as non-null

- app/utils/room.ts
- app/views/ThreadMessagesView/index.tsx
Go to a room that is used a lot, as #general or #react-native in the open.rocket.chat. Then when opening the room, click on the `Thread button` beside the `search button`, and in the ThreadMessagesView scroll and you should see the threads pagination
> [FIX] Threads' pagination not working

- app/containers/MessageBox/index.tsx
There are 4 ways of sharing images on our apps:
- Take a photo: sends as HEIC
- Choose from library: sends as HEIC
- Choose file: sends as HEIC
- Share extension: sends as JPG
We need to send as JPG as much as possible, but "Choose file" is trickier to do it.
Let's focus on "Take a photo" and "Choose from library" for now.
Removed compression from "Take a photo" so we don't apply compression anywhere.
Closes #3635 
- "Take a photo" should send as JPG
- Choose a HEIC from library and it should convert to JPG
- "Choose file" wasn't changed, but try submitting HEIC anyway
- Share HEIC file from Photos app and it should convert to JPG
- In all cases, send similar photos (e.g. same desk or plant) and compare the final sizes to make sure we're not compressing
- Only compression was changed, so …
> [IMPROVE] Convert images to JPG and remove compression

- ios/RocketChatRN.xcodeproj/project.pbxproj
- yarn.lock
Updated some yarn.lock libs and pods so that the iOS build works correctly.
However it is necessary to test if the integration with Jitsi is working correctly.
> [FIX] Fix iOS CI build

- app/lib/rocketchat.js
Before:
https://user-images.githubusercontent.com/77742477/152871904-08e6daeb-64f8-4957-b63a-cc0b17ace383.mp4
After:
https://user-images.githubusercontent.com/77742477/152871914-edc150f8-c220-4993-b5c3-0c5689088b9d.mp4
* Add a new server and you'll see dispatch of LOGIN_REQUEST action which is not the expected behavior while adding a new server.
The issue was caused by using the previously stored user and login details from the Redux store while adding a new server which hence got through the if statement to dispatch a loginRequest with that details (User token) .
> [FIX] Unnecessary login dispatch on adding new server

- app/containers/message/Message.tsx
The jitsi call button is being treated as normal message and shows the message actions like delete,star etc. The expected behavior is similar to that of info/system messages. Also Deleting the message from the mobile leaves the button on the web.
> [FIX] Disable tap gesture on call messages

- app/ReactotronConfig.js
Implementation of async storage in reactotron to solve the problem of multiple connections when reloading the app when debugging on android devices.
https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md
Open reactotron in the old version and reload the app, without async storage it will open multiple connections, with async storage it will continue with a single connection.
with async storage (after many reloads):
without async storage(after many reloads):
> [FIX] Fix reactotron multiple connections

- app/definitions/IRocketChat.ts
> Chore: Fix rocketchat interface

- package.json
- yarn.lock
> [FIX] #3606 merged using wrong JS SDK branch

- app/lib/rocketchat/rocketchat.js
- app/lib/rocketchat/services/sdk.ts
Move a few missing methods away from rocketchat.js to SDK.
> Chore: Move some methods to SDK

- app/lib/methods/subscriptions/rooms.js
- Added support for sending ephemeral messages inside threads when they have `tmid`
- Added all extra info from the message payload, like user object
- Send `/sendlater help` on a thread from the app
- It should receive and render the ephemeral message inside the thread (not on main room)
> [IMPROVE] Add support for ephemeral messages inside threads

- app/definitions/ISubscription.ts
- app/definitions/rest/v1/chat.ts
- app/lib/rocketchat/methods/roomTypeToApiType.ts
- app/lib/rocketchat/rocketchat.js
- app/lib/rocketchat/services/restApi.ts
- app/lib/rocketchat/services/sdk.ts
- app/utils/goRoom.ts
- app/views/AddExistingChannelView.tsx
- app/views/AutoTranslateView/index.tsx
- app/views/CannedResponsesListView/index.tsx
- app/views/DirectoryView/index.tsx
- app/views/DiscussionsView/index.tsx
- app/views/ForwardLivechatView.tsx
- app/views/LivechatEditView.tsx
- app/views/MessagesView/index.tsx
- app/views/NotificationPreferencesView/index.tsx
- app/views/TeamChannelsView.tsx
- app/views/ThreadMessagesView/index.tsx
Dehydrate all simple server requests from `rocketchat.js` to `rocketchat/services/restapi.ts`.
This is just a temporary solution to be able to use Typescript, move to an easier and more maintainable file structure and until we start the migration to React Hooks.
On this upcoming migration to Hooks, we're going to create a custom hook similar to [useEndpointData](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/hooks/useEndpointData.ts#L9), which is the one used on our web app. With that in hands, we're going to start extracting those endpoints away from the file I've introduced on this PR.
- General tests
> Chore: dehydrate rest api methods away from rocketchat.js

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.25.0

- app/lib/methods/getRooms.js
- app/lib/methods/getRooms.ts
Migrate methods/getRooms to TypeScript
Test on the main screen (RoomListView), check that rooms update correctly
> Chore: Migrate methods/getRooms to TS

- app/definitions/IMessage.ts
- app/definitions/IThread.ts
- app/definitions/IThreadMessage.ts
- app/lib/database/services/Subscription.ts
- app/lib/methods/updateMessages.ts
- e2e/helpers/app.js
- e2e/tests/assorted/11-deeplinking.spec.js
We need to test the load of messages in general.
> Chore: Migrate updateMessages to Typescript

- app/selectors/login.ts
- app/views/UserPreferencesView/index.tsx
Migrate `selector/login` to TypeScript
1. Check login services are being displayed properly
2. Check login form shows properly
3. Check login button shows properly
> Chore: Migrate selector/login to TS

- app/definitions/IThread.ts
- app/definitions/IUrl.ts
- app/definitions/index.ts
- app/lib/methods/helpers/parseUrls.ts
Migrate helpers/parseUrls to Typescript
Enter a room and see if a message with url will render correctly.
> Chore: Migrate helpers/parseUrls to Typescript

- app/lib/methods/helpers/parseQuery.js
- app/lib/methods/helpers/parseQuery.ts
- Login in 1open.rocket.chat1
- Then copy this link: https://go.rocket.chat/room?host=open.rocket.chat&path=channel/general/thread/meRK2nfjR99MjLn55
- Paste it inside the device's browser
- Then you should be redirect to a thread into GENERAL channel
> Chore: Migrate methods/helpers/parseQuery to Typescript

- app/definitions/IServer.ts
- app/lib/methods/enterpriseModules.ts
- app/lib/utils.ts
- app/reducers/enterpriseModules.ts
> Chore: Migrate methods/enterpriseModules to TS

- app/lib/methods/helpers/mergeSubscriptionsRooms.ts
Fix mergeSubscriptionsRooms function
With the fix (Pay attention to channel tc230222b):
Without the fix (Pay attention to channel tc230222b):
> [FIX] mergeSubscriptionsRooms function using the wrong object

- app/lib/rocketchat/services/restApi.ts
removing unused function getTeamInfo
> Chore: Remove unused function getTeamInfo

- app/definitions/rest/v1/e2e.ts
- app/definitions/rest/v1/index.ts
- app/lib/rocketchat/services/restApi.ts
Create definitions for e2e.setUserPublicAndPrivateKeys api call
When changing a user's password the api is called, if the new keys are changed correctly the change will have worked.
> Chore: Create definitions for e2e.setUserPublicAndPrivateKeys api call

- app/lib/rocketchat/services/restApi.ts
Migrate REST API - toggleBlockUser to Typescript
- Block/ Unblock users
> Chore: Migrate REST API - toggleBlockUser to Typescript

- app/lib/rocketchat/services/restApi.ts
> Chore: Delete unused function getUserRoles

- app/definitions/rest/v1/channels.ts
- app/definitions/rest/v1/groups.ts
- app/definitions/rest/v1/im.ts
- app/lib/rocketchat/services/restApi.ts
> Chore: Migrate REST API - leaveRoom to Typescript

- app/definitions/rest/v1/channels.ts
- app/definitions/rest/v1/groups.ts
- app/definitions/rest/v1/im.ts
- app/lib/rocketchat/services/restApi.ts
> Chore: Migrate REST API - deleteRoom to Typescript

- app/definitions/rest/v1/channels.ts
- app/definitions/rest/v1/groups.ts
- app/definitions/rest/v1/im.ts
- app/lib/rocketchat/services/restApi.ts
> Chore: Migrate REST API - hideRoom to Typescript 

- app/views/ForwardLivechatView.tsx
Refactor the ForwardLivechatView to remove IUser generic and use the correct from rest api
> Chore: Migrate REST API - usersAutoComplete to Typescript

- app/definitions/rest/v1/channels.ts
- app/lib/rocketchat/services/restApi.ts
> Chore: Migrate REST API - toggleRoomLeader to Typescript

- app/lib/rocketchat/services/restApi.ts
Migrate REST API - returnLivechat to Typescript
- Take a new omnichannel's chat, than go to `RoomActionsView` and click on `Return` button
> Chore: Migrate REST API - returnLivechat to Typescript

- app/definitions/rest/v1/channels.ts
- app/definitions/rest/v1/groups.ts
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - getRoomCounters to Typescript
- Inside a channel or team go to `RoomActionsView` and see how many members there are in your room
> Chore: Migrate REST API - getRoomCounters to Typescript

- app/sagas/rooms.js
Just removes a migration to Teams feature.
Not necessary anymore.
> Chore: Remove Teams migration

- app/definitions/rest/v1/omnichannel.ts
- app/ee/omnichannel/lib/subscriptions/inquiry.ts
- app/lib/rocketchat/services/restApi.ts
- app/views/LivechatEditView.tsx
getAgentDepartments to Typescript
- To take an omnichannel's room from the queue or open the `RoomInfoEditView` from an omnichannel's room should keep working
> Chore: Migrate REST API - getAgentDepartments to Typescript

- app/definitions/IProfileViewInterfaces.ts
- app/definitions/rest/v1/users.ts
- app/lib/rocketchat/services/restApi.ts
- app/views/ProfileView/index.tsx
- app/views/RoomInfoEditView/index.tsx
Migrate REST API - saveUserProfile to Typescript
- Change your profile
> Chore: Migrate REST API - saveUserProfile to Typescript

- app/definitions/IMessage.ts
- app/definitions/rest/v1/chat.ts
- app/lib/rocketchat/services/restApi.ts
- app/views/ReadReceiptView/index.tsx
Migrate REST API - getReadReceipts to Typescript
- Send a message inside a chat in `mobile.rocket.chat`
- Then do a long press in your message and up the modal, then click on `ReadReceipts`
> Chore: Migrate REST API - getReadReceipts to Typescript

- app/containers/MessageBox/index.tsx
- app/definitions/rest/v1/commands.ts
- app/definitions/rest/v1/index.ts
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - getCommandPreview to Typescript
> Chore: Migrate REST API - getCommandPreview to Typescript

- app/containers/MessageBox/CommandsPreview/index.tsx
- app/containers/MessageBox/index.tsx
- app/definitions/ISlashCommand.ts
- app/definitions/rest/v1/commands.ts
- app/definitions/rest/v1/index.ts
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - executeCommandPreview to Typescript
- In `open.rocket.chat` type `/giphy` or `/tenor` in any room
> Chore: Migrate REST API - executeCommandPreview to Typescript

- app/definitions/rest/v1/directory.ts
- app/definitions/rest/v1/index.ts
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - getDirectory to Typescript
- Go to `DirectoryView`
> Chore: Migrate REST API - getDirectory to Typescript

- app/lib/rocketchat/services/connect.ts
- app/lib/utils.ts
Migrate REST API - getServerInfo to Typescript
- Login in any server
> Chore: Migrate REST API - getServerInfo to Typescript

- app/lib/rocketchat/rocketchat.js
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - sendEmailCode to Typescript
And move `sendEmailCode` from `rocketchat.js` to `restApi.ts`
> Chore: Migrate REST API - sendEmailCode to Typescript

- app/lib/rocketchat/services/restApi.ts
- app/views/AutoTranslateView/index.tsx
Migrate REST API - saveAutoTranslate to Typescript
> Chore: Migrate REST API - saveAutoTranslate to Typescript

- app/definitions/rest/v1/channels.ts
- app/definitions/rest/v1/groups.ts
- app/definitions/rest/v1/im.ts
- app/lib/rocketchat/rocketchat.js
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - getRoomMembers to Typescript
> Chore: Migrate REST API - getRoomMembers to Typescript

- app/lib/rocketchat/rocketchat.js
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - removePushToken to Typescript
> Chore: Migrate REST API - removePushToken to Typescript

- app/containers/Header/index.tsx
- app/containers/List/ListHeader.tsx
- app/containers/List/ListInfo.tsx
- app/views/RoomsListView/Header/Header.tsx
- app/views/RoomsListView/Header/index.tsx
- app/views/RoomsListView/ListHeader/index.tsx
- app/views/RoomsListView/index.tsx
Removes `any`, `ts-ignore` and `withTheme` HOC for the following components:
- Header
- ListHeader
- RoomsListView's Header
- RoomsListView's ListHeader
> Chore: evaluate Header components - TypeScript

- app/containers/BackgroundContainer/index.tsx
Removes `theme` from `withTheme` HOC and use `theme` from `useTheme` instead; no need for `theme!` anymore
> Chore: Evaluate BackgroundContainer - TypeScript

- app/definitions/rest/v1/e2e.ts
- app/lib/rocketchat/rocketchat.js
- app/lib/rocketchat/services/restApi.ts
Migrate REST API - e2eFetchMyKeys to Typescript
> Chore: Migrate REST API - e2eFetchMyKeys to Typescript

- package.json
- yarn.lock
Update codecov version from `3.8.2` to `3.8.3`.
> Chore: Update codecov version

- app/views/RoomInfoEditView/index.tsx
> [FIX] Param privacy when editing room info

- app/containers/markdown/Hashtag.tsx
Update navToRoom press verification
The old check was wrong as the index could be zero and zero is false :)
Closes #3937
> [FIX] Update navToRoom press verification

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.26.1

- app/containers/LoginServices.tsx
We introduced on this [PR](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3935), an error that makes impossible show all the login services option.
N/A
On the app, choose a server -> click on login -> more options;
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
<video width="150" controls src="https://user-images.githubusercontent.com/14894380/160638184-18af730a-8da7-4649-a2ea-c985e5281119.mov"></video>        
</td>
<td>
<video width="150" controls src="https://user-images.githubusercontent.com/14894380/160638291-5240314a-55e1-4674-bd1c-6c539fc28352.mov"></video>
</td>
</tr>
</tbody>
</table >
> [FIX] Animation to show all login services options

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.26.2

- app/containers/RoomHeader/RoomHeader.tsx
Chore: Evaluate RoomHeader - TypeScript
> Chore: Evaluate RoomHeader - TypeScript

- app/actions/login.ts
- app/i18n/locales/en.json
- app/sagas/login.js
Meteor deals with two possible message errors related to login: 
`You've been logged out by the server. Please log in again`: the token doesn't exist on the database
`Your session has expired. Please log in again`: the token has expired
This PR adds support for the expired message.
- Have two sessions
- Go to profile and tap "Logout from other locations"
- The app should redirect to onboarding and show `You've been logged out by the server. Please log in again`
- You'll need to run the server on your machine with Meteor, so you can update the collection on MongoDB
- Find the user id and update expire the token manually with something like `db.users.update({_id:'userId'},{$set:{'services.resume.loginTokens.0.when': new Date(2021, 0, 1)}})` (Talk to me if in doubt and I can give you some …
> [FIX] Add token expired verification

- app/views/CreateDiscussionView/SelectUsers.tsx
`getUsers` was using the `spotlight` and local DB tables to search for users. On the filtering this was causing to bring up users randomly or no users, depending on the case.
1. Go to `Create a discussion`
2. On `Invite users` search for any user
It shouldn't bring random users while you type
> [FIX] Searching for users when creating discussions not returning data correctly

- app/containers/MessageBox/index.tsx
- Reply in thread
- Open the thread and upload a file or image to the thread
https://user-images.githubusercontent.com/47038980/163301439-d1e38bfd-612e-4f6b-9437-3a8b870b1d34.mov
> [FIX] Send upload inside a thread

- app/lib/notifications/push.ts
On #3958 we updated `react-native-notifications`, but we introduced a bug that would trigger push notifications when the app is in foreground.
We just send `alert: false` to the completion, so the local notification isn't triggered.
> [FIX] Stop showing native push notification when in foreground

- app/sagas/state.js
> Regression: Fix setBadgeCount import

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.27.0

- ios/fastlane/Fastfile
Related to https://github.com/fastlane/fastlane/issues/20172
> Chore: Migrate to update_code_signing_settings

- ios/Podfile.lock
- ios/RocketChatRN.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Fix websocket connection
Closes #4072
Join open server
Join mobile server
Join server with certificate
> Regression: Fix websocket connection

- app/views/CreateDiscussionView/SelectUsers.tsx
1. Go to `Create a discussion`
2. On `Invite users` search for any user and tap on it
3. Tap outside the modal to close it and search for a new user and tap on it
List should persist every selected user
> Regression: Users search on `CreateDiscussionView`

- android/gradle/wrapper/gradle-wrapper.properties
Upgrade Gradle to 6.9.2 for improved support and security fix.
The main focus of this update is:
Native support for Apple Silicon
Fix support for Zulu JDK
Mitigations for log4j vulnerability in Gradle builds
However other fixes can be seen in the gradle release notes:
https://gradle.org/releases/
> Chore: Upgrade Gradle from 6.7 to 6.9.2

- app/views/AutoTranslateView/index.tsx
Evaluate AutoTranslate
Enalbe the auto translate and check if still works fine.
> Chore: Evaluate AutoTranslate- TypeScript

- app/reducers/createChannel.ts
- app/views/CreateChannelView.tsx
Evaluate Create Channel
Test the Create Channel functionality.
> Chore: Evaluate Create Channel - TypeScript

- app/lib/notifications/push.ts
As the logic considers the number of badges to set the value, and as `0 === false`, the logic when from 0 badges is never completed.
The correct thing is to check if the bagde is number and apply the value.
Closes #4151
- Receive a push notification and the badge should point the correct unread count
- Tapping the push notification or the app icon should remove the badge count
> Regression: Fix badge count logic on iOS

- package.json
- yarn.lock
> Chore: Update ua-parser-js from 0.7.18 to 0.7.24 and set resolution

- android/app/build.gradle
- app/lib/notifications/push.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.27.1

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.28.0

- app/stacks/OutsideStack.tsx
- app/views/LegalView.tsx
- Convert to functional component
- Update interfaces
- Removes `withTheme` HOC
1. Test navigation to Legal screen and check everything renders or functions properly
> Chore: evaluate `LegalView`

- app/stacks/InsideStack.tsx
- app/stacks/MasterDetailStack/index.tsx
- app/views/MarkdownTableView.tsx
- Convert to functional component
- Update interfaces
- Remove `withTheme` HOC
- Test Markdown table
> Chore: evaluate `MarkdownTableView`

- app/stacks/InsideStack.tsx
- app/stacks/MasterDetailStack/index.tsx
- app/views/InviteUsersView/index.tsx
- Convert to functional component
- Remove `withTheme` HOC
1. Test for regressions on `Invite Users`
> Chore: evaluate `InviteUsersView`

- app/containers/RoomTypeIcon/OmnichannelRoomIcon.tsx
- app/containers/Status/index.tsx
- app/lib/hooks/index.ts
- app/lib/hooks/useAppSelector.ts
- app/lib/methods/useAppSelector.ts
- app/lib/methods/useServer.ts
- app/views/AuthLoadingView.tsx
- app/views/CannedResponseDetail.tsx
- app/views/CannedResponsesListView/index.tsx
- app/views/DiscussionsView/index.tsx
- app/views/DisplayPrefsView.tsx
- app/views/SecurityPrivacyView.tsx
- app/views/UserPreferencesView/index.tsx
> Chore: Create useAppSelector hook

- .circleci/config.yml
On #4056  we automated Android Experimental to land production without any hold step, but we broke Android Official.
The proposal of this PR is bring Official lane back
> Regression: Android Official lane on CI removed from develop branch

- app/containers/message/Reply.tsx
In this PR #4205 I forgot to change the color time for replied messages. So, the proposal of this PR is make the time on replied messages equal as the time for the message and time on rooms list. 
Check if the time on replied messages are equal to the others. (E.G: messages and rooms list). 
The problem was happened on dark theme, so please test with all themes we have.
> [FIX] Applying same color to the time on replied messages

- babel.config.js
- package.json
- yarn.lock
Fix develop build for real devices
Honestly I don't think it's necessary to merge this, probably with the update of react native this issue will be resolved.
Related to: https://github.com/facebook/react-native/issues/32453
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3371
Run on a real device using Xcode
> Chore: Fix develop build for iOS devices

- patches/commonmark+0.29.0.patch
Closes #4081
The issue is caused by the regex expression used to match name of the room after `#` which is used in the old markdown renderer. So if the  Message parser is enabled, the `NewMarkdown` will be used in place of this and the room mentions will be rendered just fine.
So to reproduce this issue , either the `enableMessageParser` has to be false or you can also turn off the internet connection and restart the app. You'll see that the room mentions that starts with `_` will not be rendered as expected.
Before :
After :
> [FIX] Channel mentions when the slug starts with underscore

- app/containers/UIKit/Actions.tsx
- app/containers/UIKit/Context.tsx
- app/containers/UIKit/DatePicker.tsx
- app/containers/UIKit/Image.tsx
- app/containers/UIKit/Input.tsx
- app/containers/UIKit/MultiSelect/index.tsx
- app/containers/UIKit/Section.tsx
- app/containers/UIKit/index.tsx
- app/containers/UIKit/interfaces.ts
- app/containers/UIKit/utils.ts
- app/externalModules.d.ts
- app/views/CreateDiscussionView/SelectUsers.tsx
- app/views/LivechatEditView.tsx
- app/views/RoomInfoEditView/index.tsx
- package.json
- yarn.lock
- Login into `open.rocket.chat`
- Go to a channel
- type `/poll` and create a poll, vote and finish it
- then type `/todo` create a todo, done, see completed
- Create a discussion inside a channel and from Rooms List View
- Create a channel, go to RoomInfoEditView, enable `Hide System Message` and select the system messages that you want to hide
> Chore: update @rocket.chat/ui-kit to 0.31.11

- app/containers/ActionSheet/ActionSheet.tsx
The closing animation of  `ActionSheets` was not working on item press after we merged [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4193). This PR fixes the issue.
> [FIX] Closing animation of action sheet on item press

- .github/dependabot.yml
Created the configuration file for dependabot, so that it starts automatically creating lib updates.
Validated in another repo: https://github.com/GleidsonDaniel/kinsta
Open PRs: https://github.com/GleidsonDaniel/kinsta/pulls
> Chore: Create dependabot.yml config

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.29.0

- app/views/RoomInfoEditView/index.tsx
The app was updating the form with new data, but that's not really expected from a form.
I removed the reactivity, so it should be just fine now.
- Editing a room should work fine
- Editing a room and immediately change any value should work (issue video attached below)
https://user-images.githubusercontent.com/804994/170341657-7dce55f8-9a95-457d-9120-94ef4c48a91c.mp4
> [FIX] Form re-rendering on RoomInfoEditView when app receives newer data from stream

- app/views/RoomView/index.tsx
Fix the in some discussions you haven't joined yet, messages are not being loaded.
Open a discussion in a open and private channel, try to loading without joining and joining the discussion.
> [FIX] In some discussions you haven't joined yet, messages are not being loaded.

- app/lib/methods/logout.ts
If a server is discontinued, it is not possible to remove it from the server listing.
It appears to only disappear after uninstalling and reinstalling the app.
- Build a new server
- Add it to your app
- Kill the server in question
- Try removing it from the server listing
- Test other approaches to logout from a server
https://user-images.githubusercontent.com/47038980/172287067-d08e009e-e018-4bc2-ac57-e5006b35246a.mov
https://user-images.githubusercontent.com/47038980/172287156-820ff237-c94a-40ff-b768-51d3e154c944.mov
> [FIX] Remove servers offline from server list

- app/containers/Toast.tsx
Migrate the containers/Toast from class component to functional component and using hooks. Also removed the interface and withTheme HOC, instead using useTheme hook.
Closes #4157 #4128
How the original PRs were "abandoned" follows this as the main one.
Test the toast functions like:
- Go to a chat and long hold on a message.
- Select the copy button from the message actions.
- You will be able to see the Copied to Clipboard! toast.
> Chore: Migrate containers/Toast to hooks

- package.json
- yarn.lock
> Chore: Resolve jpeg-js 0.4.4

- app/i18n/locales/pt-BR.json
> Regression: missing comma on i18n file

- app/lib/services/connect.ts
- app/views/UserPreferencesView/index.tsx
Closes #2610
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2576
- It should show `Enable message parser` on Profile > header right button for servers below v5
- +v5 should always use message parser
> [IMPROVE] Make message parser default

- app/views/RoomView/index.tsx
Fix check for changing header 
Change some property referring to the header on other screens such as roomInfoView or RoomEditView.
> [FIX] Room header not updating when room type changes

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.30.0

- app/sagas/selectServer.js
The user should be redirected to a screen that allows them to continue the login process.
Given there has already been an iframe login made 
- Go to the app's first screen and tap on the "workspace URL" field
- choose the "iframe" server from the dropdown
https://user-images.githubusercontent.com/47038980/180852638-53c0e235-e689-417a-a866-44a46e7d4e52.mov
https://user-images.githubusercontent.com/47038980/180852407-ec0c9ed7-adc5-46ba-ad49-85a3bdd651eb.mov
> [FIX] iFrame login takes user to blank screen

- app/views/RoomsListView/index.tsx
Change the logic to filter using tempChats instead of using the data from the observe.
On the RoomListView have a favorite and unread message, then try to change the display option (Group by).
Testing the three possible options.
> [FIX] Fix display order render on RoomListView

- app/share.tsx
Set native theme when launching the share extension
> [IMPROVE] Set native theme when launching the share extension

- app/containers/message/Audio.tsx
- app/lib/methods/audioFile.ts
- app/views/SettingsView/index.tsx
Downloads and store the audios instead of loading them.
- Now the audios are saved in the device storage.
- And they are also available offline.
- They are separated by server, if you want to delete them all from a server, you can delete them. (Clear local server cache)
Closes: #4350
Enter a room that has audios and load the audios, enter again and the others will load almost instantly, since they are already downloaded.
- Maybe add the config for the person to disable this?
> [NEW] Persist audio files

- app/containers/message/index.tsx
This regression was introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4366/files#diff-899f2d33cbae5b4ba6700d6ee729b87d681cbf7a42600f9064177aaa04ad82fdR118-R124. During the PR [IMPROVE] Add emoji picker to iOS. Was missing return if there wasn't return when closeEmojiAndAction was false. 
- Go to search messages
- Search for a message
- Tap on it
- It should jump to it
> Regression: Jump to message from search view

- app/views/SetUsernameView.tsx
> Chore: Hooks app/views/SetUsernameView

- app/stacks/OutsideStack.tsx
- app/views/ForgotPasswordView.tsx
Migrate ForgotPasswordView to hooks
> Chore: Hooks app/views/ForgotPasswordView

- app/views/JitsiMeetView.tsx
Fixes the error that appeared after pressing back or swipe back with ios in a jitsi call
Closes #4504
Enter a jitsi call and exit by pressing back on android or swipe back with ios and then try to enter the same or another call again.
> Regression: Jitsi not leaving call properly

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.31.0

- ios/RocketChatRN/Info.plist
> Chore: Remove unused iOS permissions

- app/views/DefaultBrowserView/index.tsx
The previous title was wrong because a copy/paste and missed a more careful review on my part https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4424
. Here is the fix for that regression.
> Regression: Default Browser View title

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.32.0

- app/containers/RoomHeader/RoomHeader.tsx
Fix iPad subtitle on Header font size
Before:
After:
Open the app on a tablet/ipad in landscape mode
Jira: [TC-139]
[TC-139]: https://rocketchat.atlassian.net/browse/TC-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Regression] Fix iPad subtitle font size on Header 

- app/views/E2EEncryptionSecurityView.tsx
Fix the padding between the separator and the second header in E2E Encryption View
- Enable the E2E when opening the app
- Go to Settings -> Security and Privacy -> E2E Encryption
Jira: [TC-159]
[TC-159]: https://rocketchat.atlassian.net/browse/TC-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regression: Reset E2E Key section missing padding

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.33.0

- e2e/data.ts
- e2e/data/data.cloud.ts
- e2e/data/data.docker.ts
- e2e/helpers/data_setup.ts
- e2e/tests/room/02-room.spec.ts
- e2e/tests/room/10-ignoreuser.spec.ts
After merging the developer branch I noticed that I introduced a typescript error when I merged this PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4582. Also, I added a expect and waitFor to 2 tests
[NATIVE-158]
[NATIVE-158]: https://rocketchat.atlassian.net/browse/NATIVE-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] The TS in data_setup and add expect in room and ignoreuser tests

- .github/dependabot.yml
There's no gain on running dependabot daily as the value is based on how frequent we actually take a look at the open PRs.
Let's move it to weekly.
[NATIVE-155]
[NATIVE-155]: https://rocketchat.atlassian.net/browse/NATIVE-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore: Reduce the frequency of dependabot runs to weekly basis

- app/lib/methods/search.ts
Regression from #4527 
Run detox
[NATIVE-163]
[NATIVE-163]: https://rocketchat.atlassian.net/browse/NATIVE-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regression: Remove users already in local database

- app/containers/ActionSheet/ActionSheetContentWithInputAndSubmit/index.tsx
- app/containers/UIKit/DatePicker.tsx
- app/containers/UIKit/Select.tsx
- app/views/CloseLivechatView.tsx
- app/views/RoomInfoEditView/styles.ts
Adds missing border style changes after #4659 and #4657 
[NATIVE-162]
[NATIVE-162]: https://rocketchat.atlassian.net/browse/NATIVE-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [IMPROVE] Add missing borders styles changes

- ios/Podfile.lock
- package.json
- patches/react-native-notifications+4.3.3.patch
- yarn.lock
Updates the lib and applies https://github.com/wix/react-native-notifications/issues/906#issuecomment-1315455583
Related to:
- https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4585
- https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4648
- Receive a push notification
- Tap it and the app should redirect to the message
- (Test base)
- Go to rooms list, send it to background and open it again
- It should not redirect again
- Send it to backgroud
- Receive a push on another room
- It should redirect to the correct message
- (rerun this whole test starting with the app *killed* and with the app *open in background*)
- (Test base)
- Go to another room
- Upload a photo
- (rerun this whole test starting with the app *killed* and with the app *open in background*)
[NATIVE-160] …
> Chore: Bump react-native-notifications to 4.3.3

- app/views/E2EEnterYourPasswordView.tsx
- app/views/E2EHowItWorksView.tsx
- app/views/E2ESaveYourPasswordView.tsx
- app/views/Styles.ts
<table>
<thead>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
[NATIVE-171]
[NATIVE-171]: https://rocketchat.atlassian.net/browse/NATIVE-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [IMPROVE] Standardize padding of E2E screens

- app/containers/MessageActions/index.tsx
- app/containers/message/index.tsx
- app/definitions/IMessage.ts
> [FIX] Check videoConf type

- app/containers/message/index.tsx
- app/containers/message/utils.ts
Fix the username appearing when allowing reactions. 
And about the `message removed`
- On web it’s exhibited the avatar, username, “message removed” and date/time → It may get visually polluted on mobile
- On web, if the first message of the sequence (the normal message) gets deleted, the next message of the sequence gets rendered as the “normal message”
- Before
- After
[TC-289]
[TC-274]: https://rocketchat.atlassian.net/browse/TC-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-289]: https://rocketchat.atlassian.net/browse/TC-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regression: Avatar and Username for Allowed Reactions and for Message Removed

- app/containers/UIKit/VideoConferenceBlock/components/VideoConferenceSkeletonLoading.tsx
> [FIX] Videoconf skeleton border color and height

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.34.0

- app/containers/MessageActions/Header.tsx
- app/containers/MessageActions/index.tsx
- app/views/RoomView/index.tsx
This PR fixes 2 issues following this steps:
- Long press a message
- Tap rightest emoji on the header to open the emoji picker
1. It was calling `addFrequentlyUsed` without any emoji
2. Depending on the device, it would never open the emoji picker
Closes #4734
[NATIVE-201]
[NATIVE-201]: https://rocketchat.atlassian.net/browse/NATIVE-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] Emoji picker not opening in some cases

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.35.0

- ios/RocketChatRN.xcodeproj/project.pbxproj
> Chore: Select different provisioning profile for Experimental app

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> [FIX] Bump version to 4.34.0

- app/definitions/IUpload.ts
- app/lib/database/model/Upload.js
- app/lib/database/model/migrations.js
- app/lib/database/schema/app.js
- app/lib/methods/sendFileMessage.ts
- app/views/RoomView/UploadProgress.tsx
Meanwhile the user is sending a file/image into a thread and the internet or the upload fails, will appear the button to `Try again` the upload. Then when the user press to `Try Again` and complete the upload, the file will be uploaded direct to the main channel, not to the specific thread
Also, I needed to fix a regression here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4756/files#diff-6d3240d130dc615d53b6ce6dc02db19da2b4370cf3a85b8ac24a0485937827bcR66 that was introduced here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4528, because we didn't test with the possibility of `Try Again`
- Upload a file to a thread
- Force to appear the Try Again, maybe activating the airplane mode and deactivating
- Click to Try Again
- The file should be uploaded to the …
> [FIX] Try again to resend a file on a thread

- app/views/RoomsListView/Header/index.tsx
- app/views/RoomsListView/index.tsx
- In Rooms List View
- Click to show the server dropdown
- Then click to search
- The server dropdown should close and enable the search
- Test on tablets as well
https://user-images.githubusercontent.com/47038980/210277378-33f69ccf-c9cb-4748-a66e-175fd4bdb060.mov
https://user-images.githubusercontent.com/47038980/210277324-8eabc8cc-a069-4c54-a126-36c254088088.mov
[TC-78]
[TC-78]: https://rocketchat.atlassian.net/browse/TC-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] Opening search field after server list does not hide server list

- app/views/JitsiMeetView.android.tsx
Use lib `expo-keep-awake` to prevent screen sleep
Closes: #4777
Join a call using jitsi on an android device and keep the screen open for a few minutes.
Jira: [VC-44]
[VC-44]: https://rocketchat.atlassian.net/browse/VC-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regression: Prevent screen from sleeping on Jitsi on Android

- app/views/AuthenticationWebView.tsx
When upgrading a server to 5.4.0 or 5.4.1, the user can't log in with SSO for iOS or Android
Closes https://github.com/RocketChat/Rocket.Chat/issues/27584
[TC-345]
[TC-345]: https://rocketchat.atlassian.net/browse/TC-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] Not Login with SSO after upgrade to version 5.4.0 and 5.4.1

- app/lib/methods/audioFile.ts
Currently some files come with a generic filename or without an extension and these names were causing an error in the loading of audios, this PR puts the name of the files for only the id of the message and corrects the extension error.
As it is not possible to get the file extension via buffer, only mime and iOS needs the correct extension to play the audio correctly, we assume that the default used on the web is mp3 so the default value for when you don't have the extension in the file use the default.
- Send audio between different devices (iOS <--> Android)
- Submit an audio from the web.
- Send an audio from the web and remove the extension from the filename.
Jira: [NATIVE-86]
[NATIVE-86]: https://rocketchat.atlassian.net/browse/NATIVE-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> [FIX] Audio names not being handled properly

- android/app/src/main/AndroidManifest.xml
- app/lib/methods/videoConf.ts
- app/views/RoomMembersView/index.tsx
Fix the error of audio not coming out on bluetooth devices connected to the device.
Closes: #4776
Join a call and try to listen or talk using a bluetooth device like headphones or speakers.
Test on devices above android 12 and also on devices below android 12, two tests in this case.
ANDROID ONLY
Jira: [VC-45]
[VC-45]: https://rocketchat.atlassian.net/browse/VC-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ|
Docs: https://developer.android.com/guide/topics/connectivity/bluetooth/permissions
> Regression: Add bluetooth permissions for Jitsi

- app/views/RoomView/index.tsx
On the last commit of #4801, I fixed some types, but didn't test properly https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4801/commits/e48005dd85310003ac1a2a3cde1f07bc7f29253f#diff-40253dc61ea5785ef8835b324bc382a20c83dc553e23ef6d16e7fc9760cacc21R691
> Regression: App not fetching messages properly after #4801

- package.json
- yarn.lock
Pointing to specific fork commit, so `yarn` can resolve it without having to play with cache: https://github.com/RocketChat/react-native/commit/281140d2e39d66a8e486db397ce0bf5bd0e334fc
If we point to the branch (as we used to), yarn won't identify as a different commit, because we didn't change the `package.json`'s version.
It has pros and cons.
Let's see how it goes and we can change later.
> [FIX] Point to correct RN fork commit

- e2e/README.md
Fix Documentation: Rocket.Chat server guide link
> Docs: Fix Rocket.Chat server guide URL

- ios/RocketChatRN.xcodeproj/project.pbxproj
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4823 broke Official build
> [FIX] Official CI build

- app/containers/RoomItem/index.tsx
- app/containers/RoomItem/useUserStatus.tsx
Fix RoomItem's loading status
The issue was introduced on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4310/files#diff-3c0fc0825d0585349638972b52ccd383f90a3499ed67f1265404974a2ebfbe76L194
Join in the app offline or online to see the correct user status.
Jira: [NATIVE-193]
[NATIVE-193]: https://rocketchat.atlassian.net/browse/NATIVE-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regression: Fix RoomItem's loading status

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.36.0

- app/views/JitsiMeetView.ios.tsx
Add token to jitsi call on iOS
Join a call that has jwt enabled
[VC-78]
[VC-78]: https://rocketchat.atlassian.net/browse/VC-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Regression: Add token to Jitsi call on iOS

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.35.1

- ios/Podfile.lock
- ios/RocketChatRN.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Updates React Native to 0.68.6, pointing to a new branch `0.68.6` on our fork https://github.com/RocketChat/react-native/commits/0.68.6
[NATIVE-268]
[NATIVE-268]: https://rocketchat.atlassian.net/browse/NATIVE-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore: Update React Native to 0.68.6

- app/lib/methods/subscriptions/room.ts
- app/lib/services/restApi.ts
- app/lib/services/sdk.ts
Removes deprecated `${rid}/typing` for servers above 4.0.0.
This PR doesn't implement the full compatibility for `${rid}/user-activity`, so support to threads, uploading and recording is still missing.
- Typing should be working properly on servers before and after 4.0
[NATIVE-269]
[NATIVE-269]: https://rocketchat.atlassian.net/browse/NATIVE-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chore: Remove deprecated typing stream

- android/app/src/main/AndroidManifest.xml
We removed the permissions related to low energy bt and left only the basic permission, like the jitsi app does.
https://github.com/jitsi/jitsi-meet/blob/8fcfd7a3083b60e6714de53d4a8ed6cbea46f165/android/sdk/src/main/AndroidManifest.xml#L7
It was necessary because google complained about some app permissions.
Join a video call and play the audio on a bt device.
> [FIX] Remove some permissions and keep only basic bt permission

- app/containers/RoomTypeIcon/OmnichannelRoomIcon.tsx
- ios/Podfile.lock
- package.json
- yarn.lock
When any omnichannel's app icon (example: facebook, whastsapp, Instagram) is broken, the app crashes because the component provided by the library didn't handle the error, because of this I needed to update the library react-native-svg
- First, you should be an omnichannel agent
- Then, join a WhatsApp chat from the normal queue or search a WhatsApp chat inside the omnichannel queue
https://user-images.githubusercontent.com/47038980/220766600-0dab3656-05a0-4daf-9401-91d0bcac750b.mp4
https://user-images.githubusercontent.com/47038980/221268632-a77b1dbe-2f36-41d8-8f7e-67d4a2458a1f.mp4
[NATIVE-276]
[NATIVE-276]: https://rocketchat.atlassian.net/browse/NATIVE-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] Omnichannel's icon svg fallback when the link returns an error

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.37.0

- app/containers/UserGeneratedContentRules.tsx
As you can see in the screenshots, the text alignment before isn't aligned with the center
[TC-414]
[TC-414]: https://rocketchat.atlassian.net/browse/TC-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] UGC Rules Text align

- app/containers/message/Content.tsx
Stop sending `message.md` prop to markdown if `message.type === e2e`.
`md` would still be encrypted when in reality we should be rendering `msg`.
Possibly related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4183
Tricky to reproduce, but it needs a message encrypted and with `md` block.
| --- | --- |
| ![Screenshot 2023-03-06 at 14 46 14](https://user-images.githubusercontent.com/804994/223190183-1e0800ed-58eb-4ffc-9fc9-022d99da9d04.png)| ![Screenshot 2023-03-06 at 14 46 43](https://user-images.githubusercontent.com/804994/223190242-fdfa9280-3cf0-4532-808c-79b382be1c6e.png)|
[NATIVE-273]
[NATIVE-273]: https://rocketchat.atlassian.net/browse/NATIVE-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX] Message not rendering E2EE data if `md` exists

- app/externalModules.d.ts
- ios/Podfile
- ios/Podfile.lock
- ios/RocketChatRN.xcodeproj/project.pbxproj
- package.json
- yarn.lock
> chore: Update react-native-ui-lib to 7.2.0

- app/containers/SearchBox/SearchBox.test.tsx
Un-skip test in `app/containers/SearchBox/SearchBox.test.tsx` and use the occasion for a light refactor (declaration of `<Render />` component is useless, as it has the exact same behavior as `<Searchbox />`).
#4965 
Run `yarn test app/containers/SearchBox/SearchBox.test.tsx` and see all tests pass:
N/A (test-only update)
_Test-only update_
[N/A] I have added tests that prove my fix is effective or that my feature works (if applicable)
[N/A] I have added necessary documentation (if applicable)
[N/A] Any dependent changes have been merged and published in downstream modules
> test: Unskip SearchBox test (#4965)

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.38.0

- android/app/build.gradle
- app/containers/KeyboardView.tsx
- app/views/NewMessageView/index.tsx
- app/views/RoomsListView/index.tsx
- app/views/SearchMessagesView/index.tsx
- app/views/ThreadMessagesView/index.tsx
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
This reverts commit cf14ebea78ac5c1d52b31dca9c2585c599811e98.
> Revert "fix: scroll the pages New Message, Search for Rooms, Messages and Threads (#4952)"

- android/app/build.gradle
- app/containers/KeyboardView.tsx
- app/views/NewMessageView/index.tsx
- app/views/RoomsListView/index.tsx
- app/views/SearchMessagesView/index.tsx
- app/views/ThreadMessagesView/index.tsx
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Merge 4.37.1 into master

- android/app/src/play/java/chat/rocket/reactnative/ReplyBroadcast.java
App was pointing to `mipmap` res, which doesn't exist anymore.
Pointing to `drawable` res instead.
- Receive a push notification
- Enable airplane mode
- Try to reply to push
- Production is going to crash the app
[NATIVE-306]
[NATIVE-306]: https://rocketchat.atlassian.net/browse/NATIVE-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Android): Wrong icon on push reply fail

- app/views/NewServerView/index.tsx
- e2e/tests/assorted/12-i18n.spec.ts
- e2e/tests/onboarding/01-onboarding.spec.ts
- Removes "Join open" button from NewServerView on Android.
- Removed tests related
> feat(Android): Remove Open workspace from onboarding

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.39.0

- app/definitions/rest/v1/channels.ts
- app/lib/services/restApi.ts
- e2e/tests/team/03-moveconvert.spec.ts
- Create a new public channel
- Go to Room Info
- Tap on “Convert to channel”
- Go to Room Info Edit
- Change the room to Private
- Try to convert it again
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/ac26e873-9568-484f-96be-b750e63a06f8
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/253c1b18-b9c3-44f6-833c-b84539a0c4a3
[TC-562]
[TC-562]: https://rocketchat.atlassian.net/browse/TC-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: conversion of public channel into team

- android/app/build.gradle
- app/containers/UIKit/VideoConferenceBlock/components/StartACallActionSheet.tsx
- app/definitions/ISubscription.ts
- app/lib/database/model/Subscription.js
- app/lib/database/model/migrations.js
- app/lib/database/schema/app.js
- app/lib/database/utils.test.ts
- app/lib/database/utils.ts
- app/lib/hooks/useSnaps.ts
- app/lib/hooks/useVideoConf.tsx
- app/lib/methods/helpers/getRoomIdFromJitsiCall.test.ts
- app/lib/methods/helpers/getRoomIdFromJitsiCall.ts
- app/lib/methods/helpers/mergeSubscriptionsRooms.ts
- app/lib/methods/search.ts
- app/views/AdminPanelView/index.tsx
- app/views/JitsiMeetView.tsx
- e2e/helpers/app.ts
- e2e/tests/room/01-createroom.spec.ts
- e2e/tests/room/02-room.spec.ts
- ios/Podfile.lock
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
- patches/react-native-webview+11.26.1.patch
- yarn.lock
> Merge 4.39.0 into master

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> Bump version to 4.40.0

- package.json
If you change any file that does not have a test for it, it returns this error:
This fix fixes that error:
Jira: [NATIVE-353]
[NATIVE-353]: https://rocketchat.atlassian.net/browse/NATIVE-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add --passWithNoTests to lint-staged

- app/views/UserNotificationPreferencesView/ListPicker.tsx
- app/views/UserNotificationPreferencesView/index.tsx
> After tapping the icon in the upper right corner of the Profile screen, there is a Notifications setting item that appears by tapping Notifications, but changes are not reflected.
>
> If you make changes and then reopen the Notification Settings screen, it will revert back to the original settings.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5137
- Go to Profile View
- Tap the preferences button (in the top right corner)
- Tap Notifications
- Change any notification
- Tap the Back button
- Tap Notifications again
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/14801d86-4b62-4a4a-87ef-7f4117b8d7ae
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/d2039e8c-8a47-4834-980c-5e0a856aa99e
[SUP-268]
[SUP-268]: …
> fix: user notification preference state not reflecting the real state

- app/containers/StatusBar.tsx
During the PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5132 I introduced the `StatusBarRN.setBackgroundColor(backgroundColor ?? colors.headerBackground);` and it pop up an error on the console alerting the setBackgroundColor is only for android.
This PR avoids showing this error.
[TC-854]
[TC-854]: https://rocketchat.atlassian.net/browse/TC-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: conditional to setBackgroundColor only for Android

- app/containers/UIKit/MultiSelect/Chips.tsx
- app/containers/UIKit/MultiSelect/Items.tsx
- app/containers/UIKit/MultiSelect/MultiSelectContent.tsx
- app/containers/UIKit/MultiSelect/index.tsx
- app/containers/UIKit/UiKitMessage.stories.tsx
- app/containers/UIKit/index.tsx
- app/views/CreateDiscussionView/interfaces.ts
- app/views/LivechatEditView.tsx
- app/views/RoomInfoEditView/index.tsx
- e2e/tests/room/04-discussion.spec.ts
This bug happens when creating a discussion and the user wants to search for other users, as you can see ate the screenshots. Also, this bug was noticed during the QA of https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5110. We can merge both separately because this PR doesn't introduce any bug on the #5110.
Also, we must test: Create a discussion and select the channel and users; Edit the System Messages on the rooms; Edit the tags at the Omnichannel Edit View; 
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/20b7835f-d0b0-4bff-9ad1-9d5a2726a4be
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/4dfe21ef-6b95-412b-843a-9127553bddc7
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/ad0ee9de-111b-4b75-8a3e-11b5f057ecfc …
> fix: selected items on a multiselect change when do a new search

- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/MessageComposer.tsx
- app/containers/MessageComposer/__snapshots__/MessageComposer.test.tsx.snap
- app/containers/MessageComposer/components/Buttons/MicOrSendButton.tsx
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/context.ts
- app/containers/MessageComposer/interfaces.ts
- app/containers/message/Message.tsx
- app/containers/message/index.tsx
- app/containers/message/interfaces.ts
- app/views/RoomView/List/index.tsx
- app/views/RoomView/index.tsx
Mostly copy pasted from https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5115
> feat: new composer edit

- app/containers/markdown/previewFormatText.ts
this issue was introduced here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5064
To test this edge case properly you can go to this message https://open.rocket.chat/channel/react-native?msg=qhCSkpi6d97SXFKd7, then you should do a long press on the message, then tap "Quote". Without this PR, you will notice the screen will stuck for a bit while it's rendering, but this shouldn't occur, the expectation is to render smoothly.
To test properly this edge case you can go to this message https://open.rocket.chat/channel/react-native?msg=qhCSkpi6d97SXFKd7, then you should do a long press on the message, then tap "Quote". Without this PR, you will notice the screen will stuck for a bit while it's rendering, but this shouldn't occur, the expect is to render smoothly. …
> regression: preview format text for edge cases

- app/containers/MessageActions/index.tsx
- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/MessageComposer.tsx
- app/containers/MessageComposer/__snapshots__/MessageComposer.test.tsx.snap
- app/containers/MessageComposer/components/Buttons/MicOrSendButton.tsx
- app/containers/MessageComposer/components/CancelEdit.tsx
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/components/Quotes/Quotes.tsx
- app/containers/MessageComposer/context.tsx
- app/containers/MessageComposer/emitter.ts
- app/containers/message/index.tsx
- app/lib/services/restApi.ts
- app/views/RoomView/List/index.tsx
- app/views/RoomView/ReactionPicker.tsx
- app/views/RoomView/context.ts
- app/views/RoomView/index.tsx
- jest.setup.js
> chore: increase action usage (edit, react)

- __mocks__/react-native-mmkv-storage.js
- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/__snapshots__/MessageComposer.test.tsx.snap
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/components/Toolbar/Default.tsx
- app/containers/MessageComposer/components/Toolbar/EmojiKeyboard.tsx
- app/containers/MessageComposer/components/Toolbar/Markdown.tsx
- app/containers/MessageComposer/components/Toolbar/Toolbar.tsx
- app/containers/MessageComposer/constants.ts
- app/containers/MessageComposer/context.tsx
- app/containers/MessageComposer/emitter.ts
- app/containers/MessageComposer/interfaces.ts
- app/views/RoomView/context.ts
> feat: add markdown to new composer

- app/i18n/locales/en.json
- app/i18n/locales/pt-BR.json
- app/views/RoomActionsView/index.tsx
- app/views/TeamChannelsView.tsx
Update channel teams action label
Jira: [TC-791]
[TC-791]: https://rocketchat.atlassian.net/browse/TC-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update channel teams action label

- app/lib/constants/colors.ts
Updates the toast color when the theme is dark, using shade 4 that is already being used in other things in the dark theme.
- Update something in your profile when the theme is dark
Before:
After:
Jira: [TC-910]
[TC-910]: https://rocketchat.atlassian.net/browse/TC-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update toast color in dark-theme

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.41.0

- .circleci/config.yml
> chore: Set M1 Medium on CircleCI

- .circleci/config.yml
> chore: Set machine resource for Android E2E tests

- __tests__/containers/UIKit/__snapshots__/UiKitModal.stories.storyshot
- app/containers/UIKit/UiKitMessage.stories.tsx
- app/containers/UIKit/UiKitModal.stories.tsx
- app/containers/UIKit/index.tsx
That PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5145 introduced the regression that this PR is fixing. Also, added some tests inside the storyshot.
- Logged with an account able to request praise for Koko
- You should type `/koko praise` and you should be able to select the users
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/87310ea6-c98f-4aad-b0df-66ae98f7fcf8
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/373a1b88-4d1f-4cb1-9e68-f9b6bb4fb9b0
[TC-943]
[TC-943]: https://rocketchat.atlassian.net/browse/TC-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: the value of the uikit's block uikit could be undefined

- app/lib/methods/getSettings.ts
- app/views/RoomsListView/Header/Header.tsx
There is a limitation in the code where if the mobile client needs more than a page full of settings (determined by default paging settings) - only the first page will be retrieved and some settings will be left out.
This PR iterates over the responses if more pages are available, and collects all results to provide a complete settings picture to the client.
closes #5218
Add more settings to `app\lib\constants\defaultSettings.ts` such that their count is much greater than the default page length of queries. Use a network inspector to confirm that only the first page of settings is requested.
> feat: properly fetch all settings from server

- app/containers/MessageActions/index.tsx
- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/MessageComposer.tsx
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/components/SendThreadToChannel.tsx
- app/containers/MessageComposer/components/index.ts
- app/containers/MessageComposer/context.tsx
- app/containers/message/index.tsx
- app/i18n/locales/en.json
- app/stacks/types.ts
- app/views/RoomView/List/hooks/useMessages.ts
- app/views/RoomView/context.ts
- app/views/RoomView/index.tsx
> feat: new composer thread

- app/containers/ActionSheet/ActionSheet.tsx
- app/containers/ActionSheet/BottomSheetContent.tsx
- app/containers/ActionSheet/Handle.tsx
- app/containers/ActionSheet/Provider.tsx
- app/containers/ActionSheet/styles.ts
- app/containers/MessageActions/Header.tsx
- app/containers/MessageActions/index.tsx
- app/lib/hooks/useVideoConf/StartACallActionSheet.tsx
- app/views/RoomView/index.tsx
- e2e/tests/room/02-room.spec.ts
- e2e/tests/room/05-threads.spec.ts
#5202 added a few regressions and this PR should fix them while improving a couple of things.
- added snaps to message actions to make it possible to scroll through items
- added max 80% height cap to prevent mistakes on dynamic version
- if it ever gets to this, the dynamic content is going to be cut, but it's better than fitting the whole screen (it's a valid escape hatch imo)
- removed unnecessary landscape code
- improved safe area
- Message long press
- Add reaction (play with horizontal and vertical scroll)
- Open reactions list (play with horizontal and vertical scroll)
- Try action sheets on tablet
[NATIVE-405]
[NATIVE-405]: https://rocketchat.atlassian.net/browse/NATIVE-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: dynamic action sheet taking whole screen

- .circleci/config.yml
- ios/Podfile.lock
- ios/RocketChatRN.xcodeproj/project.pbxproj
- package.json
- patches/react-native-fast-image+8.5.12.patch
- Need to test everything related to images on iOS
[NATIVE-407]
[NATIVE-407]: https://rocketchat.atlassian.net/browse/NATIVE-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Update libwebp to 1.3.2

- yarn.lock
> chore: Fix CI yarn cache not working

- app/lib/methods/checkSupportedVersions.test.ts
- app/lib/methods/checkSupportedVersions.ts
- app/lib/methods/getServerInfo.ts
- app/sagas/login.js
[NBJ-250]
[NBJ-250]: https://rocketchat.atlassian.net/browse/NBJ-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: some details on supported versions

- app/definitions/IServer.ts
- app/lib/database/model/servers/Server.js
- app/lib/database/model/servers/migrations.js
- app/lib/database/schema/servers.js
- app/lib/methods/getServerInfo.ts
- app/sagas/selectServer.ts
We were fetching supported versions from cloud every time a login was dispatched, so we were fetching too often.
This PR adds `server.supportedVersionsUpdatedAt`, which is updated every time `server.supportedVersions` is changed.
If `getServerInfo` needs to make a request to cloud again, it checks that column first and uses cached supported versions instead of going to cloud again in less than 12h.
> feat: Cache supported versions timestamp to fetch from cloud once every 12h

- app/sagas/deepLinking.js
> fix: fixes the import of the serverInfo function

- app/lib/methods/checkSupportedVersions.ts
- app/views/SidebarView/index.tsx
> fix: minor supported versions details

- app/sagas/videoConf.ts
Currently, if a person receives a call while the app is in the background, click on the push button and open the app, they will not see the incoming call indicator.
This PR solves that.
If the app is closed and it opens via push, it works normally.
resolve: #5307
Put the app in the background, receive a call and click on the received push.
Jira: [VC-154]
[VC-154]: https://rocketchat.atlassian.net/browse/VC-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: check if the app is on foreground before setting call status

- app/actions/actionsTypes.ts
- app/actions/troubleshootingNotification.ts
- app/definitions/rest/v1/index.ts
- app/definitions/rest/v1/push.ts
- app/i18n/locales/en.json
- app/i18n/locales/pt-BR.json
- app/lib/methods/getPermissions.ts
- app/lib/services/restApi.ts
- app/reducers/troubleshootingNotification.test.ts
- app/reducers/troubleshootingNotification.ts
- app/sagas/login.js
- app/sagas/troubleshootingNotification.ts
- app/views/PushTroubleshootView/index.tsx
- app/views/RoomsListView/index.tsx
This PR needs these others PRs from Rocket.Chat to work properly:
https://github.com/RocketChat/Rocket.Chat/pull/30745
https://github.com/RocketChat/Rocket.Chat/pull/30868
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/307f9651-239b-414d-baa0-6f0358cf01de
[TC-925]
[TC-925]: https://rocketchat.atlassian.net/browse/TC-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: test push notification

- android/app/build.gradle
- app/lib/methods/getServerInfo.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
Airgapped workspaces might not have allowed requests to https://releases.rocket.chat/v2/server/supportedVersions on firewall.
We don't want to block them from login. Instead we want to catch exceptions and use app's built-in supported versions.
[NATIVE-419]
[NATIVE-419]: https://rocketchat.atlassian.net/browse/NATIVE-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Catch cloud request errors

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.43.0

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.44.0

- android/app/src/main/AndroidManifest.xml
- Invite link: https://go.rocket.chat/invite?host=open.rocket.chat&path=invite%2FE2jyq6
- Room: https://go.rocket.chat/room?host=open.rocket.chat&path=group/mobile-test
- Auth: https://go.rocket.chat/auth?host=mobile.rocket.chat
- Other: https://go.rocket.chat/i/docker-compose.yml (opens browser)
- Everything again, but using `rocketchat://` and scaped adb
* Example: `adb shell am start -a android.intent.action.VIEW -d "rocketchat://room\?host\=open.rocket.chat\&path\=group/mobile-test"`
> fix(Android): Deep links not working on Android 12

- app/lib/hooks/useVideoConf/index.tsx
Currently, the first time the user opens the app and tries to make a video call, the app requests camera permissions.
However, after the user accepts the permissions, the app crashes, this PR solves this problem.
- Install the app from scratch
- Try to init a video conference 
- Accept the permissions to use camera and bt (if is necessary)
Jira: [VC-168]
[VC-168]: https://rocketchat.atlassian.net/browse/VC-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: handle camera permission crash

- android/app/src/play/java/chat/rocket/reactnative/CustomPushNotification.java
> fix: add type checking on notificationType

- app/lib/methods/helpers/formatAttachmentUrl.ts
- app/lib/methods/helpers/getAvatarUrl.ts
The problem here is with the cdnPrefix, we took in consideration only the cdn’s with protocol, but looking at this documentation: https://docs.rocket.chat/setup-and-configure/advanced-workspace-management/cdn  The cdn could be a single string, as the first example in the table, and we don’t have a fallback for this case.
Value | Example Url for Asset
-- | --
cdn | /cdn/example-asset.js
[TC-1042]
[TC-1042]: https://rocketchat.atlassian.net/browse/TC-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: handle cdnPrefix without protocol

- app/containers/DirectoryItem/index.tsx
> fix: made the description of channels in directory same as lastmessage

- app/containers/markdown/AtMention.tsx
This PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5293 introduced the feature to navigate to the user's own profile from: avatar, username. But, it was missing navigate from a mention. 
For older servers, when the user tap on the mention of himself, the user info shows a different user (Before n. 1). For latest servers, the user info shows nothing (Before n. 2).
- Mention yourself in any channel
- Tap on the mention
- This should also work when other user mentions you, and you tap on the mention
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/5b3baa3b-9133-4c30-98d9-ad2182d16e23
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/47038980/040758ca-1db8-4095-a87f-cd9d9f1e7106
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/4703898 …
> fix: navigate to own profile from mention

- README.md
Updated readme to fix the broken link of blog and removed all icons from top.
closes #5421 and closes #5187
Go to README.md
Before
After
> chore: Removed header icons and update blog link

- app/i18n/index.ts
Adding the Hungarian Language
closes #5415 
Go to settings and check languages.
> Feat: Adding Hungarian language

- app/lib/methods/checkSupportedVersions.ts
> fix: supported version expiration only working for exceptions

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Set version to 4.44.1

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.44.2

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.44.2 into single-server

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.44.2 into master

- android/app/build.gradle
- app/lib/methods/handleMediaDownload.test.ts
- app/lib/methods/handleMediaDownload.ts
When the user uses the app tenor or giphy to send a gif, the method `getFilename` receives only `url and type`, instead of `title, url, type and mimetype`. For example: 
```
{
title: undefined,
url: https://media4.giphy.com/media/bGtO3RlAPHkeQ/giphy.gif,
type: image,
mimetype: undefined
}
```
And we considered that when there isn't the mimetype passed with the file, we should consider the default types, but for this case, the apps tenor and giphy send the extension at the final of url. Then, we are checking if there is the extension `gif` on the end of the url, then use it as extension.
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5288
- Send a gif using the app tenor or giphy
- After download the gif locally and open the attachment view you should be able to see …
> fix: download gif files

- app/views/ShareView/Header.tsx
The `CustomIcon` is experiencing display issues, potentially due to insufficient layout space or misconfigured styles, leading to the icon being partially cut off in the rendered view.
Fixes #5469 
1. Go to Chats
2. Share files
> fix: customIcon styling

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.46.0

- app/lib/notifications/videoConf/backgroundNotificationHandler.ts
The ongoing tag does not work on all devices.
Related: https://github.com/invertase/notifee/issues/674
> chore: add no clear flag to video conf android notification

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.47.0

- app/stacks/MasterDetailStack/index.tsx
> fix: room actions header not using i18n

- app/sagas/selectServer.ts
[NATIVE-481]
[NATIVE-481]: https://rocketchat.atlassian.net/browse/NATIVE-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Disconnect from server when on expired support window screen

- android/app/build.gradle
- app/containers/SupportedVersions/SupportedVersionsExpired.tsx
- app/definitions/IServer.ts
- app/i18n/locales/en.json
- app/i18n/locales/pt-BR.json
- app/sagas/selectServer.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.46.1 into master

- android/app/build.gradle
- app/containers/SupportedVersions/SupportedVersionsExpired.tsx
- app/definitions/IServer.ts
- app/i18n/locales/en.json
- app/i18n/locales/pt-BR.json
- app/sagas/selectServer.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.46.1 into single-server

- app/views/Styles.ts
using the `alignSelf: 'stretch'` force the text to flex lines to take up the remaining space.
Send a gimme to a room and return to the screen where it shows all rooms, the gimmer should be rendered perfectly.
Only Android 13 and up.
Before:
After:
Jira: [NATIVE-495]
[NATIVE-495]: https://rocketchat.atlassian.net/browse/NATIVE-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add alignSelf style for Android to prevent text from getting cut off

- app/views/RoomView/index.tsx
We decided that we will not support these changes of actions or do several actions at the same time.
Jira: [NATIVE-476]
[NATIVE-476]: https://rocketchat.atlassian.net/browse/NATIVE-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: remove todo's related to actions

- app/views/LoginView/handleLoginErrors.ts
Jira: [CORE-127]
[CORE-127]: https://rocketchat.atlassian.net/browse/CORE-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: validate that the login error value is actually a string

- app/lib/methods/updateMessages.ts
> fix: `message.md` not getting cleaned up correctly

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.48.0

- app/views/ChangeAvatarView/index.tsx
Fixes the app crashing when clicking the upload image button
- Click upload image on the avatar change screen
Jira: [CORE-206]
[CORE-206]: https://rocketchat.atlassian.net/browse/CORE-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: use correct parameters on upload image on profile view

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Set version to 4.47.1

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Set version to 4.47.2

- app/views/RoomInfoView/components/RoomInfoViewTitle.tsx
closes #5632 
https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/61021881/81caa427-d4d5-4212-91ca-cdcfddac272c
> feat: copy username on long press in user info screen

- app/i18n/locales/en.json
- app/i18n/locales/pt-BR.json
- app/views/DefaultBrowserView/index.tsx
Currently on iOS the system default option is labeled Safari, however this does not reflect reality, given that the system default can be any browser, and as we do not have access to which browser is the system default, the update of the label is necessary to avoid misunderstandings.
Note: Safari does not have a deeplink.
See Apple's Documentation: https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html
Settings > Default browser
After:
Before:
Jira: [CORE-255]
[CORE-255]: https://rocketchat.atlassian.net/browse/CORE-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: change default browser label

- app/lib/encryption/encryption.ts
- app/lib/methods/sendFileMessage.ts
[E2EE-27]
[E2EE-27]: https://rocketchat.atlassian.net/browse/E2EE-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Backwards compatibility on file upload

- app/containers/MessageComposer/components/RecordAudio/RecordAudio.tsx
- app/containers/message/Attachments.tsx
- app/containers/message/index.tsx
- app/definitions/IUpload.ts
- app/lib/encryption/encryption.ts
- app/lib/encryption/room.ts
- app/lib/methods/sendFileMessage.ts
- app/views/CreateChannelView/RoomSettings/SwitchItemEncrypted.test.tsx
- app/views/ShareView/index.tsx
> chore: Revert encrypted file description

- ios/PrivacyInfo.xcprivacy
- ios/RocketChatRN.xcodeproj/project.pbxproj
Create the new PrivacyInfo file to follow the new apple rules.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
Jira: [NATIVE-517]
[NATIVE-517]: https://rocketchat.atlassian.net/browse/NATIVE-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add ios privacy info

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.50.0

- app/views/ShareView/index.tsx
resolve: #5695
Jira: [CORE-480]
[CORE-480]: https://rocketchat.atlassian.net/browse/CORE-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: fix the threadId logic

- app/lib/methods/helpers/log/events.ts
- app/sagas/login.js
> chore: Log event of server/token logout to help tracking bugs

- app/lib/methods/subscriptions/room.ts
We are reading for every chunk of messages received, but we're not updating `subscription.lastOpen`, which is the value used as the "from date" to fetch new messages next time the room is opened.
> feat: Read messages on room close to prevent fetching already seen messages

- app/lib/services/getServerTimeSync.ts
resolve: #5694
Jira: [SUP-587]
[SUP-587]: https://rocketchat.atlassian.net/browse/SUP-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: fix getServerTimeSync return

- app/containers/Toast.tsx
- app/views/Styles.ts
[NATIVE-578]
[NATIVE-578]: https://rocketchat.atlassian.net/browse/NATIVE-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: resolve circular dependency in sharedStyles import

- app/lib/methods/subscriptions/room.ts
- app/lib/methods/updateLastOpen.ts
related: #5723
Jira: [NATIVE-577]
[NATIVE-577]: https://rocketchat.atlassian.net/browse/NATIVE-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: add updateLastOpen function to update the last open date of a subscription

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- app/containers/Toast.tsx
- app/lib/methods/subscriptions/room.ts
- app/lib/methods/updateLastOpen.ts
- app/views/Styles.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.49.2 into single-server

- ios/Podfile.lock
- package.json
- patches/react-native-notifications+4.3.5.patch
- yarn.lock
update react-native-notifications lib + apply patch
resolve: #5682
Run the app pointing to the single server branch and test receiving a push (Android)
Jira: [CORE-521]
[CORE-521]: https://rocketchat.atlassian.net/browse/CORE-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: corrects crash when opening android notification

- app/containers/markdown/new/Bold.tsx
- app/containers/markdown/new/Italic.tsx
- app/containers/markdown/new/Link.tsx
- app/containers/markdown/new/Strike.tsx
- app/containers/markdown/new/components.ts
- app/containers/message/Attachments.tsx
- app/containers/message/Reply.tsx
- app/containers/message/components.ts
- app/lib/constants/links.ts
- app/lib/database/index.ts
- app/lib/methods/helpers/layoutAnimation.ts
- app/lib/methods/helpers/log/index.ts
Fixed require cycle logged on console.
[NATIVE-102]
[NATIVE-102]: https://rocketchat.atlassian.net/browse/NATIVE-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: fix require cycle

- README.md
> chore: Update README docs link

- ios/Podfile.lock
- ios/RocketChatRN.xcodeproj/project.pbxproj
- package.json
- patches/react-native-device-info+11.1.0.patch
- yarn.lock
[NATIVE-590]
[NATIVE-590]: https://rocketchat.atlassian.net/browse/NATIVE-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Update react-native-device-info

- app/views/SelectListView.tsx
Before:
After:
Jira: [NATIVE-591]
[NATIVE-591]: https://rocketchat.atlassian.net/browse/NATIVE-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: correct the message label on SelectListView

- app/containers/message/Components/Attachments/Image.tsx
- app/lib/methods/sendFileMessage/sendFileMessageV2.ts
- app/views/RoomView/List/hooks/useMessages.ts
> chore: Cleanup logs

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.50.1

- README.md
> fix(docs): Update minimum iOS supported version on README

- README.md
- android/app/build.gradle
- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/constants.ts
- app/containers/message/Components/Attachments/Image.tsx
- app/lib/methods/helpers/fileDownload.ts
- app/lib/methods/sendFileMessage/sendFileMessageV2.ts
- app/views/RoomView/List/hooks/useMessages.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.50.1 into master

- README.md
- android/app/build.gradle
- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/constants.ts
- app/containers/message/Components/Attachments/Image.tsx
- app/lib/methods/helpers/fileDownload.ts
- app/lib/methods/sendFileMessage/sendFileMessageV2.ts
- app/views/RoomView/List/hooks/useMessages.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.50.1 into single-server

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.51.0

- app/stacks/OutsideStack.tsx
* fix: corrects hanging on white screen at startup
> fix: corrects hanging on white screen at startup

- app/containers/RoomHeader/RoomHeader.tsx
- app/views/RoomsListView/Header/Header.tsx
- app/views/ShareView/Header.tsx
Jira: [MA-65]
[MA-65]: https://rocketchat.atlassian.net/browse/MA-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: set accessibilityLabel and accessibilityRole on Headers

- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/hooks/useAutoSaveDraft.ts
- app/containers/MessageComposer/interfaces.ts
- Type `ABC` on composer
- Tap send while tapping back on navigator as fast as possible
- Enter the room again
- Message was sent, but `ABC` is as draft
[SUP-635]
[SUP-635]: https://rocketchat.atlassian.net/browse/SUP-635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: draft keeping content incorrectly sometimes

- app/containers/message/Components/Attachments/CollapsibleQuote/CollapsibleQuote.test.tsx
- app/containers/message/Components/Attachments/CollapsibleQuote/index.tsx
[SUP-647]
[SUP-647]: https://rocketchat.atlassian.net/browse/SUP-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add text to collapsible quote

- app/lib/encryption/utils.ts
[SUP-648]
[SUP-648]: https://rocketchat.atlassian.net/browse/SUP-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Room encrypted with E2E_Enabled setting disabled

- app/lib/constants/defaultSettings.ts
- app/lib/encryption/encryption.ts
Related to https://github.com/RocketChat/Rocket.Chat/pull/33003
[NATIVE-617]
[NATIVE-617]: https://rocketchat.atlassian.net/browse/NATIVE-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Setting to enable file encryption

- app/containers/MessageComposer/__snapshots__/MessageComposer.test.tsx.snap
- app/containers/markdown/Preview.tsx
- app/containers/markdown/styles.ts
[NATIVE-620]
[NATIVE-620]: https://rocketchat.atlassian.net/browse/NATIVE-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Adjust markdown line height

- app/lib/encryption/encryption.ts
[NATIVE-623]
[NATIVE-623]: https://rocketchat.atlassian.net/browse/NATIVE-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> regression: Fix E2E_Enable_Encrypt_Files backwards compatibility

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.52.0

- app/containers/message/hooks/useMediaAutoDownload.tsx
- app/containers/message/index.tsx
- app/lib/methods/handleMediaDownload.ts
- app/lib/methods/updateMessages.ts
- app/views/RoomView/LoadMore/index.tsx
- app/views/RoomView/index.tsx
If last message is an attachment, sometimes it can start rendered as `to-download`, but it's actually downloading, or flicker like in the video below
https://github.com/user-attachments/assets/af8d36ab-014b-4e94-ba88-ebc6bdf3b8ba
https://github.com/user-attachments/assets/84920fff-aef4-4f43-a57d-3945eb6e797b
Current Image component can still be improved and the plan is to migrate to expo-image soon.
Sometimes the component is just going to display a white rectangle before it actually loads it correctly.
[NATIVE-621]
[NATIVE-621]: https://rocketchat.atlassian.net/browse/NATIVE-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: last message preview flickering

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.53.0

- app/index.tsx
The OAuth using Google was not workin. I added a conditional rule to the return of the type parameter in the function parseDeepLinking to make it function normally again.
https://rocketchat.atlassian.net/browse/NATIVE-658
- Try to sign in using Google;
https://github.com/user-attachments/assets/e2bf0039-9f7e-415f-b753-adce038759ef
https://github.com/user-attachments/assets/1d68dc76-bb31-4b5b-b56d-0bafcb1d11c3
> fix: Google OAuth issue

- app/containers/MessageComposer/components/ComposerInput.tsx
https://github.com/user-attachments/assets/2cf68fd9-f050-4497-aa4c-1bdbe679d967
https://github.com/user-attachments/assets/89785d24-f8d4-44a8-abec-d966e5ea9a91
[NATIVE-659]
[NATIVE-659]: https://rocketchat.atlassian.net/browse/NATIVE-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Action sheet not closing on message edit

- app/containers/Button/index.tsx
- app/lib/constants/colors.ts
Adjust the text color of the Action Sheet item.
Regression of this PR: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5869
On this PR was changed the fontDisabled color on light theme:
https://rocketchat.atlassian.net/browse/NATIVE-656
- Go to RoomViiew;
- Long Press one message;
- scroll down until Pin option;
- the color should be #CBCED1;
> fix: created color buttonFontPrimary on light theme

- android/app/build.gradle
- app/containers/Button/index.tsx
- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageSeparator.tsx
- app/containers/message/Message.stories.tsx
- app/containers/message/index.tsx
- app/index.tsx
- app/lib/constants/colors.ts
- app/lib/methods/helpers/formatAttachmentUrl.ts
- app/views/RoomView/List/index.tsx
- app/views/RoomView/LoadMore/index.tsx
- app/views/RoomView/index.tsx
- app/views/Styles.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.53.0 into master

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.54.0

- app/containers/markdown/styles.ts
The customEmoji is not aligned with the top of the line on Android because its height and width were set to 20.
https://rocketchat.atlassian.net/browse/NATIVE-671
- open the app;
- go to a room;
- send this test message: 'all What are you planning to work on during this week? :thread-it:
Please make sure to be specific and bring some details.'
> fix: custom emoji is not aligned on new line height

- app/definitions/rest/v1/omnichannel.ts
- app/lib/services/restApi.ts
https://github.com/RocketChat/Rocket.Chat/pull/26789
> feat: support endpoint "livechat/room.saveInfo"

- app/definitions/ISubscription.ts
- app/lib/encryption/encryption.ts
- app/lib/encryption/room.ts
- app/lib/methods/helpers/mergeSubscriptionsRooms.ts
- app/sagas/selectServer.ts
https://github.com/RocketChat/Rocket.Chat/pull/33615
[E2EE2-84]
[E2EE2-84]: https://rocketchat.atlassian.net/browse/E2EE2-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Implement KeyID Generation Logic

- app/containers/message/Urls.tsx
MessagesView is breaking when you open pinned Messages on specific room menu.
https://rocketchat.atlassian.net/browse/NATIVE-678
Before:
https://github.com/user-attachments/assets/fa382fcc-6366-4465-be0b-ff8e1a890a40
After:
https://github.com/user-attachments/assets/1ce86907-36e7-49f9-acf5-a8cb7f777510
> fix: pinned menu returns a blank screen for certain rooms.

- app/lib/methods/getPermissions.ts
- app/stacks/types.ts
- app/views/AddChannelTeamView.tsx
- app/views/AddExistingChannelView/index.tsx
- app/views/RoomActionsView/index.tsx
- app/views/TeamChannelsView.tsx
https://github.com/RocketChat/Rocket.Chat/pull/31117
[NATIVE-681]
[NATIVE-681]: https://rocketchat.atlassian.net/browse/NATIVE-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add new permissions to teams

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.55.0

- app/lib/methods/logout.ts
- app/sagas/login.js
On https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5815 we added react-native-keychain to the app and we started calling `Keychain.setInternetCredentials` on login.
That call is failing on some edge cases on Android, but the PR fixes an issue on iOS specifically.
This PR removes that call from Android.
[NATIVE-680]
[NATIVE-680]: https://rocketchat.atlassian.net/browse/NATIVE-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Android): unable to login due to encryption keychain failure

- app/lib/methods/subscriptions/rooms.ts
[NATIVE-693]
[NATIVE-693]: https://rocketchat.atlassian.net/browse/NATIVE-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: undefined emails on rooms stream

- app/lib/methods/parseSettings.ts
[NATIVE-698]
[NATIVE-698]: https://rocketchat.atlassian.net/browse/NATIVE-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add extra check on settings types to guarantee settings are fetched correctly

- app/stacks/MasterDetailStack/index.tsx
We are getting isMasterDetail from Redux, it's no longer necessary to set it in ModalStack.Screen options.
To fix the issue, I removed this line because we're now getting isMasterDetail from Redux.
https://rocketchat.atlassian.net/browse/NATIVE-699
- Open the app (in iPad);
- Click on directory button;
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/0bbe9491-daea-4169-b05e-097412f02f1c) | ![After](https://github.com/user-attachments/assets/7ba612f3-8a47-481f-a040-b72b95e65d57) |
> fix: Resolve crash in Directory on tablets

- app/definitions/rest/v1/omnichannel.ts
- app/ee/omnichannel/lib/index.ts
- app/ee/omnichannel/sagas/inquiry.js
Updated the API to use livechat/inquiries.queuedForUser endpoint (version 7.0+).
https://rocketchat.atlassian.net/browse/NATIVE-691
> chore: updated deprecated endpoint livechat/inquiries.queued

- app/containers/message/Components/Attachments/Video.tsx
"Revert PR [#5893](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5893) due to performance issues and crashes on Android. We'll address these issues and reintroduce the Image Thumbnail feature once it's fully functional."
https://rocketchat.atlassian.net/browse/NATIVE-705
> regression: remove video thumbnails

- .storybook/preview.tsx
- app/actions/server.ts
- app/reducers/server.test.ts
- app/sagas/deepLinking.js
- app/sagas/init.js
- app/sagas/login.js
- app/sagas/selectServer.ts
- app/views/NewServerView/index.tsx
Follow-up from https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5961
Enforce server version param on selectServerRequest.
It's going to fix some race conditions that may happen while selectServerRequest is running and other events were also triggered in the meantime.
[NATIVE-707]
[NATIVE-707]: https://rocketchat.atlassian.net/browse/NATIVE-707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: enforce server version on server select

- app/lib/encryption/room.ts
- app/lib/methods/loadThreadMessages.ts
- app/sagas/deepLinking.js
- app/sagas/login.js
- app/sagas/videoConf.ts
- app/views/ChangeAvatarView/AvatarSuggestion.tsx
- app/views/DirectoryView/index.tsx
- app/views/LivechatEditView.tsx
- app/views/RoomActionsView/index.tsx
- app/views/RoomView/RightButtons.tsx
- app/views/RoomView/index.tsx
- app/views/RoomView/services/getMessages.ts
[NATIVE-709]
[NATIVE-709]: https://rocketchat.atlassian.net/browse/NATIVE-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Handle some promise rejections

- app/containers/message/Urls.tsx
The issue occurred only on Android. I added a fallback to FastImage to make it work on Android. This is a temporary solution, and an issue has already been opened for it: https://github.com/DylanVann/react-native-fast-image/issues/974
https://rocketchat.atlassian.net/browse/NATIVE-677
- Send links to room (the link of this issue for example);
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/36a1af29-b454-4de6-a583-ba5bd266b599) | ![After](https://github.com/user-attachments/assets/439739de-1142-4e8b-982c-e86e2902c2e5) |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/880ba11b-5d89-4c8a-aba1-f3d138368618) | ![After](https://github.com/user-attachments/assets/8818bf10-06cf-4576-a75f-831c0 …
> fix: URL missing image preview

- app/views/TeamChannelsView.tsx
the regression was introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5943. The removal of the 'delete-c' permission from mapStateToProps caused the delete option in the TeamChannelsView action sheet to be hidden.
https://rocketchat.atlassian.net/browse/NATIVE-706
> regression: missing delete channel permission on team channels

- app/views/NewServerView/index.tsx
Padding correction on add workspace.
https://rocketchat.atlassian.net/browse/NATIVE-719
- Add new workspace;
| ![Before](https://github.com/user-attachments/assets/47fd0301-069b-4f4f-8d19-910d2279dd9f) | ![After](https://github.com/user-attachments/assets/4ea83f12-6ea9-4e3f-a49b-718fbec0db60)
|------------------|-------------------|
| ![Before](https://github.com/user-attachments/assets/a2f48045-d132-47be-9f9c-1a171b2526c9) | ![After](https://github.com/user-attachments/assets/ba9e8538-ca9e-4ad9-be8a-6331d5800507) |
|-------------|------------|
| ![Before](https://github.com/user-attachments/assets/0516527f-7d1a-4c5f-8403-f514b885dccd) | ![After](https://github.com/user-attachments/assets/11cb2cb3-5b21-40dc-96ec-0d08b …
> regression: "apply your certificate" is hidden when adding a new workspace

- app/containers/MessageComposer/MessageComposer.tsx
- app/containers/MessageComposer/helpers/index.ts
- app/containers/MessageComposer/helpers/insertEmojiAtCursor.test.ts
- app/containers/MessageComposer/helpers/insertEmojiAtCursor.ts
To ensure emojis are recognized correctly, I created the insertEmojiAtCursor function to handle with spaces automatically.
https://rocketchat.atlassian.net/browse/NATIVE-720
https://github.com/user-attachments/assets/d42aafc2-8de8-48ad-97fb-979ff92a789c
https://github.com/user-attachments/assets/ec5a33f7-3038-4dda-8a24-2477cbbfc038
> fix: keyboard emoji select position

- app/sagas/deepLinking.js
- app/sagas/login.js
- e2e/tests/assorted/11-deeplinking.spec.ts
7.0 is not returning [these error messages](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/8eceb25ded50015a38e1127778c07d1921cb9a60/app/sagas/login.js#L127) anymore, so we’re not logging out users in those cases.
Introduced a check for the current state, so login and offline usage keeps working.
It should also be backwards compatible.
[NATIVE-722]
[NATIVE-722]: https://rocketchat.atlassian.net/browse/NATIVE-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: login returning 401 without old messages

- app/containers/MessageErrorActions.tsx
- app/lib/encryption/encryption.ts
- app/lib/methods/getCustomEmojis.ts
- app/lib/methods/getPermissions.ts
- app/lib/methods/getRoles.ts
- app/lib/methods/getSettings.ts
- app/lib/methods/getSlashCommands.ts
- app/lib/methods/handleMediaDownload.ts
- app/lib/methods/loadThreadMessages.ts
- app/lib/methods/logout.ts
- app/lib/methods/sendMessage.ts
- app/lib/methods/subscriptions/rooms.ts
- app/lib/methods/updateMessages.ts
- app/sagas/rooms.js
Suppress warning on https://github.com/Nozbe/WatermelonDB/blob/a757e646141437ad9a06f7314ad5555a8a4d252e/src/utils/fp/arrayOrSpread/index.js#L30
[NATIVE-723]
[NATIVE-723]: https://rocketchat.atlassian.net/browse/NATIVE-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Use array instead of spread on WatermelonDB batch

- app/lib/methods/getCustomEmojis.ts
- app/lib/methods/loadThreadMessages.ts
Regression on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5987
> regression: wrong usage of db batch

- app/sagas/login.js
> fix: Logout only if 401

- app/containers/MessageActions/index.tsx
- app/definitions/rest/v1/apps.ts
- app/i18n/index.ts
- app/lib/services/restApi.ts
- app/sagas/login.js
- app/views/AIAppActionsView.tsx
- app/views/RoomActionsView/components/AIAppActionButtons.tsx
- yarn.lock
Fetching app translations from server and using those translations for app actions.
Using `apps` namespace for storing and using those translations and keeping it in a separate context from other translations in app.
[RCAI-37]
[RCAI-37]: https://rocketchat.atlassian.net/browse/RCAI-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: App i18n translations

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.56.0

- app/stacks/InsideStack.tsx
- app/stacks/MasterDetailStack/index.tsx
- app/stacks/MasterDetailStack/types.ts
- app/stacks/types.ts
- app/views/LegalView.tsx
- app/views/SettingsView/index.tsx
- e2e/tests/assorted/04-setting.spec.ts
Today we only can access legalView on onboarding, the proposal of this PR is create a Legal button on SettingsView to access the LegalView on InsideStack.
https://rocketchat.atlassian.net/browse/NATIVE-736
- Go To settingsView;
- Should have legal button;
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/7cfb9ec0-aa59-4a7a-b3c1-0b8edfc4eb88) | ![After](https://github.com/user-attachments/assets/eba107c5-3197-436f-acd3-d5545076f747) |
> chore: Legal button on SettingsView

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.57.0

- ios/SSLPinning/SSLPinning.m
- ios/SSLPinning/SSLPinning.swift
[SUP-714]
[SUP-714]: https://rocketchat.atlassian.net/browse/SUP-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Apple Watch app not working with SSL Client Certificate in some cases

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/SSLPinning/SSLPinning.m
- ios/SSLPinning/SSLPinning.swift
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.56.1 into master

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/SSLPinning/SSLPinning.m
- ios/SSLPinning/SSLPinning.swift
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.56.1 into single-server

- app/views/CreateDiscussionView/index.tsx
The discussion tests are failing because there is a duplicated SelectChannel component (regression was introduced here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6013). This PR removes the duplicated channel input.
https://rocketchat.atlassian.net/browse/NATIVE-775
> fix: Discussion tests failing

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.58.0

- android/app/build.gradle
- app/lib/methods/helpers/sslPinning.ts
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/SSLPinning.mm
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.57.1 into master

- app/lib/constants/colors.ts
Update the userPresenceBusy color token.
https://rocketchat.atlassian.net/browse/MA-170
> feat(a11y): status busy contrast

- android/app/build.gradle
- android/build.gradle
> chore(Android): Disable v1 signing

- android/app/build.gradle
- app/containers/markdown/index.tsx
- app/containers/message/Message.stories.tsx
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Merge 4.57.2 into master

- app/containers/LoginServices/serviceLogin.ts
[CORE-946]
[CORE-946]: https://rocketchat.atlassian.net/browse/CORE-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: OAuth URL separator

- app/lib/methods/subscriptions/rooms.ts
In some cases, `diff` can be undefined and that would crash the app.
Since I touched this file, I also fixed the complexity error lint was complaining about.
> Async arrow function has a complexity of 33. Maximum allowed is 31. eslint [complexity](https://eslint.org/docs/latest/rules/complexity)
It doesn't "change" anything on the code, except some things moved around.
[NATIVE-804]
[NATIVE-804]: https://rocketchat.atlassian.net/browse/NATIVE-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Crash in case of undefined obj

- app/containers/markdown/index.tsx
`parse` can't really be undefined, so I've added `try/catch` to prevent the issue, made sure `msg` is a string and also imported `Root` type correctly.
```
TypeError TaskQueue: Error with task : undefined is not a function 
node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:70963 km
node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:28865 n
node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:73709 parse
node_modules/@rocket.chat/message-parser/dist/messageParser.production.js:1:183550 s
app/containers/markdown/index.tsx:56:49 Markdown
```
[NATIVE-805]
[NATIVE-805]: https://rocketchat.atlassian.net/browse/NATIVE-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: undefined is not a function on markdown

- ios/ShareRocketChatRN/ShareRocketChatRN.swift
https://github.com/user-attachments/assets/214d8e82-8bca-4dd7-a5d3-4f04f759a5d2
[NATIVE-764]
[NATIVE-764]: https://rocketchat.atlassian.net/browse/NATIVE-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(iOS): share extension not working for screenshots

- app/containers/MessageComposer/components/ComposerInput.tsx
- app/containers/MessageComposer/components/EmojiSearchbar.tsx
- app/containers/UIKit/MultiSelect/MultiSelectContent.tsx
- app/lib/constants/debounceConfig.ts
- app/lib/constants/index.ts
- app/views/AddExistingChannelView/index.tsx
- app/views/ChangeAvatarView/index.tsx
- app/views/DiscussionsView/index.tsx
- app/views/E2EEncryptionSecurityView/ChangePassword.tsx
- app/views/PickerView.tsx
- app/views/RoomView/ReactionPicker.tsx
- app/views/RoomsListView/index.tsx
- app/views/SearchMessagesView/index.tsx
- app/views/TeamChannelsView.tsx
- app/views/ThreadMessagesView/index.tsx
I have unified all the debounce values of functions that use debounce, including TextInput related functions, to a single constant. This ensures uniformity across the codebase and allows easier future adjustments to debounce timing. 
Reference to this [comment](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6179#discussion_r1975747044) , and this [comment](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6179#discussion_r1975817511)
NA
NA
Please let me know if I mistakenly left some places unchanged or if I added the debounce value in places where it wasn't needed. Thanks a lot!
> chore: unified all the TextInput related debounce times

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.59.0

- app/lib/encryption/encryption.ts
Refactored subscription decryption process to handle null records and ensure only valid records are batched during write operation
[NATIVE-816]
[NATIVE-816]: https://rocketchat.atlassian.net/browse/NATIVE-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Improve handling of encrypted subscription decryption

- app/lib/methods/helpers/theme.ts
Refactored setNativeTheme to be an async function, so the promise rejection is handled
[NATIVE-817]
[NATIVE-817]: https://rocketchat.atlassian.net/browse/NATIVE-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Android): Improve native theme color setting

- ios/ShareRocketChatRN/ShareRocketChatRN.swift
Update URL opening mechanism to use UIApplication's open method with completion handler
- Share extension must be working
[NATIVE-821]
[NATIVE-821]: https://rocketchat.atlassian.net/browse/NATIVE-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(iOS): Improve URL opening method in share extension

- .github/workflows/organize_translations.yml
- app/i18n/locales/en.json
This PR removes tj-actions because it was compromised and it's printing github secrets in the build output. We are replacing this action by the one created by the security company that detected the threat.
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
> ci: Remove tj-actions/changed-files github action since it's compromised

- app/AppContainer.tsx
- app/index.tsx
- app/lib/methods/helpers/emitter.ts
- app/lib/methods/helpers/localAuthentication.ts
- app/lib/methods/helpers/normalizeMessage.ts
- app/lib/methods/loadMessagesForRoom.ts
- app/lib/methods/loadThreadMessages.ts
- app/lib/methods/updateMessages.ts
- app/lib/notifications/index.ts
- app/lib/notifications/push.ts
- app/sagas/deepLinking.js
- app/sagas/state.js
I was not able to reproduce the same behavior mentioned on #6057, but I could implement a few improvements that could fix issues related to it.
- added a check to navigate from deep link only when react-navigation is ready
- added a check to avoid calling on foreground event when navigation isn't ready
- added a flag to identify if the push is configured already (that's important on Android)
- delayed hide of splash screen on local authentication
- added additional filters on message database updates to avoid unnecessary updates
Closes #6057
- Push notifications
- Screen lock
- Message load
- Receive a push notification (repeat the test for main room and thread)
- Tap it to open the app from push (repeat the test with the app open and closed on background)
- Message should load correctly …
> fix: improve load from push notification flow

- app/containers/message/Urls.tsx
- The URLs component was breaking when verifying if a URL contained an image and received a status outside the 200-500 range.
- URLimage was not being rendered because Expo Image does not start loading the image when its height and width are set to 0.
https://rocketchat.atlassian.net/browse/NATIVE-830
Regression introduced on
- #6127
- #5996 
- open the app;
- go to a room;
- send a link with image (example: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6273);
https://rocketchat.atlassian.net/browse/NATIVE-830?focusedCommentId=49041
| Before | After | 
| ![Simulator Screenshot - iPhone 15 - 2025-03-27 at 17 06 57](https://github.com/user-attachments/assets/cb1840f1-facd-41ca-9f1d-cf1587d06c65) | ![Simulator Screenshot - iPhone 15 - 2025-03-27 at 17 06 …
> regression: Image URL not working properly

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.60.0

- app/containers/MessageComposer/constants.ts
Add a `mediaTypes` prop to the library picker configuration to enable video selection.
https://rocketchat.atlassian.net/browse/NATIVE-845
- Go to room;
- Click on `Plus` icon on message composer;
- Click on `Choose from Library`;
| ![Simulator Screenshot - iPhone 15 - 2025-04-07 at 17 02 42](https://github.com/user-attachments/assets/8459c30e-6a1c-47aa-8f82-3e4171df1d41) | ![Simulator Screenshot - iPhone 15 - 2025-04-07 at 17 02 56](https://github.com/user-attachments/assets/e359828b-8121-4630-b11e-d95528c6e0b4) |
> fix: added media type "all" on library picker config

- app/actions/actionsTypes.ts
- app/actions/server.ts
- app/lib/services/connect.ts
- app/reducers/server.ts
- app/sagas/selectServer.ts
- app/views/NewServerView/hooks/useConnectServer.tsx
- app/views/NewServerView/index.tsx
- e2e/helpers/data_setup.ts
This PR prevents encryption from stopping when navigating to the NewServerView while logged in and then going back. It also fixes the endpoint error that was breaking the app.
https://rocketchat.atlassian.net/browse/SUP-780
- Enter E2EE password;
- try to Add new workspace;
- Click on Close;
> fix: switching workspaces requires re-enter E2EE password

- app/reducers/videoConf.test.ts
- app/reducers/videoConf.ts
- app/sagas/videoConf.ts
https://rocketchat.atlassian.net/browse/SUP-732
> fix: direct call opens without interaction

- app/containers/markdown/components/Plain.tsx
- app/containers/message/Emoji.tsx
- app/containers/message/Reactions.test.tsx
- e2e/tests/assorted/17-userpreferences.spec.ts
The PR fixes the reactions emoji not being rendered correctly.
Regression introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6326 .
https://rocketchat.atlassian.net/browse/NATIVE-866
- open the app;
- react a message with :thumbsup: 
| ![Simulator Screenshot - iPhone 15 - 2025-05-02 at 15 24 58](https://github.com/user-attachments/assets/cfa6f1bf-82b2-434b-8f41-9ac7c990fa30) | ![Simulator Screenshot - iPhone 15 - 2025-05-02 at 15 25 12](https://github.com/user-attachments/assets/095584db-c646-4bec-98d9-4e9b8108707f) |
> fix: reactions not being rendered correctly

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.61.0

- app/containers/ActionSheet/ActionSheet.tsx
- app/containers/ActionSheet/BottomSheetContent.tsx
- app/containers/TextInput/FormTextInput.tsx
- e2e/tests/assorted/01-e2eencryption.spec.ts
- ios/Podfile.lock
- jest.setup.js
- package.json
- patches/@discord+bottom-sheet+4.6.1.patch
- yarn.lock
Components inside the ActionSheet became unfocusable on iOS due to a regression introduced by the change from gohom/bottomsheet in [this PR](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6267).
This PR rolls back that change to restore expected behavior and ensure all components are focusable again.
https://rocketchat.atlassian.net/browse/MA-239
- Click on RoomsListHeaderView;
- Turn the screen reader on;
- Try to focus on components inside of bottom sheet;
> regression: bottom sheet content not accessible

- app/containers/HeaderButton/Common.tsx
- app/containers/HeaderButton/HeaderButtonItem.tsx
- app/views/E2EEnterYourPasswordView.tsx
Regression introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6267
https://rocketchat.atlassian.net/browse/NATIVE-865
- Turn on the screen reader;
- Navigate to enterE2EEPasswordView;
- Focus on Close icon;
> regression: close button is not labelled

- app/lib/database/model/Subscription.js
Introduced on #6357.
Not a regression, because it's not released.
> fix: wrong column naming on subscription.asPlain()

- android/app/src/main/java/chat/rocket/reactnative/notification/CustomPushNotification.java
Simply wraps the call checking if React is initialized
[NATIVE-879]
[NATIVE-879]: https://rocketchat.atlassian.net/browse/NATIVE-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Make sure React context is initialized before notifying JS of a new push notification

- app/lib/hooks/usePreviewFormatText/usePreviewFormatText.test.ts
- package.json
- patches/remove-markdown+0.3.0.patch
- yarn.lock
The pull request https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5990 introduced a regression that incorrectly removed spaces around asterisks, rather than just removing the spaces between the asterisks and the content.
This caused markdown bold text to render incorrectly in the room view’s last message content, by removing spaces that should have been preserved.
N/A
| Old Regex | New Regex |
| --- | --- |
| <img width="377" alt="Screenshot 2025-05-16 at 7 47 34 PM" src="https://github.com/user-attachments/assets/512b0173-d1c5-47a3-992b-fd8ecb0b9d42" /> | <img width="377" alt="Screenshot 2025-05-16 at 7 48 02 PM" src="https://github.com/user-attachments/assets/1c3425d2-fbf4-4a83-b798-a603bbd79b59" /> |
| | Last Message | Chat Message |
| --- | --- | --- |
| Before | <img …
> fix: message preview markdown improvements

- app/lib/methods/helpers/log/index.ts
- app/lib/notifications/videoConf/backgroundNotificationHandler.ts
React Native Firebase is transitioning to a modular query API in its next major release. The current version we are using displays a warning in the console. This PR adds support for the modular query to remove those warnings and ensure a smooth upgrade path.
N/A
N/A
N/A
[Migration Link](https://rnfirebase.io/migrating-to-v22)
> chore: firebase modular query

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.62.0

- app/containers/markdown/Markdown.stories.tsx
- app/containers/markdown/components/Plain.tsx
- app/containers/markdown/styles.ts
Introduced on #6326 #6361
https://rocketchat.atlassian.net/browse/NATIVE-908
|Before   | After  |
|---|---|
|  <img width="243" alt="image" src="https://github.com/user-attachments/assets/d8f16be5-1610-4a89-9343-01c857e7f169" /> | <img width="237" alt="Screenshot 2025-06-23 at 11 54 00" src="https://github.com/user-attachments/assets/57edd507-45eb-4bec-99d1-acb4d324d755" /> |
Added this story, but there's no snapshot testing yet.
> regression: Markdown lists lacking style

- app/containers/ActionSheet/ActionSheet.tsx
Fixes action sheet rendering behind notch when on landscape.
Found while working on #6380 
https://rocketchat.atlassian.net/browse/NATIVE-915
| Before  |  After |
|---|---|
| <img width="1137" alt="image" src="https://github.com/user-attachments/assets/cfeb168f-5b44-4e03-b3ca-988991f5dd95" />  | <img width="1137" alt="image" src="https://github.com/user-attachments/assets/2cd278c6-127e-44ce-9d34-dbd0bc179e7f" />  |
> fix: Action sheet notch on landscape

- app/containers/SearchBox/__snapshots__/SearchBox.test.tsx.snap
- app/containers/TextInput/FormTextInput.tsx
- app/containers/TextInput/__snapshots__/TextInput.test.tsx.snap
regression introduced here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/6317
https://rocketchat.atlassian.net/browse/MA-253
- Go to ChangeAvatarView;
- Turn screen reader on;
- Focus on "Avatar URL" input;
| ![Captura de Tela 2025-06-27 às 14 29 07](https://github.com/user-attachments/assets/53b81c8b-f720-4ece-a958-f93b7019ff54) | ![Captura de Tela 2025-06-27 às 14 29 27](https://github.com/user-attachments/assets/460eb8b3-76c8-48a5-8c9d-fd4801853f17) |
> regression: a11y label announces "ERROR:" without validation error

- android/app/build.gradle
- ios/RocketChatRN.xcodeproj/project.pbxproj
- ios/RocketChatRN/Info.plist
- ios/ShareRocketChatRN/Info.plist
- package.json
> chore: Bump version to 4.63.0

- app/lib/methods/helpers/media.test.ts
- app/lib/methods/helpers/media.ts
This PR ensures that file uploads are not blocked due to spaces in the allowList string.
https://rocketchat.atlassian.net/browse/NATIVE-941
- on workspace settings go to `File Upload > Allowed File Types` and add the allowed list below:
```
application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.oasis.opendocument.text, application/pdf, image/jpeg, image/png, text/plain, image/gif, image/heif, image/*, image/heic, image/pjpeg, image/x-png
```
- Go to room;
- Try to take a photo and send on iOS;
> fix: remove spaces from allowList to ensure correct MIME type validation

- app/views/RoomsListView/components/Container.tsx
https://rocketchat.atlassian.net/browse/NATIVE-957
| Before  | After  |
|---|---|
|  <img width="387" height="176" alt="image" src="https://github.com/user-attachments/assets/c23772c9-0da6-40da-9289-b5eaf2a2ad61" /> |  <img width="387" height="178" alt="image" src="https://github.com/user-attachments/assets/573ea6f7-97a8-4dc9-98ea-ca45b253d985" /> |
> regression: Wrong StatusBar on RoomsListView

- app/containers/message/Message.stories.tsx
- app/containers/message/__snapshots__/Message.test.tsx.snap
- app/views/RoomView/LoadMore/LoadMore.test.tsx
- Refactored the `responsiveLayoutProviderLargeFontValue` to accept a dynamic font scale.
- Wrapped `MessageComponent` in `ResponsiveLayoutContext.Provider` to ensure proper context usage.
- Updated snapshot tests to replace NaN values with appropriate dimensions (36 for height and width) for various components.
- Ensured that the LoadMore test file correctly unmocked the `useResponsiveLayout` hook for accurate testing.
https://rocketchat.atlassian.net/browse/NATIVE-959
> chore: Update Message component stories for responsive layout and fix snapshot tests

- app/lib/encryption/room.ts
- e2e/tests/assorted/01-e2eencryption.spec.ts
Simple PR that fixes the way ciphertext is built.
https://rocketchat.atlassian.net/browse/CORE-1290
- Edit an encrypted message
- Updated message should be written correctly
Note: Added an e2e test for that.
> fix: Update encrypted message doesn't work

- android/app/build.gradle
- android/build.gradle
- package.json
- yarn.lock
Follow [this commit](https://github.com/bugsnag/bugsnag-js/issues/2273#issuecomment-2587273163) and removed `bugsnag-android-gradle-plugin`
> chore: fix Android builds failing on CI

- ios/RocketChatRN.xcodeproj/project.pbxproj
- package.json
- yarn.lock
I forgot to do this when #6478 was merged.
My bad!
https://rocketchat.atlassian.net/browse/NATIVE-976
> chore: Use react-native-simple-crypto from main

- app/views/RoomView/List/definitions.ts
- app/views/RoomView/List/index.tsx
- app/views/RoomView/index.tsx
It looks like `Flatlist.ListFooterComponent` is causing a really long animation loading, especially on threads (see videos below).
We're yet to evaluate LegendList and FlashList, so I'm removing the prop from the list for now.
https://rocketchat.atlassian.net/browse/NATIVE-983
https://github.com/user-attachments/assets/a9bd9c02-095a-4d7c-8ccc-5d2ac32cfdd2
https://github.com/user-attachments/assets/b8a1be91-40db-4db5-8a6f-87ad43a21c17
> fix: Remove List footer to prevent thread load animation

- app/containers/MessageComposer/MessageComposer.test.tsx
- app/containers/MessageComposer/MessageComposer.tsx
- app/containers/MessageComposer/__snapshots__/MessageComposer.test.tsx.snap
Fixed an issue with early return on send message.
Wrote unit tests to make sure it's working fine.
https://rocketchat.atlassian.net/browse/NATIVE-987
- Type `/gimme` on composer (or any other slash command)
- While the slash autocomplete is rendered, send the message
- Autocomplete should be gone
> fix: Autocomplete not hiding after using slash command

- app/views/E2ESaveYourPasswordView.tsx
https://rocketchat.atlassian.net/browse/NATIVE-998
- Reset your E2EE Password;
- Log in again;
- Navigate to E2eEnterYourPasswordView;
| <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-09-02 at 18 02 32" src="https://github.com/user-attachments/assets/621db5d2-9652-4fbf-91b6-50271149fbad" /> | <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-09-02 at 18 02 21" src="https://github.com/user-attachments/assets/c62c0aca-3f22-41d3-879e-b307d865c26a" /> |
| 1x | 2x |
| <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-09-02 at 18 02 21" src="https://github.com/user-attachments/assets/c62c0aca-3f22-41d3-879e-b307d865c26a" /> | <img …
> fix: Copy button title was not displayed on E2ESaveYourPasswordView

- app/views/ProfileView/components/ConfirmEmailChangeActionSheetContent/index.tsx
When we try to change any detail on profile which requires password confirmation, bottomsheet on Android hide behind keyboard which makes it hard to write password and update information.
| --- | --- |
| <img width="735" height="843" alt="Screenshot 2025-09-05 at 12 52 38 AM" src="https://github.com/user-attachments/assets/13cafd87-d8f8-4194-872d-f962f3537117" /> |<img width="739" height="852" alt="Screenshot 2025-09-05 at 12 51 33 AM" src="https://github.com/user-attachments/assets/f203d4c5-84ff-4019-802b-13d1c7765f19" /> |
> fix(Android): confirm password hidden behind keyboard

- app/lib/methods/getServerInfo.ts
`getServerInfo` endpoint checks the `view-statistics` permission, and to perform the verification, we need to send the user's credentials in the request.
https://rocketchat.atlassian.net/browse/NATIVE-993
- Navigate to SettingsView;
- Scroll down;
> fix: getServerInfo never returning patch versions

- android/app/src/main/java/chat/rocket/reactnative/notification/Ejson.java
This PR addresses two critical crashes in the Android notification system that were preventing push notifications from working properly:
- NullPointerException in Ejson constructor - App crashed when React context was unavailable during MMKV initialization
- SecurityException with Gson reflection - Gson failed to deserialize notification JSON due to non-static inner classes
The fixes ensure that:
- The notification system handles cases where the React context is not available during app startup or background states
- Gson can properly deserialize notification JSON objects without reflection security violations
- The app maintains functionality even when storage initialization fails
- These changes follow Android development best practices and ensure robust notification handling across …
> fix(android): resolve notification system crashes due to null context and Gson reflection issues

- app/lib/methods/getPermalinks.test.ts
- app/lib/methods/getPermalinks.ts
It fixes links to messages or channels with non ascii characters or spaces.
Closes #6600
1. Create channel with spaces and non ascii symbols.
2. Create message.
3. Quote message.
> fix: Encode URI in quotation (message) and channel links

- app/views/ForgotPasswordView.tsx
We used the wrong I18n key for showing the email label in Forget Password View
N/A
| --- | --- |
| <img width="366" height="193" alt="Screenshot 2025-09-09 at 8 37 58 PM" src="https://github.com/user-attachments/assets/fd476d3b-769a-4adf-a103-a3a54ec3b162" /> | <img width="370" height="186" alt="Screenshot 2025-09-09 at 8 38 18 PM" src="https://github.com/user-attachments/assets/118c2f10-049d-476d-93e1-539328bf515c" /> |
> fix: invalid i18n key for email on ForgetPasswordView
