RocketChat/Rocket.Chat.ReactNative

app/views/LoginView.js, app/views/Styles.js
=> Improve login view

__tests__/__snapshots__/RoomItem.js.snap, __tests__/__snapshots__/Storyshots.test.js.snap, app/containers/Avatar.js, app/presentation/RoomItem.js, app/views/SelectUsersView.js, package-lock.json, package.json
=> Change avatars to square format

app/actions/actionsTypes.js, app/actions/messages.js, app/containers/Message.js, app/containers/MessageBox.js, app/containers/message/User.js, app/containers/message/index.js, app/lib/realm.js, app/lib/rocketchat.js, app/reducers/messages.js, app/sagas/messages.js, app/views/RoomView.js, package-lock.json, package.json
Messages actions step by step to see what's happening on ios build
=> Messages actions 2

__tests__/__snapshots__/RoomItem.js.snap, __tests__/__snapshots__/Storyshots.test.js.snap, app/lib/realm.js, app/presentation/RoomItem.js, app/views/RoomsListView.js, storybook/stories/Channels/DirectMessage.js
Enable option to delete realm if migration is needed!
=> Add mention mark by the unread number

app/containers/routes/AuthRoutes.js, app/views/RoomsListView.js
=> Change Room’s back button text to previews screen title

app/containers/message/Card.js, app/containers/message/PhotoModal.js
- Increase preview size to fit the screen space better
- Allow zoom up to 5x (why not? 😄 )
- Close on tap
- Fix alignments
=> Improve image modal/preview

app/containers/MessageBox.js, app/containers/Typing.js, app/lib/realm.js, app/lib/rocketchat.js, app/sagas/rooms.js, app/views/RoomView.js, app/views/RoomsListView.js
moved on top
cancel typing on send
=> User typing

app/lib/createStore.js, app/sagas/index.js, app/sagas/init.js, app/sagas/state.js, app/views/RoomsListView.js, package-lock.json, package.json
- Fix return from background
- fix Date on RoomList
=> [FIX][ANDROID] Fix return from background

app/containers/Routes.js, app/containers/routes/NavigationService.js, app/reducers/app.js, app/reducers/login.js, app/sagas/login.js, app/sagas/rooms.js, app/views/RoomView.js
=> [NEW] Reload room on return from background

app/containers/message/Reply.js
=> Attachments improvements

app/lib/rocketchat.js, app/sagas/state.js
- User presence away when app goes to background
- User presence online when app comes back to foreground
=> Set user presence (online/away)

app/actions/actionsTypes.js, app/actions/login.js, app/constants/colors.js, app/containers/Header.js, app/containers/routes/AuthRoutes.js, app/lib/rocketchat.js, app/reducers/login.js, app/views/RoomsListView.js
=> Manage user's status

__tests__/RoomItem.js, __tests__/__snapshots__/RoomItem.js.snap, __tests__/__snapshots__/Storyshots.test.js.snap, app/presentation/RoomItem.js, app/views/RoomsListView.js, storybook/stories/Channels/DirectMessage.js
=> [NEW] Better date format for room’s list

app/containers/message/Markdown.js, package-lock.json, package.json
=> Better markdown

.eslintrc.js, __tests__/__snapshots__/RoomItem.js.snap, __tests__/__snapshots__/Storyshots.test.js.snap, app/presentation/RoomItem.js, app/utils/touch/index.android.js, app/utils/touch/index.ios.js
Use TouchableHighlight and TouchableNativeFeedback instead of TouchableOpacity on the room list items
@ggazzo
=> Improve Rooms List

app/containers/Routes.js, app/views/LoginView.js
After tapping hardware's back button, splash screen would never be hidden.
- Back button fix
- Login text input focus
=> Splash screen bug on android

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Solves issues : #160 
@ggazzo  Let me know if changes are required.
=> Added Templates for Issue and Pull Requests

android/app/build.gradle, android/app/src/main/java/com/rocketchatrn/CustomTabsAndroid.java, android/app/src/main/java/com/rocketchatrn/RocketChatNativePackage.java, app/containers/message/Audio.js, app/containers/message/Reply.js, app/containers/message/Url.js, app/containers/message/Video.js, app/nativeModules/CustomTabsAndroid.js, app/utils/openLink.android.js, app/utils/openLink.ios.js, package-lock.json
Closes #167 
Implemented custom tabs for opening links on android in chrome custom tabs. 
For iOS , it is same as it was earlier.
@ggazzo Do review!
=> Open link in customTabs on Android.

app/containers/message/Markdown.js
=> [FIX] Mentions and rooms regex

.circleci/config.yml
=> Fix CircleCi build

.circleci/config.yml, ios/fastlane/Fastfile, ios/fastlane/README.md, ios/fastlane/report.xml
=> Fix build of PRs from forks

app/containers/MessageBox/index.js
Closes #191 
If there is no text then the **+** icon will be shown and if there is any text then the **send** icon will be shown which is same on the web.
=> Improves messageBox

app/actions/actionsTypes.js, app/actions/room.js, app/lib/ddp.js, app/lib/rocketchat.js, app/reducers/room.js, app/sagas/rooms.js, app/views/RoomView/Header/index.js, app/views/RoomView/index.js
Closes #169
- Fixed the bug when you receive a message inside that room, the notification wont go away.
- Added data about when the room was last opened
- And fixed some subscriptions not being properly closed when you leave (back to room list) a channel.
=> [FIX] Unread not going away when receiving a message from inside a room

android/app/build.gradle, android/app/src/main/java/com/rocketchatrn/MainApplication.java, android/settings.gradle, app/containers/MessageActions.js, app/utils/info.js, app/views/ForgotPasswordView.js, app/views/LoginView.js, app/views/RegisterView.js, package-lock.json, package.json
=> Adds support for Toast message

app/lib/ddp.js
=> hotfix subscriptions

app/containers/MessageActions.js, app/lib/realm.js, app/lib/rocketchat.js, app/views/RoomView/index.js, app/views/RoomView/styles.js
=> Read only room

app/containers/MessageBox/index.js, app/containers/MessageBox/style.js
=> Autocomplete @all & @here mentions

android/app/src/main/AndroidManifest.xml, app/containers/MessageActions.js
=> App perform a vibration feedback onLongPress

android/app/src/main/AndroidManifest.xml, app/containers/MessageBox/index.js, app/containers/MessageBox/style.js, app/views/RoomView/index.js, package-lock.json, package.json
=> Message box issues

.circleci/config.yml
=> Fix TestFlight upload

app/containers/MessageBox/index.js
=> Keyboard updates

.eslintrc.js, __tests__/__snapshots__/RoomItem.js.snap, __tests__/__snapshots__/Storyshots.test.js.snap, app/actions/actionsTypes.js, app/actions/mentionedMessages.js, app/actions/pinnedMessages.js, app/actions/starredMessages.js, app/containers/message/Reply.js, app/containers/message/index.js, app/containers/routes/AuthRoutes.js, app/lib/realm.js, app/lib/rocketchat.js, app/presentation/RoomItem.js, app/reducers/index.js, app/reducers/mentionedMessages.js, app/reducers/pinnedMessages.js, app/reducers/starredMessages.js, app/sagas/index.js, app/sagas/mentionedMessages.js, app/views/MentionedMessagesView/index.js, app/views/MentionedMessagesView/styles.js, app/views/PinnedMessagesView/index.js, app/views/RoomActionsView/index.js, app/views/RoomMembersView/index.js, app/views/RoomMembersView/styles.js, app/views/RoomView/ListView.js, app/views/RoomView/index.js, app/views/StarredMessagesView/index.js
=> [NEW] Room actions: Mentioned messages and Room Members

app/animations/fade.js, app/containers/EmojiPicker/EmojiCategory.js, app/containers/EmojiPicker/index.js, app/containers/Sidebar.js, app/views/ListServerView.js, app/views/LoginView.js, app/views/RoomMembersView/index.js
=> Workaround for RN 0.54 on iOS

android/app/build.gradle, app/containers/TextInput.js, app/containers/message/User.js, app/containers/message/index.js, app/lib/rocketchat.js, app/views/MentionedMessagesView/index.js, app/views/PinnedMessagesView/index.js, app/views/RoomFilesView/index.js, app/views/RoomsListView/index.js, app/views/SearchMessagesView/index.js, app/views/SelectedUsersView.js, app/views/SnippetedMessagesView/index.js, app/views/StarredMessagesView/index.js
=> Beta fixes

android/app/build.gradle, android/app/proguard-rules.pro, app/containers/MessageBox/index.js, app/containers/message/index.js, app/views/LoginSignupView.js, app/views/LoginView.js, app/views/NewServerView.js, app/views/RegisterView.js, app/views/RoomsListView/index.js, app/views/SelectedUsersView.js, package-lock.json, package.json
=> Fabric and image fix

package-lock.json
=> Markdown fix

android/app/src/main/AndroidManifest.xml, app/actions/actionsTypes.js, app/actions/deepLinking.js, app/containers/Routes.js, app/containers/routes/NavigationService.js, app/lib/ddp.js, app/lib/methods/canOpenRoom.js, app/lib/methods/helpers/parseQuery.js, app/lib/methods/subscriptions/room.js, app/lib/methods/subscriptions/rooms.js, app/lib/rocketchat.js, app/sagas/connect.js, app/sagas/deepLinking.js, app/sagas/index.js, app/sagas/selectServer.js, app/views/NewServerView.js, app/views/RoomView/Header/index.js, app/views/RoomView/ListView.js, app/views/RoomView/index.js, app/views/RoomsListView/index.js, ios/RocketChatRN/AppDelegate.m, ios/RocketChatRN/Info.plist
=> Deep linking

app/containers/Avatar.js, app/containers/RoomTypeIcon.js, app/presentation/RoomItem.js, app/utils/avatarInitialsAndColor.js, app/views/RoomActionsView/index.js, app/views/RoomInfoView/index.js, app/views/RoomView/Header/index.js
Avatar initials style updated to match web repo
=> Avatar initials and room type icon

app/lib/rocketchat.js
Closes #137 
Some server configurations may send x-instance-id header with different case.
=> Allow x-instance-id and X-Instance-ID header

app/lib/methods/helpers/mergeSubscriptionsRooms.js
=> [Fix] Empty room name for livechat

android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java, package-lock.json, package.json
=> [FIX] Android 8 notifications

README.md
=> Added single-server to readme

app/containers/message/index.js
=> [FIX] Only single attachment rendered

android/app/build.gradle, app/lib/realm.js, app/sagas/selectServer.js, app/views/RoomsListView/Header/Header.ios.js, app/views/RoomsListView/ServerDropdown.js, app/views/RoomsListView/index.js, ios/RocketChatRN/Info.plist
=> [FIX] Missing current server

app/views/RoomsListView/index.js
=> [FIX] Drawer navigation won't refresh chats

app/containers/message/Audio.js, app/containers/message/Image.js, app/containers/message/Url.js, app/containers/message/Video.js
=> [FIX] Avoid errors on Audio/Image/Video

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.2.1

android/app/build.gradle
=> Stop supporting Android 4.4 and lower

android/app/build.gradle, android/build.gradle, app/views/RoomsListView/index.js, index.android.js, package-lock.json, package.json
=> [NEW] Use community JSC for Android

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.3.0

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.3.1

.circleci/config.yml, app/lib/ddp.js, app/lib/methods/canOpenRoom.js, app/lib/methods/getCustomEmojis.js, app/lib/methods/getPermissions.js, app/lib/methods/getRooms.js, app/lib/methods/getSettings.js, app/lib/methods/helpers/rest.js, app/lib/methods/loadMessagesForRoom.js, app/lib/methods/loadMissedMessages.js, app/lib/methods/readMessages.js, app/lib/methods/sendMessage.js, app/lib/methods/subscriptions/room.js, app/lib/rocketchat.js, app/sagas/init.js, app/views/RoomView/styles.js, app/views/RoomsListView/ServerDropdown.js, e2e/08-roomactions.spec.js, e2e/09-roominfo.spec.js
=> [FIX] Handle deleted messages

app/lib/rocketchat.js, app/views/RoomsListView/index.js
Rooms were disappearing during search
=> [FIX] Search rooms

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.3.3

app/views/RoomInfoView/index.js, package-lock.json
=> Customfields display userinfo

app/containers/ConnectionBadge.js
DDP badge wasn't hiding on fast connections
=> [FIX] DDP badge hide

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.4.0

app/views/RoomsListView/index.js
=> [FIX] Unread rooms group order

app/containers/message/index.js
=> Use grouping setting on temp messages

app/views/RoomActionsView/index.js, app/views/RoomInfoEditView/index.js, app/views/RoomView/index.js
=> [FIX] Delete room error

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values/strings.xml
=> Rename to Rocket.Chat Experimental

app/lib/rocketchat.js
=> Regression: Wait for unmount to delete database after logout

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.4.1

app/containers/ConnectionBadge.js, app/lib/rocketchat.js, app/views/index.js
=> Regression: Crash on Android search

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.4.2

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to v1.4.3

.babelrc, app/lib/rocketchat.js, app/presentation/RoomItem.js, app/sagas/login.js, app/views/RoomsListView/index.js
=> [FIX] Logout

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.4.4

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.5.0

app/lib/methods/loadMessagesForRoom.js, app/lib/methods/loadMissedMessages.js, app/views/RoomView/index.js
=> [FIX] Messages not being loaded properly

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.5.1

app/views/RoomView/Header/index.js
=> [FIX] Room view header crashes when destructuring reducer

app/views/RoomView/index.js, app/views/RoomsListView/index.js, package-lock.json, package.json
After closing any room with an opened keyboard, the keyboard would stay opened in the rooms list without focusing anything.
=> [FIX] Dismiss keyboard on room close

README.md, android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.6.0

android/app/src/main/AndroidManifest.xml
- Removed largeHeap
- Changed from singleTop to singleTask
- Update uses-sdk
=> Android Manifest changes

app/actions/actionsTypes.js, app/actions/index.js, app/containers/Sidebar.js, app/reducers/app.js, app/sagas/deepLinking.js
=> Regression: Deep linking stopped working after react-native-navigation update

app/lib/rocketchat.js, app/sagas/login.js, app/views/OnboardingView/index.js, app/views/ProfileView/index.js, app/views/RoomsListView/index.js, app/views/SettingsView/index.js, package-lock.json
=> [FIX] Android stuck on splash screen after hardware back button is pressed

app/views/RoomsListView/index.js
**With these filters**
**Before**
**After**
=> Chats: Don't show group header if none of the filters is selected

.circleci/config.yml
Update Xcode from 10.0.0 to 10.1.0
=> [CHORE] Update Xcode image version on CircleCI

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.7.0

.circleci/config.yml
=> [CHORE] Add hold step on CircleCI before TestFlight

app/lib/rocketchat.js
=> [FIX] GET /info to check if it's a valid server instead of x-instance-id

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.7.1

app/containers/MessageActions.js
=> [FIX] Back button press on message actions

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.8.0

app/lib/rocketchat.js
If login params have `code`, the user already have typed user and password and he wants to login from 2FA.
=> [FIX] 2FA login in a server with LDAP enabled

app/views/SelectedUsersView.js, e2e/07-createroom.spec.js
=> Allow to create empty channel

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/message/Reply.js, storybook/stories/Message.js
=> [FIX] Reply title should break text

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.9.0

README.md
=> [CHORE] Add TestFlight invite and update Readme

package.json, yarn.lock
This migration lost a previous react-native-fast-image downgrade.
=> [FIX] NPM -> yarn dependencies migration

.github/ISSUE_TEMPLATE.md
=> [CHORE] Update issue template

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.10.0

android/app/build.gradle, app/containers/MessageBox/index.js
Call `isTyping` only one time per second.
=> [FIX] Prevent mass is typing dispatchs

android/app/build.gradle, app/containers/MessageBox/index.js, app/lib/methods/getCustomEmojis.js, app/lib/methods/getSettings.js, app/lib/methods/loadMessagesForRoom.js, app/lib/methods/loadMissedMessages.js, app/lib/methods/sendFileMessage.js, app/lib/methods/subscriptions/rooms.js, app/lib/rocketchat.js
=> [FIX] Handle database errors properly

app/containers/MessageBox/index.js
This PR attempts to fix a common bug on React Native that causes TextInput's to become slow after typing a long text.
**Useful links:**
- There's an open issue on React Native repo [here](https://github.com/facebook/react-native/issues/20119)
- [This video](https://youtu.be/83ffAY-CmL4?t=1366) from @axe-fb also explains why the TextInput becomes slow and he suggests a workaround (the one I used in this PR).
=> [FIX] Slow messagebox

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/MessageActions.js, app/containers/MessageBox/index.js, app/containers/message/Message.js, app/containers/message/index.js, app/containers/message/styles.js, app/utils/vibration.js, app/views/RoomMembersView/index.js
- Remove touchable opacity when scrolling messages
- Tap on disable messages closes keyboard
- Unify vibration
- Vibrate only on Android
=> Message button

app/containers/MessageBox/index.js
=> [FIX] Select emoji error

package.json, yarn.lock
=> Update Realm to 2.24

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump to 1.10.1

app/index.js, app/push/index.js, app/push/push.android.js, app/push/push.ios.js, app/sagas/deepLinking.js, app/sagas/selectServer.js, app/views/AuthLoadingView.js, ios/RocketChatRN.xcodeproj/project.pbxproj
=> [FIX] Deep linking between multiple logged servers

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.11.0

app/containers/HeaderButton.js, app/views/RoomView/Header/index.js
=> added scrollable room name feature

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.12.0

app/containers/message/Markdown.js, app/containers/message/Reply.js, app/views/RoomView/List.js
=> [FIX] Apply emojify on empty texts

app/index.js
=> Lock drawer when stack is not on root screen

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/message/Message.js, app/containers/message/styles.js, app/views/RoomView/Header/Header.js, package.json, storybook/stories/Message.js, yarn.lock
=> [FIX] Smaller thread title

app/views/RoomsListView/index.js
=> [Regression] Search stopped working on Android after LastMessage refactor

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.13

app/views/RoomInfoView/index.js
=> removed one getRoleDescription function

app/views/RoomView/Header/index.js
=> [FIX] Remove listeners on RoomView header unmount

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.14.0

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/message/Message.js, app/containers/message/MessageAvatar.js, app/containers/message/index.js
=> [FIX] Message grouping not re-rendering

app/containers/ReactionsModal.js
=> [FIX] Get custom emoji on reactions modal

.circleci/config.yml
=> [CHORE] Upgrade Mac CI image to 10.2.1

app/containers/message/Reactions.js
=> [FIX] Reaction count not rerendering

.circleci/config.yml, android/app/build.gradle
=> [CHORE] Android app bundle

android/app/build.gradle
I commited the same error the community fixed here: https://github.com/facebook/react-native/pull/23897
=> [FIX] Architecture typo

.circleci/config.yml, android/app/google-services.json, android/app/google-services.prod.json, ios/GoogleService-Info.prod.plist
We just migrated to Firebase and debug builds are starting to mess up other info.
Crash free users, performance, retention, etc.
This PR falls all non-release versions into another Firebase project and beta/production in the important one.
=> [CHORE] Split Google Services in debug and production

app/containers/MessageActions.js
Closes #944 
We were important `moment` in a wrong way.
=> [FIX] Crash on message long press

app/containers/MessageBox/ReplyPreview.js
=> [FIX] Reply preview showing the entire message

app/utils/openLink/index.ios.js
=> [IMPROVEMENT] Open links as push instead of modal

package.json, yarn.lock
1.14.0 beta is crashing on Samsung devices.
It started to happen on Realm updated.
This PR attempts to fix it.
Related to https://github.com/realm/realm-js/issues/2391
=> [FIX] Crashing on app launch

app/views/ThreadMessagesView/index.js
=> [FIX] Thread crash if room is undefined

app/containers/MessageBox/index.js
=> [FIX] Stop mention tracking if text is empty.

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> [CHORE] Bump version to 1.15.0

android/app/build.gradle, android/build.gradle, package.json, yarn.lock
Possible fix to https://github.com/facebook/react-native/issues/24261
=> [CHORE] Use no-JIT JSC

app/lib/rocketchat.js, app/sagas/selectServer.js, app/views/RoomsListView/Header/Header.android.js, app/views/RoomsListView/Header/Header.ios.js, app/views/RoomsListView/Header/index.js
Closes #934 
Bug:
If the user changes from one server to another fast enough, the app executes some request with the wrong token causing a 403, disconnect and clearing the user data.
Fix:
This PR makes `RocketChat.connect` returns a Promise and resolves it on `handleSelectServer` with yield. This makes every connect call to be in sync with the rest of the methods.
Then it check for select server connecting and loading reducers to disable `ServerDropdown` button.
Depends on #959
=> [FIX] Change server issue

android/app/build.gradle
=> [FIX] Android build stopped working after Play Services release

app/sagas/rooms.js
App still hang on "Updating" sometimes.
When the app goes `inactive` and return to `foreground`, it may not fire `background` state.
=> [FIX] Change rooms request's race cancellation condition

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.15.1

app/lib/rocketchat.js, app/views/RoomView/index.js
=> [FIX] Join discussion

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.16.0

app/sagas/init.js
Fix bug when android app start because servers of rn-user-defaults on android always return null.
I used ```AsyncStorage``` to save ```hasMigration``` because ```rn-user-defaults``` isn't erased if uninstall the app.
=> [BUG] Fix native credentials (android)

yarn.lock
Fix Android build error introduced by #1026
=> [FIX] Android build

app/sagas/init.js, ios/RocketChatRN.xcodeproj/project.pbxproj
=> [FIX] iOS share credentials build

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.16.1

app/sagas/deepLinking.js
=> [FIX] Set UserDefaults AppGroup on notification tap

app/presentation/RoomItem/Actions.js, app/presentation/RoomItem/index.js, app/presentation/RoomItem/styles.js, app/views/RoomsListView/index.js
=> [FIX] Swipe animations

android/app/build.gradle, ios/RocketChatRN/Info.plist
=> Bump version to 1.17.0

app/containers/MessageActions.js, app/containers/Toast.js, app/helperComponent/Toast.js, app/index.js, app/utils/info.js, app/views/ProfileView/index.js, app/views/RoomInfoEditView/index.js, app/views/RoomMembersView/index.js, app/views/RoomView/index.js
=> [IMPROVEMENT] Reusable toast

app/sagas/login.js, app/utils/moment.js, app/views/RoomsListView/index.js
We have an error when use moment.locale because our language key is 'pt-BR', with 'BR' on uppercase and moment.locale not have this locale.
https://github.com/facebook/react-native/issues/16540
=> [FIX] Moment locales

app/containers/MessageBox/UploadModal.js
=> [FIX] Empty white list enables all media types upload

ios/Pods/Pods.xcodeproj/project.pbxproj, yarn.lock
=> Merge master into develop

README.md
=> [CHORE] Update README

app/views/ShareListView/index.js, app/views/ShareView/index.js
=> [FIX] Media share type

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.18.0

app/views/NewServerView.js, app/views/OnboardingView/index.js
=> [FIX] Remove onboarding insets

app/containers/message/Markdown.js
=> [FIX] Markdown not rendering mentions and channels

.babelrc, android/gradle.properties, app/lib/createStore.js, babel.config.js, index.js, package.json, patches/react-native-markdown-renderer+3.2.8.patch, yarn.lock
Apparently, we're logging console after RN 0.60.4
=> [FIX] Remove console on production builds

app/lib/rocketchat.js
Defaults setting to true (even more for not being available on most servers yet).
Closes https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1075
=> [IMPROVEMENT] Checks if custom OAuth button should be shown

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.19.0

app/containers/MessageActions.js, app/containers/MessageBox/index.js, app/lib/methods/getSlashCommands.js, app/lib/methods/sendFileMessage.js, app/presentation/ServerItem/index.js, app/views/NotificationPreferencesView/index.js, app/views/RoomInfoView/index.js
`log` only can receive one param, if you send two params you get this error:
=> [FIX] Fix calls to bugsnag.notify

app/containers/FileModal.js, app/containers/message/Video.js
=> [FIX][Android] Play webm video format on webview

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.20.0

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/EmojiPicker/CustomEmoji.js, app/containers/markdown/index.js
=> [IMPROVEMENT] Use FastImage to custom emojis

app/views/NotificationPreferencesView/index.js, app/views/RoomActionsView/index.js, app/views/RoomMembersView/index.js, app/views/RoomView/UploadProgress.js, app/views/ThreadMessagesView/index.js
=> [FIX] Intended direct mutation state running before initial state gets initiated

ios/RocketChatRN.xcodeproj/project.pbxproj
=> [FIX] Link WatermelonDB on share extension

app/index.js, package.json, yarn.lock
When we open the app it blinks the sidebar.
I opened an [issue](https://github.com/react-navigation/drawer/issues/108) on `react-navigation-drawer`, when it is resolved, we can update it again.
=> [CHORE] Revert react-navigation-drawer

app/views/SidebarView/index.js
=> [FIX] Show admin panel button logic

app/containers/MessageBox/Recording.js, app/containers/MessageBox/UploadModal.js, app/containers/MessageBox/index.js, app/lib/methods/sendFileMessage.js, app/utils/media.js, app/views/ShareListView/index.js
=> [FIX] Unify upload check

app/containers/MessageBox/RightButtons.android.js, app/containers/message/Audio.js, app/containers/message/Broadcast.js, app/containers/message/Discussion.js, app/containers/message/Message.js, app/containers/message/Urls.js, app/containers/message/Video.js, app/index.js, app/notifications/inApp/index.js, app/presentation/RoomItem/Actions.js, app/views/AuthLoadingView.js, app/views/AuthenticationWebView.js, app/views/DirectoryView/Options.js, app/views/DirectoryView/index.js, app/views/RoomInfoView/index.js, app/views/RoomView/index.js, app/views/RoomsListView/ListHeader/index.js, app/views/RoomsListView/SortDropdown.js, app/views/ShareListView/index.js, app/views/SidebarView/index.js
Closes #1203
Replaced <React.Fragment> and </React.Fragment> tags with <> and </>, respectively.
=> [CHORE] Use React Fragment shorthand

app/views/RoomsListView/SortDropdown.js
Closes #1224
Here I have corrected the mistakes that I made pin previous commit.
=> [FIX] Close SortDropdown on sort select

app/containers/MessageBox/index.js
=> [FIX] Slash commands not cleaning is typing and not using state

__tests__/__snapshots__/Storyshots.test.js.snap
=> [FIX] Jest

SECURITY.md
=> [CHORE] Add security doc

app/containers/message/index.js
=> [FIX] Reaction press

app/sagas/selectServer.js
=> [FIX] Channel avatars not showing after application unloads

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.20.1

app/lib/database/model/Subscription.js, app/lib/database/model/migrations.js, app/lib/database/schema/app.js, app/presentation/RoomItem/index.js, app/views/RoomsListView/index.js
=> [IMPROVEMENT] Respect "Hide counter" preference

app/containers/MessageBox/index.js, app/views/RoomView/index.js
=> [FIX] Pass isFocused as a function to Messagebox

app/presentation/RoomItem/index.js
=> [FIX] Unnecessary rerender on RoomItem when status is undefined

app/lib/methods/subscriptions/rooms.js
Preview stopped showing after #1344
=> [FIX] URL preview

app/views/RoomView/List.js
=> [REGRESSION] Decrease list view memory size

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.20.3

.circleci/config.yml
=> [FIX] Use Ruby 2.4 on TestFlight upload

app/lib/methods/helpers/parseUrls.js
=> [FIX] Parse image URL only if it's not empty

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.21.0

app/lib/rocketchat.js
=> [FIX] Crowd login

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.22.0

app/lib/methods/updateMessages.js
When messages are deleted or pruned, the app isn't deleting them from local db.
Related to #1385
=> [FIX] Delete messages

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.24.0

app/views/LoginView.js, app/views/NewServerView.js
- URL keyboard on server
- Mark username and password content type so the OS can provide autofill.
=> [IMPROVEMENT] Keyboard and content type on login

app/views/RoomsListView/index.js
It fails randomly on development after Fast Refresh fires.
=> [FIX] BackHandler remove random failing on development

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 1.25.0

ios/Podfile.lock, ios/Pods/Local Podspecs/RNImageCropPicker.podspec.json, ios/Pods/Manifest.lock, yarn.lock
@RocketChat/reactnative 
Update `react-native-image-crop-picker` solve the problem.
=> [FIX] Take a video

app/views/ThemeView.js
=> [FIX] Automatic theme repeating

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
Keeping Experimental and official app version in sync should make easier to differentiate features and track issues.
=> [CHORE] Sync Experimental and Official app versions

README.md
=> [DOCS] Update readme

yarn.lock
=> [FIX] Jitsi with Hermes Enabled

android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java, android/app/src/main/java/chat/rocket/reactnative/Ejson.java
Steps to reproduce:
* Administration -> Push -> Send a test push to my user.
* When you receive the push, app closes because we try to access some variables that doesn't exist.
Closes #1505 .
=> [FIX] Server Test Push Notification

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.2.1

app/lib/methods/helpers/normalizeMessage.js
=> [FIX] Error when normalizing empty messages

app/views/AuthenticationWebView.js
CAS stopped working after #1527 
Closes #1545
=> [REGRESSION] CAS

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.2.2

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.2.3

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.2.4

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.3.0

app/sagas/rooms.js
We need to catch problems on `db.batch` for rooms get and not update `roomsUpdatedAt` if save to db raises any error.
=> [FIX] Channels doesn't load

app/views/AuthenticationWebView.js, app/views/LoginSignupView.js
=> [FIX] Make SAML to work on Rocket.Chat < 2.3.0

ios/RocketChatRN.xcodeproj/project.pbxproj
=> [CHORE] Add Start Packager script

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.3.1

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.4.0

app/views/RoomView/List.js
Now you can pull to refresh your messages list.
=> [NEW] Pull to refresh RoomView

app/constants/links.js
=> [REGRESSION] Use HTTPS links for sharing and markets protocol for review

app/lib/methods/subscriptions/room.js
=> [REGRESSION] Read message

app/containers/SearchBox.js, app/lib/rocketchat.js, app/views/RoomsListView/Header/index.js, app/views/RoomsListView/ListHeader/Directory.js, app/views/RoomsListView/ListHeader/SearchBar.js, app/views/RoomsListView/ListHeader/Sort.js, app/views/RoomsListView/ListHeader/index.js, app/views/RoomsListView/index.js
=> [FIX] Spotlight

.circleci/config.yml, package.json, yarn.lock
We started using Hermes, but we didn't follow appropriate docs from Bugsnag: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#uploading-hermes-source-maps
=> [FIX] Different sourcemaps generation for Hermes

app/lib/methods/subscriptions/room.js
If something happens on `sub.unsubscribe()`, `try/catch` would never handle it.
=> [FIX] Catch room unsubscribe error

app/i18n/locales/de.js
I missed to translate a single key with my last PR (#1735).
=> [i18n] missed a single translation key with last PR 

app/lib/Navigation.js, app/lib/methods/actions.js, app/views/ModalBlockView.js
For now it'll work with different behavior about loses connection.
When you try to submit a modal without connection, it'll loading for some seconds (5), and then, finish the loading without any response, then you can dismiss the modal, or try again. Try again not will generate any request, because the another request is on pipe yet, then when the connection go back, the request will be done and the interaction will work.
1. Open some App that use Modal
2. Disable connection with modal opened
3. Submit more than one time
4. Reconnect
=> [FIX] UIKit submit when connection lost

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.5.0

app/constants/settings.js, app/containers/MessageBox/RightButtons.android.js, app/containers/MessageBox/RightButtons.ios.js, app/containers/MessageBox/index.js
=> [IMPROVEMENT] Honor "Message_AudioRecorderEnabled"

app/sagas/createChannel.js, app/views/RoomView/index.js
When you create a new Channel, the button to join appear to you, before these changes you need to exit and back to the room to this disappear, or just press the button.
=> [FIX] Join Room

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/markdown/AtMention.js, app/containers/markdown/Hashtag.js, app/containers/markdown/Link.js, app/containers/markdown/index.js, app/containers/markdown/mergeTextNodes.js, app/presentation/RoomItem/LastMessage.js
=> [IMPROVEMENT] Markdown perf

ios/fastlane/Appfile, ios/fastlane/README.md, ios/fastlane/report.xml
=> [CHORE] Fastlane

app/containers/markdown/AtMention.js
=> [FIX] Empty mentions for @all and @here when real name is enabled

app/containers/markdown/index.js, app/views/RoomView/Header/Header.js
Some tests started to fail after #1827
=> [FIX] e2e tests

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.5.1

app/containers/message/Audio.js
=> [FIX] Ignore silent mode on audio player

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/Avatar.js
=> [FIX] Incorrect size params to avatar endpoint

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.6.0

app/containers/markdown/index.js, app/utils/url.js
=> [FIX] Encode Image URI

app/views/LoginSignupView.js
=> [FIX] Linkedin OAuth login

app/views/CreateChannelView.js
=> [CHORE] Fix typo in CreateChannel View

app/lib/rocketchat.js, app/sagas/createChannel.js
=> [FIX] Direct Message between multiple users REST

app/views/AuthenticationWebView.js
=> [FIX] Saml

app/lib/rocketchat.js, app/sagas/login.js, app/views/StatusView.js
=> [FIX] Change user own status

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.6.1

app/lib/methods/canOpenRoom.js, app/lib/rocketchat.js, app/sagas/deepLinking.js, app/views/RoomActionsView/index.js, app/views/RoomView/index.js, app/views/RoomsListView/index.js
=> [FIX] DM header blink

app/lib/methods/getSettings.js, app/sagas/selectServer.js, app/views/RoomsListView/ServerDropdown.js
=> [FIX] Split get settings into two requests

app/sagas/deepLinking.js
=> [REGRESSION] Invite Links

app/views/AuthenticationWebView.js
=> [FIX] Cas auth

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.6.4

app/containers/message/Blocks.js, app/views/ModalBlockView.js
=> [FIX] UIKit with only one block

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.7.0

app/constants/colors.js
=> [FIX] Action Tint Color on Black theme

app/containers/MessageBox/Mentions/MentionItem.js
* Open the app without network connection
* Type `/` on some room
=> [FIX] Show slash commands when disconnected

app/views/NewServerView.js
* Login to some server
* Click on add server
* Connect and navigate to login
* Using Back try to go back to the previous server
=> [FIX] Backhandler onBoarding

app/containers/UIKit/MultiSelect/index.js
=> [FIX] Hide system messages

app/lib/methods/subscriptions/room.js
`prepareUpdate` throw an Error when this record have some update pending, so, we need to surround these logic into a `try/catch`.
=> [FIX] Pending update

app/index.js, app/views/RoomActionsView/index.js
=> [FIX] AttachmentView (Android)(Tablet)

app/containers/message/Emoji.js
=> [FIX] ReactionsModal

app/views/ScreenLockConfigView.js
We'll enable biometry only if user provide it when put their first password.
=> [FIX] Default biometry enabled

app/lib/rocketchat.js
* Open the app
* Open the Share Extension and share something
* Come back to the app
* Try to do some action that needs to check permissions, like show message actions
* It throws an Error: `Cannot read property 'roles' of null`.
=> [FIX] Roles

patches/react-native-navigation-bar-color+2.0.1.patch
I opened a pull request at the library to fix this, while it's not merged we can use a patch.
https://github.com/thebylito/react-native-navigation-bar-color/pull/37
=> [FIX] Change bar color while no activity attached

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.8.0

app/views/RoomView/index.js
=> [FIX] Respect server HideSystemMessages

app/views/LoginView.js, app/views/WorkspaceView/index.js
=> [FIX] Show registration form when add server by a invite link

app/lib/rocketchat.js
We should set `user.username` when try login, then [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L916) will have the right value.
Test Plan:
* Login with some user with email 2FA enabled
* Press `Send me the code again`
=> [FIX] 2FA email - send code again

app/views/RoomView/Header/index.js
=> [FIX] Remove duplicated sCU condition

app/lib/rocketchat.js, app/views/RoomView/List.js
=> [IMPROVEMENT] Mark thread as read on open

app/containers/MessageActions/index.js
Closes #2236.
Use the same icon of our web client.
=> [FIX] Read receipt icon on action sheet

app/selectors/login.js
Refer to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/688#issuecomment-653223420
=> [FIX] Iframe auth Login Button

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.9.0

app/views/RegisterView.js
=> [FIX] Register crashing when error data is undefined

app/utils/navigation/index.js, app/views/SidebarView/index.js
=> [FIX] Get active route returning undefined

app/containers/ActionSheet/styles.js, app/containers/MessageActions/Header.js, app/containers/MessageActions/index.js
=> [FIX] Action sheet cutting emojis on the header

app/views/ShareView/index.js
=> [FIX] Mime type check crashing the app

app/views/NotificationPreferencesView/index.js
=> [FIX] Notification preferences update crashing the app

app/containers/MessageActions/index.js
=> [FIX] Create discussion not working from MessageActions

app/lib/methods/getSettings.js
I removed `InteractionManager`, which makes `try/catch` not work properly.
=> [FIX] getSettings not catching errors

app/lib/rocketchat.js
=> [REGRESSION] Jitsi Call doesn't send message link

android/app/build.gradle, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.10.0

app/containers/MessageActions/index.js, app/stacks/MasterDetailStack/index.js, app/views/ReadReceiptView/index.js
=> [FIX] Read receipts on tablet

app/views/RoomsListView/Header/Header.js
=> [FIX] Style not being applied on RoomsListView header subtitle

yarn.lock
=> Revert "[CHORE] Update commonmark.js "

__tests__/__snapshots__/Storyshots.test.js.snap, app/constants/colors.js, app/containers/markdown/AtMention.js, app/containers/markdown/Hashtag.js, app/containers/markdown/styles.js, app/lib/database/model/Subscription.js, app/lib/database/model/migrations.js, app/lib/database/schema/app.js, app/presentation/RoomItem/UnreadBadge.js, app/presentation/RoomItem/index.js
=> [IMPROVEMENT] Apply new mention colors

app/containers/MessageActions/index.js, app/containers/MessageBox/index.js, app/views/RoomMembersView/index.js
Adds missing icons after #2318
=> [FIX] Missing icons

app/views/RoomActionsView/index.js, app/views/RoomInfoView/index.js
More missing icons since our refactor
=> [FIX] More missing icons

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/Status/Status.js, app/presentation/RoomItem/RoomItem.js, app/presentation/RoomItem/Title.js, app/presentation/RoomItem/UpdatedAt.js, app/presentation/RoomItem/Wrapper.js, app/presentation/RoomItem/index.js, app/presentation/RoomItem/styles.js, storybook/index.js, storybook/stories/RoomItem.js, storybook/stories/StoriesSeparator.js, storybook/stories/index.js
=> [FIX] Vertically centralize RoomItem when `Store_Last_Message` is disabled

app/utils/log/index.js
Wraps the `logEvent()` method in a `try/catch` block  in case of any thrown exception by `analytics().logEvent()`  or `leaveBreadcrumb()`
=> [CHORE] Wrap logEvent in a try/catch

app/views/WorkspaceView/index.js
We need to look for `url` and fallback to `defaultUrl`
Closes #2371 
Closes https://github.com/RocketChat/Rocket.Chat/issues/18344
Co-authored-by: Gabriel Henriques <gabriel.henriques@rocket.chat>
=> [FIX] WorkspaceView not looking for the correct image path

android/build.gradle
=> [FIX] Android targeting wrong SDK version

app/containers/markdown/AtMention.js
If `mentions = [null, undefined]` the app was crashing with `Cannot read property 'username' of null`
Closes #2367
=> [FIX] Mentions crashing without username

app/containers/MessageErrorActions.js
Hopefully, the last missing icon...
=> [FIX] Missing delete icon on MessageErrorActions

app/lib/rocketchat.js
Quote on Group DMs should be using `room.rid` instead of `room.name`.
=> [FIX] Quote not working on Group DM

README.md
=> [DOCS] Add Whitelabel

CONTRIBUTING.md, README.md
Added CONTRIBUTING.md and refactor README.md
=> [DOCS] Refactor Readme

.github/ISSUE_TEMPLATE.md
Improve issue template to possibly get more info.
=> [CHORE] Improve ISSUE_TEMPLATE.md

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.11.0

.circleci/config.yml, android/fastlane/Fastfile
Alpha track requires Google's review. Let's change it to Internal track instead to match TestFlight's behaviour, so we can test both apps right away.
=> [CHORE] Add to Google Play Internal track instead of alpha

app/views/SidebarView/index.js
=> [FIX] Fix broken StatusView on tablet

app/lib/rocketchat.js
=> [FIX] REST for method calls not raising errors

android/app/src/main/java/chat/rocket/reactnative/Ejson.java
We should check null when get a value from mmkv storage.
I guess it's happening to users that are receiving a notification before open the app, that does the migration data, so, it doesn't have a userId yet on mmkv, and when try to concat a null value to a string got a NullPointer exception.
=> [FIX] Android crashing on receive a notification

app/lib/methods/subscriptions/room.js
Sometimes when we try to open the same room it's not opening.
1. Disconnect your device of network
2. Open the app
3. Open some room
4. Go back
5. Try to open the same room
=> [FIX] Rooms not opening again

app/views/SettingsView/index.js
=> [FIX] Wrong merge resolution after #2171

android/fastlane/Fastfile
=> [FIX] Upload to internal looking for the wrong path after #2171

app/utils/log/index.js
=> [FIX] Crashlytics reportError not working after #2171

app/lib/rocketchat.js
When login using password instead of a Oauth/SSO provider we shouldn't show the cookies clean alert.
1. login using password with TOTP enabled
2. press logout
3. It shown the cookies clean alert when shouldn't
=> [FIX] Logout from custom oauth when using password

package.json, patches/react-native-jitsi-meet+2.1.1.patch, yarn.lock
Jitsi Meet SDK 2.10.0 introduces a breaking change, which is failing on our CI.
Starting on 2.10.0, minimum SDK 23 is required on Android.
Let's stick to 2.9.0 for our app version 4.11.0.
=> [FIX] Jitsi breaking changes

package.json, patches/react-native-jitsi-meet+2.1.1.patch, yarn.lock
=> Update WatermelonDB to 0.19.0

app/lib/database/index.js, app/lib/encryption/encryption.js, app/lib/methods/enterpriseModules.js, app/lib/methods/getSettings.js, app/sagas/encryption.js, app/sagas/init.js, app/sagas/rooms.js, app/sagas/selectServer.js
Change experimental database file.
=> [CHORE] Change database location to Experimental Apps

app/i18n/index.js, app/sagas/login.js
Web client sets languages on a non-pattern way with all chars lowercased, so, we need to do some find to check the value used by mobile devices and moment (e.g.: pt-BR).
- Set language preference to Português do Brasil on web client
- It should be Português do Brasil on mobile clients too
=> [FIX] Language set by web client

ios/RocketChatRN/AppDelegate.m
Do migration from userDefaults to MMKV once on Official & Experimental iOS apps.
Install Experimental 4.11 app.
Login into any server.
Install Official app.
=> [FIX] Logout when install fresh Official and Experimental iOS app

patches/react-native+0.63.1.patch
Refer to https://github.com/facebook/react-native/issues/29279#issuecomment-658244428
=> [FIX] Show images in iOS 14

patches/react-native+0.63.1.patch, patches/react-native-webview+10.3.2.patch, patches/rn-fetch-blob+0.12.0.patch
Pin SSL Certificate on RN-Fetch-Blob layer.
You'll need a Server with SSL Client Certificate.
Everything should work as expected.
=> [REGRESSION] SSL Pinning stopped working after #2449

package.json, yarn.lock
=> [CHORE] Reset yarn cache

ios/RocketChatRN.xcodeproj/project.pbxproj, ios/fastlane/README.md, ios/fastlane/report.xml
=> [FIX] Fastlane iOS

android/app/build.gradle, android/app/src/foss/java/chat/rocket/reactnative/AdditionalModules.java, android/app/src/main/java/chat/rocket/reactnative/MainApplication.java, android/app/src/play/java/chat/rocket/reactnative/AdditionalModules.java, android/settings.gradle, react-native.config.js
=> [IMPROVEMENT] Add F-Droid modules as AdditionalModules

.circleci/config.yml, ios/fastlane/Fastfile
When creating a fork PR the iOS build is failing. This PR is a test to fix the Fastlane build process.
Create a PR and check if the iOS build will pass.
=> [FIX] Failing iOS build on fork PR

app/containers/Header/index.js
takes into account long server names/addresses on small screens which led to overlapping title and right buttons on the header bar
Closes #2497
=> [FIX] Rooms header overlapping right icons

app/utils/moment.js
Add missing locales in moment helper
Missing locales in moment helper
=> [FIX] Missing locales in moment helper

README.md
Set supported Android versions on Readme.
=> [DOCS] Update Android Supported versions

app/lib/database/model/User.js, app/lib/database/model/servers/User.js
`login_email_password` and `show_message_in_main_thread` placed on wrong `User` model.
- Login via email password
- Reload the app to cause a `resume` request
- Logout
- App should not ask to clear cookies
---
- Login via OAuth
- Reload the app to cause a `resume` request
- Logout
- App should ask to clear cookies
- Play with the user preference and the app should show/hide messages on the main thread accordingly
=> [FIX] Model columns misplaced

android/app/src/main/AndroidManifest.xml
Opt-out of scoped storage https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage
Closes #2456
=> [FIX] Share extension and save image not working on Android 10

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.13.0

app/presentation/RoomItem/index.js
=> [FIX] Initial users' status is not fetched

package.json
Uses `experimentalPlayDebug` as official flavor on Android.
=> [FIX] Yarn android scripts

app/views/RoomView/List.js
Currently, RoomView's List component has a state called `animated`, which triggers LayoutAnimations after the view is mounted.
It doesn't really render anything, so it could be a class variable instead of a state.
=> [IMPROVEMENT] Use class variable instead of state for List's animated

app/views/RoomView/index.js
Removes an if condition, which was trying to remove MessageActions from the tree, but it was causing the bottom sheet to be hidden.
I've removed the condition instead of fixing it, because there's close to no performance improvement in doing that.
It looks like the condition was to hide MessageActions when the user navigates to a thread, but it was never being fired. It was only happening when the app leaves focus (goes background), but then it would never restore the MessageActions.
- Go to a thread
- Minimize and restore the app
- Back to main channel
- Try to open MessageActions
=> [FIX] Bottom sheet being hidden sometimes

__tests__/__snapshots__/Storyshots.test.js.snap, app/constants/colors.js, app/presentation/UnreadBadge/getUnreadStyle.js, app/presentation/UnreadBadge/getUnreadStyle.test.js, app/utils/room.js, app/views/ThreadMessagesView/Item.stories.js, storybook/stories/index.js
We were using different colors for text and background badges.
This PR makes them use the same tone.
=> [IMPROVEMENT] Match background and text mention colors

android/gradle.properties
After I update my branch gradle not sync and yarn android or yarn android-whitelabel not working
```
A problem occurred evaluating project ':app'.
> Could not get unknown property 'APPLICATION_ID' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, …
```
=> [FIX] APPLICATION_ID typo

android/app/build.gradle
Gradle sync on single-server branch has error:
```
A problem occurred evaluating project ':app'.
> No signature of method: build_9su1sax1oamyt1xqgxd00k8ze.android() is applicable for argument types: (build_9su1sax1oamyt1xqgxd00k8ze$_run_closure1) values: [build_9su1sax1oamyt1xqgxd00k8ze$_run_closure1@7710e97e]
```
#2730
=> [FIX] Cast VERSIONCODE to integer

android/app/src/official/AndroidManifest.xml
=> [FIX] Official app without sharedUserId

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.13.1

app/lib/methods/helpers/mergeSubscriptionsRooms.js
Uses the same logic for channels order from the web client.
- Login the app
- Login the web client
- Both of them must have the same channels order
=> [FIX] Channels list not following the same sorting logic from web client

app/presentation/RoomItem/Touchable.js
This removes deprecation warning on logs from Animated.event by using the native driver
In order to check this, you  just need to open the app and you will see the warning related to this issue if you set ```console.disableYellowBox = false``` in the ReactotronConfig
=> [FIX] RoomItem using deprecated animated event signature

app/views/NewServerView/ServerInput/Item.js
Prevents multiline workspace URL as well as multiline usernames on the FlatList that appears when typing your workspace URL.
You need to be logged out in order to test this.
1. Open the app
2. Tap on 'Join a workspace'
3. Tap in the input field 
If the usernames or workspace URLs from the FlatList are too long they should render with '...' at the end.
=> [FIX] Server autocomplete text breaking line

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.14.0

app/containers/MessageBox/index.js, package.json, yarn.lock
We found a case where messagebox would still have a whitespace.
- Go to a thread
- Navigate back using gesture
- Open Messagebox
- Whitespace is there
It was fixed by using a longer timeout instead of InteractionManager.
It forces `resetTracking` to be fired after the `deferedInitializeAccessoryViewsAndHandleInsets`.
It also comments out some unused code.
=> [FIX] Messagebox tracking lost on pop gesture navigation

app/i18n/locales/tr.js
#2793 had a minor issue on lint and I merged anyway.
My bad.
=> [FIX] Lint on #2793

app/i18n/locales/de.js
This adds the new translation for the workspace login screen
=> [i18n] adding new strings for German translation on workspace login screen

app/views/RoomsListView/ServerDropdown.js
After changing server, server version would become null.
- Login server A
- Login server B
- Change server
- Check server version on SettingsView
=> [FIX] Server version becoming null on server change

app/constants/links.js
We were using Experimental's app id since #2701.
We can add a condition to test the correct version of the app (Official vs Experimental) later when Experimental is back to App Store.
=> [FIX] App Store using Experimental's app id

android/app/src/play/java/chat/rocket/reactnative/CustomPushNotification.java
App was using the same username for the whole notifications display loop.
Closes #2744
=> [FIX] Wrong username on push notifications

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist
=> Bump version to 4.14.1

app/containers/MessageBox/index.js
On iOS the video quality and size are decreasing. For example, the original file could be 2,3 MB and after uploading it is 815 kb in size. In order to solve this we should bypass compression using `compressVideoPreset: 'Passthrough'` from `react-native-image-crop-picker`.
In order to test this you should be logged in. For simplicity use the Web client as well.
1. Go to a room.
2. Upload a file from the Web client.
3. Download it from iOS.
4. Try to re-upload the same file again, but now from iOS.
Size should be the same as the file uploaded from Web client.
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] Video quality and size on iOS

app/containers/message/Reply.js
The prop in question is not being used anywhere in the implementation. It is not defined in the PropTypes either. Hence, can be safely removed.
=> [FIX] Reply component sending unused prop to Description

app/constants/settings.js, app/lib/methods/callJitsi.js, app/lib/methods/canOpenRoom.js, app/sagas/deepLinking.js, app/views/RoomActionsView/index.js, app/views/RoomInfoView/index.js, app/views/RoomView/index.js
Mobile support to https://github.com/RocketChat/Rocket.Chat/pull/17481
Closes #2505
=> [FIX] Support Jitsi_URL_Room_Hash

app/views/AttachmentView.js
We have the ability to save attachments to the camera roll on `AttachmentView`. To do that, we first download the attachment to a temp directory and then save to the camera roll but that leaves a temp file behind. In order to solve this, we need to flush the cached file using `RNFetchBlobResponse.flush()`
In order to test this you should be logged in and inside a room with  any media files (image/video).
1. Get in a room
2. Download an attachment (image/video).
3.  Check if temp file directory is empty (in order to do so you can `console.log(res.path())` and open that path from the Terminal).
=> [FIX] Temp attachment files not being flushed after saved to gallery

ios/RocketChatRN.xcodeproj/project.pbxproj
=> [CHORE] Update profiles

app/lib/methods/subscriptions/room.js, app/views/RoomView/index.js
When clicked on a user avatar in a group message and then clicked "message" to go to their DM room then the are another user was typing from the DM room that was in the group room. Because of that I need to unsubscribe that channel when user go to User Info view. If user press back in User Info View, the app will automatically subscribe that channel again.
1. Go to a group room
2. Click on a user's avatar
3. Click message to go to their DM room
4. Have someone in the group room start typing
5. Typing status shows up for that user even though they aren't in the DM room.
=> [FIX] DM rooms show typing status from last group room

app/containers/MessageActions/index.js, app/views/RoomView/index.js
If message has attachment, I copy the text from message.attachments[0].description, otherwise I just copy from message.msg
- Edit messages text that have image in it:
1. Go to channel or DM.
2. Upload some image and add the caption
3. Edit the message.
- Copy messages text that have image in it:
1. Go to channel or DM.
2. Upload some image and add the caption
3. Copy the message.
=> [FIX] Can't copy or edit media's description

app/views/RoomView/Header/RightButtons.js
Need to return default value (false) when is not match any condition
=> [FIX] RightButtonsContainer re-render check not returning default value

app/containers/Toast.js, app/containers/TwoFactor/index.js, app/views/ChangePasscodeView.js, app/views/ScreenLockedView.js
There're a couple of places where we're not sending the second argument, which doesn't really removes the listener.
Possibly it's not causing any weird behavior (at least the places I've found), but it's not working as intended.
=> [FIX] App not sending second argument for EventEmitter.removeListener on some places

app/lib/methods/sendMessage.js
When `Use real name` is set, author name is blinking as username and fixed after the response is received from the server. In order to fix this, I added the property `name` to the message user object that is sent to the Threads/Messages collections
In order to test this you must have `Use real name` activated.
1. Send a message to a room/thread
It shouldn't blink the username.
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] Temp message ignoring real name

app/views/NewMessageView.js
It limits query size to 50 on NewMessageView and removes observability.
- Nav to NewMessageView
- Only 50 records should be shown
- Updates on the list order shouldn't trigger a re-render
=> [FIX] Limit new message list query size to 50

app/containers/ReactionsModal.js
1. Go to a room
2. React to a message
3. Long press reaction
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] Reactions modal's backdrop color too light

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist, package.json
=> Bump version to 4.15.0

.circleci/config.yml, ios/NotificationService/Info.plist, ios/ShareRocketChatRN/Info.plist
On #2701 we create new entries on Info.plist, but they weren't added to all targets.
Closes #2877
Closes #2819
- Install Rocket.Chat official (without having Experimental on the same device)
- Try to share anything
=> [FIX] Share extension not working correctly on Official app

app/containers/MessageBox/index.js
Use `auxiliaryColor` on placeholder.
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table >
=> [FIX] Messagebox's placeholder color is too bright

e2e/tests/room/05-createdmgroup.spec.js
For now we don't have e2e testing for group DM, so we decide to adding it.
=> [TESTS] Add E2E tests to group DM

app/views/CreateDiscussionView/index.js
Depending on the channel and current status of encryption, server would fail to create a discussion because of null value on encryption param.
- Tests should pass
=> [FIX] Create discussion request being sent with null value on encryption param

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist, package.json
=> Bump version to 4.16.0

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist, package.json
=> Bump version to 4.17.0

app/views/AuthenticationWebView.js
On #2978, we added support to SAML with 2FA.
2FA works by doing an initial login request to the server, which is going to fail requesting TOTP.
After that we request TOTP using a modal and repeat the process.
Since the login is done from a webview and it takes some time, there's enough time for the URL to open the webclient, which opens TOTP modal before reaching the app, that's also going to request TOTP.
In order to prevent this behaviour, we added `immediate` prop to debounce, so we close webview and open TOTP modal from the app right away.
However, some servers require an additional delay to evaluate the token causing the app to fail in the first login request with `No matching login attempt found`.
This PR removes `immediate` from debounce in order to keep SAML working for all use …
=> [REGRESSION] SAML stopped working after #2978

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist, package.json
=> Bump version to 4.16.1

__tests__/__snapshots__/Storyshots.test.js.snap, app/containers/message/User.js
`MessageUser`'s touchable would take the whole space until `time`.
Touching that empty space area would navigate the user to `User Info`, most probably by a mistake.
This PR doesn't change anything visually, it just take a smaller space.
Added red background just to illustrate the touchable area.
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] Message author touchable taking whole space available

android/app/build.gradle, ios/RocketChatRN.xcodeproj/project.pbxproj, ios/RocketChatRN/Info.plist, ios/ShareRocketChatRN/Info.plist, package.json
=> Bump version to 4.16.2

app/definition/ITeam.js, e2e/helpers/data_setup.js
Currently mocha does not support ES6 imports which makes the e2e tests to instantly crash due to the ITeam file being an ES6 export being used on the `data_setup`. In order to solve this I just replicated the `TEAM_TYPE` object on the `data_setup` instead of importing it.
=> [FIX] Tests not working by ES6 import

app/lib/rocketchat.js
- Disable `API_Use_REST_For_DDP_Calls`
- Jump to an old message, so load surrounding method is called
- Tap `Load Next` to trigger `loadNextMessages`
- Messages were loaded :)
=> [FIX] Method calls not sending date params as EJSON

app/views/NewMessageView.js
Prevent old server versions from visualizing team features since they don't support it
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table >
=> [FIX] Check for old servers for Teams

app/constants/settings.js, app/i18n/locales/en.json, app/i18n/locales/pt-BR.json, app/views/StatusView.js
Show/Hide the Invisible Status when the admin option allows/disallows the Invisible status option from all users.
After adding a new feature to admin allows/disallows the Invisible status option from all users: https://github.com/RocketChat/Rocket.Chat/pull/20084 
The app still showing the Invisible button when the server disallows the Invisible status.
- Access admin configurations
- In `Accounts` -> `Disallows the Invisible status option`
- Open the app
- Edit Status
<table>
<thead>
<tr>
<th>If the admin change the option while the app is open</th>
<th>After re-open the app</th>
</thead>
</tr>
<tbody>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] Option to prevent users from using Invisible status

app/views/TeamChannelsView.js
<table>
<thead>
<tr>
<th>After</th>
</thead>
</tr>
<tbody>
<tr>
<td>
https://user-images.githubusercontent.com/804994/120862782-dfaaa680-c55f-11eb-9306-8cc056d8f3d1.mp4
</td>
<td>
https://user-images.githubusercontent.com/804994/120862789-e33e2d80-c55f-11eb-8dbf-164fba2dcc91.mp4
</td>
</tr>
</tbody>
</table>
=> [FIX] Item not animating on tap on team's channels view

app/views/DirectoryView/index.js
Change the param `t: 'c'` to `t: item.t` , passing the correct param to navigation
- Go to `Directory`
- Search for `Channels`
- Click in any private or public channel
<table>
<tbody>
<tr>
<td>
</td>
</tr>
</tbody>
</table>
=> [FIX] Directory sending incorrect room type
